<?php
define("_EDEN_GOOGLE_CAPTCHA_PRIVATE_KEY","6Ld6AtsSAAAAABxCO8QdG_6maiMwFfejOmd4x_CA");
define("_EDEN_GOOGLE_CAPTCHA_PUBLIC_KEY","6Ld6AtsSAAAAAFtfSXnYjL1HrxWb5lPGKaD-Yv7x");

$url_adds = $eden_cfg['url_edencms_files']."img_adds/";
$url_admins = $eden_cfg['url_edencms_files']."img_admins/";
$url_admins_category = $eden_cfg['url_edencms_files']."img_admins_category/";
$url_admins_images_main = $eden_cfg['url_edencms_files']."img_admins_images/main/";
$url_admins_images_usr = $eden_cfg['url_edencms_files']."img_admins_images/admins/";
$url_articles = $eden_cfg['url_edencms_files']."img_articles/";
$url_articles_channels = $eden_cfg['url_edencms_files']."img_articles_channels/";
$url_auto = $eden_cfg['url_edencms_files']."img_auto/";
$url_calendar = $eden_cfg['url_edencms_files']."img_calendar/";
$url_category = $eden_cfg['url_edencms_files']."img_category/";
$url_clan_awards = $eden_cfg['url_edencms_files']."img_clan_awards/";
$url_clan_maps = $eden_cfg['url_edencms_files']."img_clan_maps/";
$url_download = $eden_cfg['url_edencms_files']."img_download/";
$url_eden_images = $eden_cfg['url_edencms_files']."img_eden_images/";
$url_files = $eden_cfg['url_edencms_files']."files/";
$url_flags = $eden_cfg['url_edencms_files']."img_flags/";
$url_forum = $eden_cfg['url_edencms_files']."img_forum/";
$url_games = $eden_cfg['url_edencms_files']."img_games/";
$url_league_awards = $eden_cfg['url_edencms_files']."img_league_awards/";
$url_league_team = $eden_cfg['url_edencms_files']."img_league_teams/";
$url_links = $eden_cfg['url_edencms_files']."img_links/";
$url_mtg_cards = $eden_cfg['url_edencms_files']."img_mtg_cards/";
$url_ntb = $eden_cfg['url_edencms_files']."img_ntb/";
$url_poker_cards_big = $eden_cfg['url_edencms_files']."poker_cards/big/";
$url_poker_cards_small = $eden_cfg['url_edencms_files']."img_poker_cards/small/";
$url_profiles = $eden_cfg['url_edencms_files']."img_profiles/";
$url_project_images = $eden_cfg['url']."images/";
$url_rss = $eden_cfg['url_edencms_files']."img_rss/";
$url_rss_itunes = $eden_cfg['url_edencms_files']."img_rss_itunes/";
$url_screenshots = $eden_cfg['url_edencms_files']."img_screenshots/";
$url_shop_clothes_colors = $eden_cfg['url_join']."edencms/img_shop/clothes_colors/";
$url_shop_clothes_design = $eden_cfg['url_edencms_files']."img_shop/clothes_design/";
$url_shop_clothes_style = $eden_cfg['url_join']."edencms/img_shop/clothes_style/";
$url_shop_clothes_style_parent = $eden_cfg['url_join']."edencms/img_shop/clothes_style_parent/";
$url_shop_man = $eden_cfg['url_edencms_files']."img_shop/manufacturers/";
$url_shop_prod = $eden_cfg['url_edencms_files']."img_shop/products/";
$url_shop_payments = $eden_cfg['url_edencms_files']."img_shop/payments/";
$url_smiles = $eden_cfg['url_edencms_files']."img_smiles/";
$url_todo_category = $eden_cfg['url_edencms_files']."img_todo_category/";

$ftp_path_adds = $eden_cfg['ftp_path_files']."img_adds/";
$ftp_path_admins = $eden_cfg['ftp_path_files']."img_admins/";
$ftp_path_admins_category = $eden_cfg['ftp_path_files']."img_admins_category/";
$ftp_path_articles = $eden_cfg['ftp_path_files']."img_articles/";
$ftp_path_articles_channels = $eden_cfg['ftp_path_files']."img_articles_channels/";
$ftp_path_auto = $eden_cfg['ftp_path_files']."img_auto/";
$ftp_path_calendar = $eden_cfg['ftp_path_files']."img_calendar/";
$ftp_path_category = $eden_cfg['ftp_path_files']."img_category/";
$ftp_path_clan_maps =  $eden_cfg['ftp_path_files']."img_clan_maps/";
$ftp_path_download = $eden_cfg['ftp_path_files']."img_download/";
$ftp_path_files = $eden_cfg['ftp_path_files']."files/";
$ftp_path_flags = $eden_cfg['ftp_path_files']."img_flags/";
$ftp_path_games = $eden_cfg['ftp_path_files']."img_games/";
$ftp_path_images_usr = $eden_cfg['ftp_path_files']."img_admins_images/admins/";
$ftp_path_images_main = $eden_cfg['ftp_path_files']."img_admins_images/main/";
$ftp_path_league_team = $eden_cfg['ftp_path_files']."img_league_teams/";
$ftp_path_league_awards = $eden_cfg['ftp_path_files']."img_league_awards/";
$ftp_path_links = $eden_cfg['ftp_path_files']."img_links/";
$ftp_path_mtg_cards = $eden_cfg['ftp_path_files']."img_mtg_cards/";
$ftp_path_ntb = $eden_cfg['ftp_path_files']."img_ntb/";
$ftp_path_project_images = $eden_cfg['ftp_path_main']."images/";
$ftp_path_profiles = $eden_cfg['ftp_path_files']."img_profiles/";
$ftp_path_rss = $eden_cfg['ftp_path_files']."img_rss/";
$ftp_path_rss_itunes = $eden_cfg['ftp_path_files']."img_rss_itunes/";
$ftp_path_screenshots = $eden_cfg['ftp_path_files']."img_screenshots/";
$ftp_path_shop = $eden_cfg['ftp_path_files']."img_shop/";
$ftp_path_shop_clothes_colors = $eden_cfg['ftp_path_files']."img_shop/clothes_colors/";
$ftp_path_shop_clothes_design = $eden_cfg['ftp_path_files']."img_shop/clothes_design/";
$ftp_path_shop_clothes_style = $eden_cfg['ftp_path_files']."img_shop/clothes_style/";
$ftp_path_shop_clothes_style_parent = $eden_cfg['ftp_path_files']."img_shop/clothes_style_parent/";
$ftp_path_shop_man = $eden_cfg['ftp_path_files']."img_shop/manufacturers/";
$ftp_path_shop_prod = $eden_cfg['ftp_path_files']."img_shop/products/";
$ftp_path_shop_payments = $eden_cfg['ftp_path_files']."img_shop/payments/";
$ftp_path_smiles = $eden_cfg['ftp_path_files']."img_smiles/";
$ftp_path_todo_category = $eden_cfg['ftp_path_files']."img_todo_category/";

$db_news = $eden_cfg['db_prefix_join']."_news";
$db_adds = $eden_cfg['db_prefix_join']."_adds";
$db_admin = $eden_cfg['db_prefix_join']."_admin";
$db_admin_category  = $eden_cfg['db_prefix_join']."_admin_category";
$db_admin_clan = $eden_cfg['db_prefix_join']."_admin_clan";
$db_admin_contact  = $eden_cfg['db_prefix_join']."_admin_contact";
$db_admin_contact_shop  = $eden_cfg['db_prefix_join']."_admin_contact_shop";
$db_admin_customize  = $eden_cfg['db_prefix_join']."_admin_customize";
$db_admin_game = $eden_cfg['db_prefix_join']."_admin_game";
$db_admin_images = $eden_cfg['db_prefix_join']."_admin_images";
$db_admin_info = $eden_cfg['db_prefix_join']."_admin_info";
$db_admin_hw  = $eden_cfg['db_prefix_join']."_admin_hw";
$db_admin_poker  = $eden_cfg['db_prefix_join']."_admin_poker";
$db_admin_guids = $eden_cfg['db_prefix']."_admin_guids";
$db_articles = $eden_cfg['db_prefix_join']."_articles";
$db_articles_files = $eden_cfg['db_prefix_join']."_articles_files";
$db_articles_channel = $eden_cfg['db_prefix_join']."_articles_channels";
$db_articles_images = $eden_cfg['db_prefix_join']."_articles_images";
$db_auto = $eden_cfg['db_prefix']."_auto";
$db_auto_typ = $eden_cfg['db_prefix']."_auto_typ";
$db_auto_znacka = $eden_cfg['db_prefix']."_auto_znacka";
$db_ban = $eden_cfg['db_prefix_join']."_ban";
$db_calendar = $eden_cfg['db_prefix']."_calendar_msg";
$db_category  = $eden_cfg['db_prefix_join']."_category";
$db_clan_awards = $eden_cfg['db_prefix']."_clans_awards";
$db_clan_clanwars = $eden_cfg['db_prefix']."_clans_clanwars";
$db_clan_games = $eden_cfg['db_prefix']."_clans_games";
$db_clan_games_main = $eden_cfg['db_prefix']."_clans_games_main";
$db_clan_gameleague = $eden_cfg['db_prefix']."_clans_gameleague";
$db_clan_gametype = $eden_cfg['db_prefix']."_clans_gametype";
$db_clan_maps = $eden_cfg['db_prefix']."_clans_maps";
$db_clan_setup = $eden_cfg['db_prefix']."_clans_setup";
$db_comments = $eden_cfg['db_prefix_join']."_comments";
$db_comments_log = $eden_cfg['db_prefix_join']."_comments_log";
$db_compare_categories = $eden_cfg['db_prefix']."_compare_categories";
$db_compare_makers = $eden_cfg['db_prefix']."_compare_makers";
$db_compare_ntb = $eden_cfg['db_prefix']."_compare_ntb";
$db_compare_parts = $eden_cfg['db_prefix']."_compare_parts";
$db_compare_txt = $eden_cfg['db_prefix']."_compare_txt";
$db_contests = $eden_cfg['db_prefix']."_contests";
$db_country  = $eden_cfg['db_prefix_join']."_country";
$db_cups_bracket = $eden_cfg['db_prefix']."_cups_bracket";
$db_dictionary = $eden_cfg['db_prefix']."_dictionary";
$db_download = $eden_cfg['db_prefix']."_download";
$db_download_category = $eden_cfg['db_prefix']."_download_category";
$db_eden_log = $eden_cfg['db_prefix']."_log";
$db_filters = $eden_cfg['db_prefix']."_filters";
$db_forum_posts = $eden_cfg['db_prefix']."_forum_posts";
$db_forum_posts_log = $eden_cfg['db_prefix']."_forum_posts_log";
$db_forum_posts_edit_log = $eden_cfg['db_prefix']."_forum_posts_edit_log";
$db_forum_posts_report_log = $eden_cfg['db_prefix']."_forum_posts_report_log";
$db_forum_pm = $eden_cfg['db_prefix']."_forum_pm";
$db_forum_pm_log = $eden_cfg['db_prefix']."_forum_pm_log";
$db_forum_topic = $eden_cfg['db_prefix']."_forum_topic";
$db_gamesrv = $eden_cfg['db_prefix']."_clans_gameservers";
$db_groups = $eden_cfg['db_prefix_join']."_groups";
$db_guestbook = $eden_cfg['db_prefix']."_guestbook";
$db_guestbook_admin = $eden_cfg['db_prefix']."_guestbook_admin";
$db_guestbook_topic = $eden_cfg['db_prefix']."_guestbook_topic";
$db_ip_to_country = $eden_cfg['db_prefix_join']."_ip_to_country";
$db_language = $eden_cfg['db_prefix_join']."_language";
$db_league_awards = $eden_cfg['db_prefix']."_league_awards";
$db_league_draft = $eden_cfg['db_prefix']."_league_draft";
$db_league_guids = $eden_cfg['db_prefix']."_league_guids";
$db_league_leagues = $eden_cfg['db_prefix']."_league_leagues";
$db_league_log = $eden_cfg['db_prefix']."_league_log";
$db_league_players = $eden_cfg['db_prefix']."_league_players";
$db_league_players_bans = $eden_cfg['db_prefix']."_league_players_bans";
$db_league_players_leagues = $eden_cfg['db_prefix']."_league_players_leagues";
$db_league_requests = $eden_cfg['db_prefix']."_league_requests";
$db_league_seasons = $eden_cfg['db_prefix']."_league_seasons";
$db_league_seasons_results_players = $eden_cfg['db_prefix']."_league_seasons_results_players";
$db_league_seasons_results_teams = $eden_cfg['db_prefix']."_league_seasons_results_teams";
$db_league_seasons_round_allowed_players = $eden_cfg['db_prefix']."_league_seasons_round_allowed_players";
$db_league_seasons_rounds = $eden_cfg['db_prefix']."_league_seasons_rounds";
$db_league_seasons_rounds_results_players = $eden_cfg['db_prefix']."_league_seasons_rounds_results_players";
$db_league_seasons_rounds_results_teams = $eden_cfg['db_prefix']."_league_seasons_rounds_results_teams";
$db_league_teams = $eden_cfg['db_prefix']."_league_teams";
$db_league_teams_sub = $eden_cfg['db_prefix']."_league_teams_sub";
$db_league_teams_sub_leagues = $eden_cfg['db_prefix']."_league_teams_sub_leagues";
$db_links = $eden_cfg['db_prefix']."_links";
$db_mtg_cards = $eden_cfg['db_prefix']."_mtg_cards";
$db_podcast = $eden_cfg['db_prefix']."_podcast";
$db_podcast_channel = $eden_cfg['db_prefix']."_podcast_channel";
$db_poker_cardrooms = $eden_cfg['db_prefix']."_poker_cardrooms";
$db_poker_hands = $eden_cfg['db_prefix']."_poker_hands";
$db_poker_variants = $eden_cfg['db_prefix']."_poker_variants";
$db_poll_answers  = $eden_cfg['db_prefix']."_poll_answers";
$db_poll_questions  = $eden_cfg['db_prefix']."_poll_questions";
$db_profiles = $eden_cfg['db_prefix']."_profiles";
$db_reserved_words = $eden_cfg['db_prefix_join']."_reserved_words";
$db_rss = $eden_cfg['db_prefix']."_rss";
$db_rss_lang = $eden_cfg['db_prefix']."_rss_lang";
$db_sessions = $eden_cfg['db_prefix']."_sessions";
$db_setup = $eden_cfg['db_prefix']."_setup";
$db_setup_images = $eden_cfg['db_prefix']."_setup_images";
$db_setup_lang = $eden_cfg['db_prefix']."_setup_lang";
$db_shop_basket = $eden_cfg['db_prefix']."_shop_basket";
$db_shop_carriage = $eden_cfg['db_prefix_join']."_shop_carriage";
$db_shop_carriage_category = $eden_cfg['db_prefix_join']."_shop_carriage_category";
$db_shop_clothes_colors = $eden_cfg['db_prefix_join']."_shop_clothes_colors";
$db_shop_clothes_design = $eden_cfg['db_prefix']."_shop_clothes_design";
$db_shop_clothes_size = $eden_cfg['db_prefix_join']."_shop_clothes_size";
$db_shop_clothes_style = $eden_cfg['db_prefix_join']."_shop_clothes_style";
$db_shop_clothes_style_parents = $eden_cfg['db_prefix_join']."_shop_clothes_style_parents";
$db_shop_currency = $eden_cfg['db_prefix_join']."_shop_currency";
$db_shop_discount_category = $eden_cfg['db_prefix_join']."_shop_discount_categories";
$db_shop_gender = $eden_cfg['db_prefix_join']."_shop_gender";
$db_shop_man = $eden_cfg['db_prefix_join']."_shop_manufacturers";
$db_shop_orders = $eden_cfg['db_prefix']."_shop_orders";
$db_shop_orders_log = $eden_cfg['db_prefix']."_shop_orders_log";
$db_shop_orders_product = $eden_cfg['db_prefix']."_shop_orders_product";
$db_shop_payment_methods = $eden_cfg['db_prefix_join']."_shop_payment_methods";
$db_shop_pictures = $eden_cfg['db_prefix']."_shop_pictures";
$db_shop_product = $eden_cfg['db_prefix']."_shop_product";
$db_shop_product_changes = $eden_cfg['db_prefix']."_shop_product_changes";
$db_shop_product_clothes = $eden_cfg['db_prefix']."_shop_product_clothes";
$db_shop_sellers = $eden_cfg['db_prefix']."_shop_sellers";
$db_shop_setup = $eden_cfg['db_prefix']."_shop_setup";
$db_shop_tax_class = $eden_cfg['db_prefix_join']."_shop_tax_class";
$db_shop_tax_rates = $eden_cfg['db_prefix_join']."_shop_tax_rates";
$db_shop_tax_zones = $eden_cfg['db_prefix_join']."_shop_zones";
$db_smiles = $eden_cfg['db_prefix']."_smiles";
$db_streams = $eden_cfg['db_prefix']."_streams";
$db_streams_date = $eden_cfg['db_prefix']."_streams_date";
$db_thumbs = $eden_cfg['db_prefix']."_thumbs";
$db_todo = $eden_cfg['db_prefix']."_todo";
$db_todo_category = $eden_cfg['db_prefix']."_todo_category";
$db_tournaments = $eden_cfg['db_prefix']."_tournaments"; 
$db_videos = $eden_cfg['db_prefix']."_videos";

define("_URL_ADS",$eden_cfg['url_edencms_files']."img_adds/");
define("_URL_ADMINS",$eden_cfg['url_edencms_files']."img_admins/");
define("_URL_ADMINS_CATEGORIES",$eden_cfg['url_edencms_files']."img_admins_category/");
define("_URL_ADMINS_IMAGES_MAIN",$eden_cfg['url_edencms_files']."img_admins_images/main/");
define("_URL_ADMINS_IMAGES_USR",$eden_cfg['url_edencms_files']."img_admins_images/admins/");
define("_URL_ARTICLES",$eden_cfg['url_edencms_files']."img_articles/");
define("_URL_ARTICLES_CHANNELS",$eden_cfg['url_edencms_files']."img_articles_channels/");
define("_URL_AUTO",$eden_cfg['url_edencms_files']."img_auto/");
define("_URL_CALENDAR",$eden_cfg['url_edencms_files']."img_calendar/");
define("_URL_CATEGORIES",$eden_cfg['url_edencms_files']."img_category/");
define("_URL_CLAN_AWARDS",$eden_cfg['url_edencms_files']."img_clan_awards/");
define("_URL_CLAN_MAPS",$eden_cfg['url_edencms_files']."img_clan_maps/");
define("_URL_CLAN_SCREENSHOTS",$eden_cfg['url_edencms_files']."img_screenshots/");
define("_URL_DOWNLOADS",$eden_cfg['url_edencms_files']."img_download/");
define("_URL_EDEN_IMAGES",$eden_cfg['url_edencms_files']."img_eden_images/");
define("_URL_FILES",$eden_cfg['url_edencms_files']."files/");
define("_URL_FLAGS",$eden_cfg['url_edencms_files']."img_flags/");
define("_URL_FORUM",$eden_cfg['url_edencms_files']."img_forum/");
define("_URL_GAMES",$eden_cfg['url_edencms_files']."img_games/");
define("_URL_LEAGUE_AWARDS",$eden_cfg['url_edencms_files']."img_league_awards/");
define("_URL_LEAGUE_TEAMS",$eden_cfg['url_edencms_files']."img_league_teams/");
define("_URL_LINKS",$eden_cfg['url_edencms_files']."img_links/");
define("_URL_MTG_CARDS",$eden_cfg['url_edencms_files']."img_mtg_cards/");
define("_URL_POKER_CARDS_BIG",$eden_cfg['url_edencms_files']."poker_cards/big/");
define("_URL_POKER_CARDS_SMALL",$eden_cfg['url_edencms_files']."img_poker_cards/small/");
define("_URL_PROFILES",$eden_cfg['url_edencms_files']."img_profiles/");
define("_URL_PROJECT_IMAGES",$eden_cfg['url']."images/");
define("_URL_RSS",$eden_cfg['url_edencms_files']."img_rss/");
define("_URL_RSS_ITUNES",$eden_cfg['url_edencms_files']."img_rss_itunes/");
define("_URL_SHOP_CLOTHES_COLORS",$eden_cfg['url_join']."edencms/img_shop/clothes_colors/");
define("_URL_SHOP_CLOTHES_DESIGNS",$eden_cfg['url_edencms_files']."img_shop/clothes_design/");
define("_URL_SHOP_CLOTHES_STYLES",$eden_cfg['url_join']."edencms/img_shop/clothes_style/");
define("_URL_SHOP_CLOTHES_STYLES_PARENTS",$eden_cfg['url_join']."edencms/img_shop/clothes_style_parent/");
define("_URL_SHOP_MANUFACTURERS",$eden_cfg['url_edencms_files']."img_shop/manufacturers/");
define("_URL_SHOP_PRODUCTS",$eden_cfg['url_edencms_files']."img_shop/products/");
define("_URL_SHOP_PAYMENTS",$eden_cfg['url_edencms_files']."img_shop/payments/");
define("_URL_SMILES",$eden_cfg['url_edencms_files']."img_smiles/");
define("_URL_TODO_CATEGORIES",$eden_cfg['url_edencms_files']."img_todo_category/");

define("_FTP_PATH_ADS",$eden_cfg['ftp_path']."img_adds/");
define("_FTP_PATH_ADMINS",$eden_cfg['ftp_path']."img_admins/");
define("_FTP_PATH_ADMINS_CATEGORY",$eden_cfg['ftp_path']."img_admins_category/");
define("_FTP_PATH_ARTICLES",$eden_cfg['ftp_path']."img_articles/");
define("_FTP_PATH_ARTICLES_CHANNELS",$eden_cfg['ftp_path']."img_articles_channels/");
define("_FTP_PATH_AUTO",$eden_cfg['ftp_path']."img_auto/");
define("_FTP_PATH_CALENDAR",$eden_cfg['ftp_path']."img_calendar/");
define("_FTP_PATH_CATEGORIES",$eden_cfg['ftp_path']."img_category/");
define("_FTP_PATH_CLAN_MAPS", $eden_cfg['ftp_path']."img_clan_maps/");
define("_FTP_PATH_CLAN_SCREENSHOTS",$eden_cfg['ftp_path']."img_screenshots/");
define("_FTP_PATH_DOWNLOADS",$eden_cfg['ftp_path']."img_download/");
define("_FTP_PATH_FILES",$eden_cfg['ftp_path']."files/");
define("_FTP_PATH_FLAGS",$eden_cfg['ftp_path']."img_flags/");
define("_FTP_PATH_GAMES",$eden_cfg['ftp_path']."img_games/");
define("_FTP_PATH_IMAGES_USR",$eden_cfg['ftp_path']."img_admins_images/admins/");
define("_FTP_PATH_IMAGES_MAIN",$eden_cfg['ftp_path']."img_admins_images/main/");
define("_FTP_PATH_LEAGUE_TEAMS",$eden_cfg['ftp_path']."img_league_teams/");
define("_FTP_PATH_LEAGUE_AWARDS",$eden_cfg['ftp_path']."img_league_awards/");
define("_FTP_PATH_LINKS",$eden_cfg['ftp_path']."img_links/");
define("_FTP_PATH_MTG_CARDS",$eden_cfg['ftp_path']."img_mtg_cards/");
define("_FTP_PATH_COMPARE_NTB",$eden_cfg['ftp_path']."img_ntb/");
define("_FTP_PATH_PROJECT_IMAGES",$eden_cfg['ftp_path_main']."images/");
define("_FTP_PATH_PROFILES",$eden_cfg['ftp_path']."img_profiles/");
define("_FTP_PATH_RSS",$eden_cfg['ftp_path']."img_rss/");
define("_FTP_PATH_RSS_ITUNES",$eden_cfg['ftp_path']."img_rss_itunes/");
define("_FTP_PATH_SHOP",$eden_cfg['ftp_path']."img_shop/");
define("_FTP_PATH_SHOP_CLOTHES_COLORS",$eden_cfg['ftp_path']."img_shop/clothes_colors/");
define("_FTP_PATH_SHOP_CLOTHES_DESIGNS",$eden_cfg['ftp_path']."img_shop/clothes_design/");
define("_FTP_PATH_SHOP_CLOTHES_STYLES",$eden_cfg['ftp_path']."img_shop/clothes_style/");
define("_FTP_PATH_SHOP_CLOTHES_STYLES_PARENTS",$eden_cfg['ftp_path']."img_shop/clothes_style_parent/");
define("_FTP_PATH_SHOP_MANUFACTURES",$eden_cfg['ftp_path']."img_shop/manufacturers/");
define("_FTP_PATH_SHOP_PRODUCTS",$eden_cfg['ftp_path']."img_shop/products/");
define("_FTP_PATH_SHOP_PAYMENST",$eden_cfg['ftp_path']."img_shop/payments/");
define("_FTP_PATH_SMILES",$eden_cfg['ftp_path']."img_smiles/");
define("_FTP_PATH_TODO_CATEGORIES",$eden_cfg['ftp_path']."img_todo_category/");

define("_DB_NEWS",$eden_cfg['db_prefix_join']."_news");
define("_DB_NEWS_TAGS",$eden_cfg['db_prefix_join']."_news_tags");
define("_DB_ADS",$eden_cfg['db_prefix_join']."_adds");
define("_DB_ADMINS",$eden_cfg['db_prefix_join']."_admin");
define("_DB_ADMINS_CATEGORIES",$eden_cfg['db_prefix_join']."_admin_category");
define("_DB_ADMINS_CLANS",$eden_cfg['db_prefix_join']."_admin_clan");
define("_DB_ADMINS_CONTACTS",$eden_cfg['db_prefix_join']."_admin_contact");
define("_DB_ADMINS_CONTACTS_SHOP",$eden_cfg['db_prefix_join']."_admin_contact_shop");
define("_DB_ADMINS_CUSTOMIZE",$eden_cfg['db_prefix_join']."_admin_customize");
define("_DB_ADMINS_GAMES",$eden_cfg['db_prefix_join']."_admin_game");
define("_DB_ADMINS_IMAGES",$eden_cfg['db_prefix_join']."_admin_images");
define("_DB_ADMINS_INFO",$eden_cfg['db_prefix_join']."_admin_info");
define("_DB_ADMINS_HW",$eden_cfg['db_prefix_join']."_admin_hw");
define("_DB_ADMINS_POKER",$eden_cfg['db_prefix_join']."_admin_poker");
define("_DB_ADMINS_GUIDS",$eden_cfg['db_prefix']."_admin_guids");
define("_DB_ARTICLES",$eden_cfg['db_prefix_join']."_articles");
define("_DB_ARTICLES_FILES",$eden_cfg['db_prefix_join']."_articles_files");
define("_DB_ARTICLES_CHANNELS",$eden_cfg['db_prefix_join']."_articles_channels");
define("_DB_ARTICLES_IMAGES",$eden_cfg['db_prefix_join']."_articles_images");
define("_DB_ARTICLES_TAGS",$eden_cfg['db_prefix_join']."_articles_tags");
define("_DB_AUTO",$eden_cfg['db_prefix']."_auto");
define("_DB_AUTO_TYPES",$eden_cfg['db_prefix']."_auto_typ");
define("_DB_AUTO_MODELS",$eden_cfg['db_prefix']."_auto_znacka");
define("_DB_BANS",$eden_cfg['db_prefix_join']."_ban");
define("_DB_CALENDARS",$eden_cfg['db_prefix']."_calendar_msg");
define("_DB_CATEGORIES",$eden_cfg['db_prefix_join']."_category");
define("_DB_CLAN_AWARDS",$eden_cfg['db_prefix']."_clans_awards");
define("_DB_CLAN_CLANWARS",$eden_cfg['db_prefix']."_clans_clanwars");
define("_DB_CLAN_GAMES",$eden_cfg['db_prefix']."_clans_games");
define("_DB_CLAN_GAMES_MAIN",$eden_cfg['db_prefix']."_clans_games_main");
define("_DB_CLAN_GAMELEAGUES",$eden_cfg['db_prefix']."_clans_gameleague");
define("_DB_CLAN_GAMESERVERS",$eden_cfg['db_prefix']."_clans_gameservers");
define("_DB_CLAN_GAMETYPES",$eden_cfg['db_prefix']."_clans_gametype");
define("_DB_CLAN_MAPS",$eden_cfg['db_prefix']."_clans_maps");
define("_DB_CLAN_SETUP",$eden_cfg['db_prefix']."_clans_setup");
define("_DB_COMMENTS",$eden_cfg['db_prefix_join']."_comments");
define("_DB_COMMENTS_LOG",$eden_cfg['db_prefix_join']."_comments_log");
define("_DB_COMPARE_CATEGORIES",$eden_cfg['db_prefix']."_compare_categories");
define("_DB_COMPARE_MAKERS",$eden_cfg['db_prefix']."_compare_makers");
define("_DB_COMPARE_NTB",$eden_cfg['db_prefix']."_compare_ntb");
define("_DB_COMPARE_PARTS",$eden_cfg['db_prefix']."_compare_parts");
define("_DB_COMPARE_TXT",$eden_cfg['db_prefix']."_compare_txt");
define("_DB_CONTESTS",$eden_cfg['db_prefix']."_contests");
define("_DB_COUNTRIES",$eden_cfg['db_prefix_join']."_country");
define("_DB_CUPS_BRACKETS",$eden_cfg['db_prefix']."_cups_bracket");
define("_DB_DICTIONARY",$eden_cfg['db_prefix']."_dictionary");
define("_DB_DOWNLOADS",$eden_cfg['db_prefix']."_download");
define("_DB_DOWNLOADS_CATEGORIES",$eden_cfg['db_prefix']."_download_category");
define("_DB_EDEN_LOG",$eden_cfg['db_prefix']."_log");
define("_DB_FILTERS",$eden_cfg['db_prefix']."_filters");
define("_DB_FORUM_POSTS",$eden_cfg['db_prefix']."_forum_posts");
define("_DB_FORUM_POSTS_LOG",$eden_cfg['db_prefix']."_forum_posts_log");
define("_DB_FORUM_POSTS_EDIT_LOG",$eden_cfg['db_prefix']."_forum_posts_edit_log");
define("_DB_FORUM_POSTS_REPORT_LOG",$eden_cfg['db_prefix']."_forum_posts_report_log");
define("_DB_FORUM_PM",$eden_cfg['db_prefix']."_forum_pm");
define("_DB_FORUM_PM_LOG",$eden_cfg['db_prefix']."_forum_pm_log");
define("_DB_FORUM_TOPICS",$eden_cfg['db_prefix']."_forum_topic");
define("_DB_GROUPS",$eden_cfg['db_prefix_join']."_groups");
define("_DB_GUESTBOOKS",$eden_cfg['db_prefix']."_guestbook");
define("_DB_GUESTBOOKS_ADMINS",$eden_cfg['db_prefix']."_guestbook_admin");
define("_DB_GUESTBOOKS_TOPICS",$eden_cfg['db_prefix']."_guestbook_topic");
define("_DB_IP_TO_COUNTRY",$eden_cfg['db_prefix_join']."_ip_to_country");
define("_DB_LANGUAGES",$eden_cfg['db_prefix_join']."_language");
define("_DB_LEAGUE_AWARDS",$eden_cfg['db_prefix']."_league_awards");
define("_DB_LEAGUE_DRAFTS",$eden_cfg['db_prefix']."_league_draft");
define("_DB_LEAGUE_GUIDS",$eden_cfg['db_prefix']."_league_guids");
define("_DB_LEAGUE_LEAGUES",$eden_cfg['db_prefix']."_league_leagues");
define("_DB_LEAGUE_LOG",$eden_cfg['db_prefix']."_league_log");
define("_DB_LEAGUE_PLAYERS",$eden_cfg['db_prefix']."_league_players");
define("_DB_LEAGUE_PLAYERS_BANS",$eden_cfg['db_prefix']."_league_players_bans");
define("_DB_LEAGUE_PLAYERS_LEAGUES",$eden_cfg['db_prefix']."_league_players_leagues");
define("_DB_LEAGUE_REQUESTS",$eden_cfg['db_prefix']."_league_requests");
define("_DB_LEAGUE_SEASONS",$eden_cfg['db_prefix']."_league_seasons");
define("_DB_LEAGUE_SEASONS_RESULTS_PLAYERS",$eden_cfg['db_prefix']."_league_seasons_results_players");
define("_DB_LEAGUE_SEASONS_RESULTS_TEAMS",$eden_cfg['db_prefix']."_league_seasons_results_teams");
define("_DB_LEAGUE_SEASONS_ROUNDS)ALLOWED_PLAYERS",$eden_cfg['db_prefix']."_league_seasons_round_allowed_players");
define("_DB_LEAGUE_SEASONS_ROUNDS",$eden_cfg['db_prefix']."_league_seasons_rounds");
define("_DB_LEAGUE_SEASONS_ROUNDS_RESULTS_PLAYERS",$eden_cfg['db_prefix']."_league_seasons_rounds_results_players");
define("_DB_LEAGUE_SEASONS_ROUNDS_RESULTS_TEAMS",$eden_cfg['db_prefix']."_league_seasons_rounds_results_teams");
define("_DB_LEAGUE_TEAMS",$eden_cfg['db_prefix']."_league_teams");
define("_DB_LEAGUE_TEAMS_SUB",$eden_cfg['db_prefix']."_league_teams_sub");
define("_DB_LEAGUE_TEAMS_SUB_LEAGUES",$eden_cfg['db_prefix']."_league_teams_sub_leagues");
define("_DB_LINKS",$eden_cfg['db_prefix']."_links");
define("_DB_MTG_CARDS",$eden_cfg['db_prefix']."_mtg_cards");
define("_DB_MTG_DECKLISTS",$eden_cfg['db_prefix']."_mtg_decklists");
define("_DB_MTG_DECKLISTS_CARDS",$eden_cfg['db_prefix']."_mtg_decklists_cards");
define("_DB_PODCASTS",$eden_cfg['db_prefix']."_podcast");
define("_DB_PODCASTS_CHANNELS",$eden_cfg['db_prefix']."_podcast_channel");
define("_DB_POKER_CARDROOMS",$eden_cfg['db_prefix']."_poker_cardrooms");
define("_DB_POKER_HANDS",$eden_cfg['db_prefix']."_poker_hands");
define("_DB_POKER_VARIANTS",$eden_cfg['db_prefix']."_poker_variants");
define("_DB_POLL_ANSWERS",$eden_cfg['db_prefix']."_poll_answers");
define("_DB_POLL_QUESTIONS",$eden_cfg['db_prefix']."_poll_questions");
define("_DB_PROFILES",$eden_cfg['db_prefix']."_profiles");
define("_DB_RESERVED_WORDS",$eden_cfg['db_prefix_join']."_reserved_words");
define("_DB_RSS",$eden_cfg['db_prefix']."_rss");
define("_DB_RSS_LANG",$eden_cfg['db_prefix']."_rss_lang");
define("_DB_SESSIONS",$eden_cfg['db_prefix']."_sessions");
define("_DB_SETUP",$eden_cfg['db_prefix']."_setup");
define("_DB_SETUP_IMAGES",$eden_cfg['db_prefix']."_setup_images");
define("_DB_SETUP_LANG",$eden_cfg['db_prefix']."_setup_lang");
define("_DB_SHOP_BASKETS",$eden_cfg['db_prefix']."_shop_basket");
define("_DB_SHOP_CARRIAGES",$eden_cfg['db_prefix_join']."_shop_carriage");
define("_DB_SHOP_CARRIAGES_CATEGORIES",$eden_cfg['db_prefix_join']."_shop_carriage_category");
define("_DB_SHOP_CLOTHES_COLORS",$eden_cfg['db_prefix_join']."_shop_clothes_colors");
define("_DB_SHOP_CLOTHES_DESIGNS",$eden_cfg['db_prefix']."_shop_clothes_design");
define("_DB_SHOP_CLOTHES_SIZES",$eden_cfg['db_prefix_join']."_shop_clothes_size");
define("_DB_SHOP_CLOTHES_STYLES",$eden_cfg['db_prefix_join']."_shop_clothes_style");
define("_DB_SHOP_CLOTHES_STYLES_PARENTS",$eden_cfg['db_prefix_join']."_shop_clothes_style_parents");
define("_DB_SHOP_CURRENCIES",$eden_cfg['db_prefix_join']."_shop_currency");
define("_DB_SHOP_DISCOUNTS_CATEGORIES",$eden_cfg['db_prefix_join']."_shop_discount_categories");
define("_DB_SHOP_GENDERS",$eden_cfg['db_prefix_join']."_shop_gender");
define("_DB_SHOP_MANUFACTURERS",$eden_cfg['db_prefix_join']."_shop_manufacturers");
define("_DB_SHOP_ORDERS",$eden_cfg['db_prefix']."_shop_orders");
define("_DB_SHOP_ORDERS_LOG",$eden_cfg['db_prefix']."_shop_orders_log");
define("_DB_SHOP_ORDERS_PRODUCTS",$eden_cfg['db_prefix']."_shop_orders_product");
define("_DB_SHOP_PAYMENTS_METHODS",$eden_cfg['db_prefix_join']."_shop_payment_methods");
define("_DB_SHOP_PICTURES",$eden_cfg['db_prefix']."_shop_pictures");
define("_DB_SHOP_PRODUCTS",$eden_cfg['db_prefix']."_shop_product");
define("_DB_SHOP_PRODUCTS_CHANGES",$eden_cfg['db_prefix']."_shop_product_changes");
define("_DB_SHOP_PRODUCTS_CLOTHES",$eden_cfg['db_prefix']."_shop_product_clothes");
define("_DB_SHOP_SELLERS",$eden_cfg['db_prefix']."_shop_sellers");
define("_DB_SHOP_SETUP",$eden_cfg['db_prefix']."_shop_setup");
define("_DB_SHOP_TAX_CLASSES",$eden_cfg['db_prefix_join']."_shop_tax_class");
define("_DB_SHOP_TAX_RATES",$eden_cfg['db_prefix_join']."_shop_tax_rates");
define("_DB_SHOP_TAX_ZONES",$eden_cfg['db_prefix_join']."_shop_zones");
define("_DB_SMILES",$eden_cfg['db_prefix']."_smiles");
define("_DB_STREAMS",$eden_cfg['db_prefix']."_streams");
define("_DB_THUMBS",$eden_cfg['db_prefix']."_thumbs");
define("_DB_TAGS",$eden_cfg['db_prefix']."_tags");
define("_DB_TODO",$eden_cfg['db_prefix']."_todo");
define("_DB_TODO_CATEGORIES",$eden_cfg['db_prefix']."_todo_category");
define("_DB_TOURNAMENTS",$eden_cfg['db_prefix']."_tournaments");
define("_DB_VIDEOS",$eden_cfg['db_prefix']."_videos");

