<?php
$_GET['action'] = AGet($_GET,'action');
echo "<script type=\"text/javascript\">\n";
echo "<!--\n";
if ($_GET['action'] == "reg" || $_GET['action'] == "reg_scr"){
echo "function CheckRegistration(formular,nick) {";
echo "	re = new RegExp(\"^[^@\\.]([\\.]?[^@\\.]+)*@([^@\\.]+[\\.]{1}[^@\\.]+)+\$\");";
echo "	if (formular.admin_username.value == \"\"){";
echo "		alert (\""._ERR_REG_EMPTY_USERNAME."\");";
echo "		return false;";
echo "	} else if (formular.admin_nick.value == \"\" && nick == 1){";
echo "		alert (\""._ERR_REG_EMPTY_NICK."\");";
echo "		return false;";
echo "	} else if (formular.admin_password1.value == \"\"){";
echo "		alert (\""._ERR_REG_EMPTY_PASS."\");";
echo "		return false;";
echo "	} else if (formular.admin_password1.value.length <= 3){";
echo "		alert (\""._ERR_REG_SHORT_PASS."\");";
echo "		return false;";
echo "	} else if (formular.admin_password1.value !== formular.admin_password2.value){";
echo "		alert (\""._ERR_REG_BADPASS."\");";
echo "		return false;";
echo "	} else if (formular.admin_firstname.value == \"\"){";
echo "		alert (\""._ERR_REG_EMPTY_FIRSTNAME."\");";
echo "		return false;";
echo "	} else if (formular.admin_name.value == \"\"){";
echo "		alert (\""._ERR_REG_EMPTY_NAME."\");";
echo "		return false;";
echo "	} else if (formular.admin_email.value == \"\"){";
echo "		alert (\""._ERR_REG_EMPTY_EMAIL."\");";
echo "		return false;";
echo "	} else if (!re.test(formular.admin_email.value)){";
echo "		alert (\""._ERR_REG_BAD_EMAIL."\");";
echo "		return false;";
echo "	} else if (!re.test(formular.admin_email_repeat.value)){";
echo "		alert (\""._ERR_REG_BAD_EMAIL."\");";
echo "		return false;";
echo "	} else if (formular.admin_email.value !== admin_email_repeat.value){";
echo "		alert (\""._ERR_REG_BADPASS."\");";
echo "		return false;";
echo "	} else if (formular.admin_agreement.status == false){";
echo "		alert (\""._ERR_REG_DISAGREE_JS."\");";
echo "		return false;";
echo "	} else {";
echo "		return true;";
echo "	}";
echo "}";
}

echo "function CheckPoll(formular) {";
echo "	var radioOk = 0;";
echo "	for(i=0, n=document.eden_poll.eden_poll_vote.length; i < n; i++) {";
echo "		if(document.eden_poll.eden_poll_vote[i].checked) radioOk = 1;";
echo "	}";
echo "	if(!radioOk) {";
echo "		alert(\""._ERR_POLL_EMPTY_OPTION."\");";
echo "		return false;";
echo "	} else {";
echo "		return true;";
echo "	}";
echo "}\n";
echo "//-->\n";
echo "</script>";