<?php
define("_ADD_COMMENTS","Přidat komentář");
define("_ADD_LINK","Přidat odkaz");
define("_ADD_LINK_HELP","Odkaz se objeví v seznamu až po schválení administrátorem. Podmínkou schválnení je umístění našeho loga či banneru s odkazem na hlavní straně vašem webu.");
define("_BADLOGIN","Špatné jméno nebo heslo.");
define("_CL_TOPICS","Kapitoly článku");
define("_CLOSE","Zavřít");
define("_COM_COM","Komentářů:");
define("_COM_COM_NEW","nových:");
define("_COM_COM_VIEWS","přečteno:");
define("_COM_SHOW_OR_ADD","Přidat či zobrazit komentář");
define("_COM_SUBMIT","Zobrazit komentáře");
define("_COMMENTS","Komentář k zápasu");
define("_COMMENTS_DOWNLOAD","Komentářů");
define("_COMMENTS_POLL","Komentářů k anketě");
define("_CONTACT","Kontakt");
define("_COUNTER","Počítadlo přístupů");
define("_CTVRTEK","Čtvrtek");
define("_CUPS_CUPS_RESULTS","Výsledky turnajů");
define("_CUPS_ARTICLES","Novinky");
define("_CUPS_RULES","Pravidla");
define("_CW_INFO","Info o zápase");
define("_DATUM","Datum");
define("_DEMA","Dema");
define("_DESCRIPTION","Popis");
define("_DICTIONARY","Slovník");
define("_DICTIONARY_WORD","Výraz");
define("_DISC","Diskuze k článku");
define("_DISKHITS","Příspěvků v diskuzi");
define("_DL_CLOSE","Zavřít");
define("_DL_OPEN","Otevřít");
define("_DOWNLOAD_FILES_NUMBER","Souborů: ");
define("_EMAIL","Email");
define("_ENEMY_INFO","Info o soupeři");
define("_ERROR","Chyba: ");
define("_ERROR_DB","Chyba spojení s databází");
define("_FULL_ARTICLE","Celý článek");
define("_GAME_SERVERS","Herní servery");
define("_GAMETYPE","Typ hry");
define("_GUEST_ADD_LINK","Vložit odkaz");
define("_GUEST_COMMENTS","Komentář:");
define("_GUEST_DATE","Datum:");
define("_GUEST_EMAIL","Email:");
define("_GUEST_NAME","Jméno:");
define("_GUEST_PREDMET","Předmět:");
define("_IMAGE","Obrázek");
define("_INFO","Detaily");
define("_LAST_DOWNLOAD","Poslední download");
define("_LAST_UPDATE"," Poslední aktualizace:");
define("_LATEST_WARS","Poslední zápasy");
define("_LIGA","Liga");
define("_LINK","Odkaz");
define("_LOGIN","Přihlásit");
define("_LOGIN_FORGOTTEN_PASS","Zapomněli jste heslo?");
define("_LOGIN_FORGOTTEN_PASS_HINT","Pro zjištení vašich prihlašovacích informací zadejte váš login a emailovou adresu, na kterou jste se registrovali. Login a nové heslo vám budou zaslány emailem.");
define("_LOGOUT","Odhlásit");
define("_MAPS","Mapy");
define("_MUST_LOGIN","Pro přidávání či hodnocení komentářů musíte být přihlášeni.");
define("_NAZEV","Název");
define("_NEDELE","Neděle");
define("_NEW_MEMBERS","Noví členové");
define("_NEW_USERS","Noví uživatelé");
define("_ARTICLES_ARCHIVE","ARCHIV NOVINEK");
define("_ARTICLES_SOURCE","Zdroj");
define("_NO","Ne");
define("_NOLOGIN","Nepřihlášen");
define("_NONEDIT","Nedefinovano");
define("_NUM_DOWNLOAD","Stáhnuto");
define("_ONLY_FOR_USERS","<h2 style='color: #ff0000;'>OMEZENÁ ZÓNA!</h2>Pro zobrazení této stránky musíte být přihlášeni. <br><br>Jestliže doposud nemáte svůj účet, zaregistrujte se prosím.<br><br>  ");
define("_OVERALL","Celkem: ");
define("_PAR_NAME","Název");
define("_PASSWORD","Heslo");
define("_PASSWORD2","Zopakujte heslo");
define("_PASSWORD_OLD","Staré heslo");
define("_PATEK","Pátek");
define("_PM","Privátní zprávy");
define("_PM_ADD_TO_FRIENDS","Přidat k přátelům");
define("_PM_DEL_MARKED","Vymaž označené");
define("_PM_CHOOSE_REC","Vyberte příjemce");
define("_PM_SEND_NEWS","Odešli/Aktualizuj");
define("_PM_USER_DETAILS","Detaily");
define("_PONDELI","Pondělí");
define("_REG","Registrovat");
define("_REG_ADMIN","Uživatel má současně i administrátoreké práva, všechny změny lze prováděn jen pomocí redakčního systému <a href='http://eden.blackfoot.cz' target='_SELF'>EDEN</a>");
define("_REG_INFO","Vaše registrační info:");
define("_REG_INTRO","");
define("_REG_OK","Registrace proběhla v pořádku.");
define("_REG_PASS","Heslo:");
define("_REG_THX","Děkujeme za registraci.");
define("_REG_USERNAME","Uživatelské jméno:");
define("_SCORE","Výsledek");
define("_SCREENY","Screenshoty");
define("_SCRIPT_TIME","Stránka byla vygenerována za: ");
define("_SEARCH","Vyhledávání");
define("_SEARCH_ADVANCE","Pokročilé hledání");
define("_SEARCH_CHOICE_ACT","Aktuality");
define("_SEARCH_CHOICE_ARTICLES","Novinky & Články");
define("_SEARCH_CHOICE_WHERE","Vyhledat v:");
define("_SEARCH_PODMINKA_1","Všechna slova");
define("_SEARCH_PODMINKA_2","Alespoň jedno slovo");
define("_SEARCH_PODMINKA_3","Přesný výraz");
define("_SEARCH_SEARCH","Vyhledat");
define("_SEARCH_SEARCHED_RECORD","záznamů");
define("_SEARCH_SEARCHED_WAS","Bylo nalezeno:");
define("_SEARCH_SEARCHED_WORD","Hledaný výraz:");
define("_SERVERS","Servery");
define("_SESTAVA","Sestava");
define("_SHOW_ALL_ARTICLES","Všechny články");
define("_SHOW_ALL_COLUMNS","Všechny sloupky");
define("_SOBOTA","Sobota");
define("_SPONSORS","Sponzoři");
define("_STREDA","Středa");
define("_TAG","Klan Tag");
define("_USER","Uživatel");
define("_USERS","Uživatelů");
define("_USER_CLANIRC","IRC klanu");
define("_USER_CLANNAME","Název klanu");
define("_USER_CLANTAG","Klantag");
define("_USER_CLANWWW","Klanové www");
define("_USER_DEL_FRIENDS","Odebrat z přátel");
define("_USER_EDIT","Upravit profil");
define("_USER_FRIENDS","Přátelé");
define("_USERNAME","Přihlašovací jméno");
define("_USERS_COMMENTS","Komentáře návštěvníků");
define("_UTERY","Úterý");
define("_WEB_AUTORA","URL");
define("_WHO_IS_ONLINE","Kdo je online");
define("_WWW","Homepage");
define("_YES","Ano");
/***************************************************************************************************************
*
*		COMMON
*
***************************************************************************************************************/
define("_CMN_BYTES","Bajtů");
define("_CMN_CANCEL","Storno");
define("_CMN_COLOUR","Barva");
define("_CMN_COLOURS","Barvy");
define("_CMN_CONTACT_FORM_COMMENT","Komentář:");
define("_CMN_CONTACT_FORM_EMAIL","Email:");
define("_CMN_CONTACT_FORM_NAME","Jméno:");
define("_CMN_CONTACT_FORM_SEND","Odeslat komentář");
define("_CMN_CLOSE","Zavřít");
define("_CMN_DATE","Datum");
define("_CMN_DEL","Odstranit");
define("_CMN_DESIGN","Design");
define("_CMN_DETAILS","Detaily");
define("_CMN_EDIT","Editovat");
define("_CMN_GAME","Hra");
define("_CMN_NAME","Název");
define("_CMN_NEXT","Starší");
define("_CMN_NO","Ne");
define("_CMN_ONLINE","Online");
define("_CMN_ONTOP","Nahoru");
define("_CMN_OPTIONS","Možnosti");
define("_CMN_PM_SEND_PM","Napsat soukromou zprávu");
define("_CMN_PREVIOUS","Novější");
define("_CMN_PRICE","Cena");
define("_CMN_QUANTITY","Množství");
define("_CMN_SIZE","Velikost");
define("_CMN_SIZES","Velikosti");
define("_CMN_STYLE","Styl");
define("_CMN_STYLES","Styly");
define("_CMN_SUBMIT","Odeslat");
define("_CMN_SUBMIT_REG","Registrovat");
define("_CMN_SUBMIT_SEARCH","Hledat");
define("_CMN_WEIGHT","Váha");
define("_CMN_YES","Ano");
//**************************************************************************************************************
//
//		NEWS
//
//**************************************************************************************************************
define("_NEWS_SOURCE","Zdroj");
/***************************************************************************************************************
*
*		ADMINS
*
***************************************************************************************************************/
define("_ADMIN_ADMINS","- Administrátoři");
define("_ADMIN_AGE","Věk");
define("_ADMIN_AGREE_EMAIL","Přeji si dostávat komerční sdělení");
define("_ADMIN_AGREEMENT","Souhlasím s výše uvedenými podmínkami a pravidly");
define("_ADMIN_AOL","AOL");
define("_ADMIN_AUTOLOGIN","Zapamatovat si mě na tomto počítači");
define("_ADMIN_AVATAR","Avatar");
define("_ADMIN_AVATAR_MIN_SIZE","Minimální rozměr");
define("_ADMIN_AVATAR_MAX_SIZE","Maximální rozměr");
define("_ADMIN_AVATAR_MAX_FILESIZE","Maximální velikost souboru");
define("_ADMIN_AVATAR_SIZE","Rozměr");
define("_ADMIN_AVATAR_SUPPORTED_IMAGETYPE","Podporované typy obrázků: <strong>gif</strong>, <strong>jpg</strong>, <strong>png</strong>");
define("_ADMIN_BIRTH_DAY","Datum narození");
define("_ADMIN_CLAN_IRC","Klanové irc");
define("_ADMIN_CLAN_WWW","Klanové www");
define("_ADMIN_CLANNAME","Clanname");
define("_ADMIN_CLANTAG","Clantag");
define("_ADMIN_CONTACT_ADDRESS","Adresa");
define("_ADMIN_CONTACT_CITY","Město");
define("_ADMIN_CONTACT_COMPANYNAME","Název společnosti");
define("_ADMIN_CONTACT_COUNTRY","Země");
define("_ADMIN_CONTACT_POSTCODE","PSČ");
define("_ADMIN_EDENSHOP_ERR_FILL_ALL","Vyplňte prosím všechny položky uvedené výše.");
define("_ADMIN_EMAIL","Email");
define("_ADMIN_EMAIL_CHANGE","Změnit email");
define("_ADMIN_EMAIL_CHANGE_HINT","Pro změnu emailu vyplňte prosím obě kolonky a z bezpečnostních důvodů také heslo k vašemu účtu. Po odeslání vám bude na novou adresu zaslán email s aktivačním kódem. Vaše nová emailová adresa bude změněna až po kliknutí na odkaz s tímto kódem. Před odesláním doporučujeme správně nastavit váš spam filtr aby byl výše uvedený email doručen.");
define("_ADMIN_EMAIL_NEW","Nový email");
define("_ADMIN_EMAIL_REPEAT","Email znovu");
define("_ADMIN_FAV_MAP","Oblíbená mapa");
define("_ADMIN_FAV_TEAM","Oblíbený team ve hře");
define("_ADMIN_FAV_WPN","Oblíbená zbraň");
define("_ADMIN_FILTERS","Filtry");
define("_ADMIN_FIRSTNAME","Jméno");
define("_ADMIN_GAME_M_ACCEL","Akcelerace myši");
define("_ADMIN_GAME_M_INVERT","Invert myši");
define("_ADMIN_GAME_M_SENS","Senzitivita myši");
define("_ADMIN_GAME_RESOLUTION","Rozlišení");
define("_ADMIN_GAME_RESOLUTION_SELECT","Vyberte prosím vaše herní rozlišení");
define("_ADMIN_GAMES_COD2_PBGUID","CoD 2 PBGUID");
define("_ADMIN_GENDER","Pohlaví");
define("_ADMIN_GENDER_F","Žena");
define("_ADMIN_GENDER_M","Muž");
define("_ADMIN_HINT_AUTOLOGIN","Pokud zatrhnete tento checkbox, systém vás bude automaticky přihlašovat dokud budete mít platná cookies prohlížeče.");
define("_ADMIN_HINT_EMAIL","Zadejte prosím svou emailovou adresu.");
define("_ADMIN_HINT_FIRSTNAME","Zadejte prosím své jméno.");
define("_ADMIN_HINT_NAME","Zadejte prosím své příjmení.");
define("_ADMIN_HINT_NICK","Zadejte prosím svůj nickname/přezdívku. Tato bude použita pokud budete přispívat do komentářů, fóra atd.");
define("_ADMIN_HINT_PASSWORD1","Zadejte prosím své heslo. Musí být dlouhé nejméně <strong>4</strong> znaky.");
define("_ADMIN_HINT_PASSWORD2","Zadejte prosím své heslo znova. Toto je ochrana proti překlepu.");
define("_ADMIN_HINT_PASSWORD_OLD","Z bezpečnostních důvodů prosím zadejte staré heslo.");
define("_ADMIN_HINT_USERNAME","Přihlašovací jméno slouží pouze k přihlašování. Snažte se ho tedy zachovat co nejjednodušší. Mezery budou nahrazeny znakem podtržítka.<br>Povelené znaky:<br><strong>0123456789<br>abcdefghijklmnopqrstuvwxyz<br>_-</strong>");
define("_ADMIN_HW_BRAND_PC","Značka PC");
define("_ADMIN_HW_CD","CD");
define("_ADMIN_HW_CONECTION","Připojení k internetu");
define("_ADMIN_HW_CPU","CPU");
define("_ADMIN_HW_GAMEPAD","Gamepad");
define("_ADMIN_HW_HDD","HDD");
define("_ADMIN_HW_HEADSET","Sluchátka");
define("_ADMIN_HW_KEY","Klávesnice");
define("_ADMIN_HW_MB","MB");
define("_ADMIN_HW_MONITOR","Monitor");
define("_ADMIN_HW_MOUSE","Myš");
define("_ADMIN_HW_MOUSEPAD","Podložka");
define("_ADMIN_HW_OS","Operační systém");
define("_ADMIN_HW_RAM","RAM");
define("_ADMIN_HW_REPRO","Reproduktory");
define("_ADMIN_HW_SOUNDCARD","Zvuková karta");
define("_ADMIN_HW_VGA","VGA");
define("_ADMIN_ID","ID");
define("_ADMIN_ICQ","ICQ");
define("_ADMIN_INFO_BASIC","Základní info");
define("_ADMIN_INFO_CLAN","Klanové info");
define("_ADMIN_INFO_CONTACT","Kontakt");
define("_ADMIN_INFO_CONTACT_SHOP","Dodací adresa");
define("_ADMIN_INFO_CONTACT_SHOP_HELP","(Jen pokud je rozdílná s kontaktní adresou)");
define("_ADMIN_INFO_FAV","Oblíbené");
define("_ADMIN_INFO_GAME","Nastavení hry");
define("_ADMIN_INFO_HW","Hardware a Software");
define("_ADMIN_INFO_POKER","Poker");
define("_ADMIN_LANG","Jazyk na stránkách");
define("_ADMIN_MOBIL","Mobil");
define("_ADMIN_MSN","MSN");
define("_ADMIN_NAME","Příjmení");
define("_ADMIN_NAME_CHANGE","Změnit jméno");
define("_ADMIN_NICK","Nick");
define("_ADMIN_NOT_REGISTERED","Nereg.");
define("_ADMIN_OTHER_SETTINGS","Další nastavení");
define("_ADMIN_PLAYER_STATUS","Pozice v klanu");
define("_ADMIN_POKER_FAV_CARDROOM","Oblíbená pokerová herna");
define("_ADMIN_POKER_FAV_CARDROOM_SELECT","Vyberte prosím vaší oblíbenou pokerovou hernu");
define("_ADMIN_POKER_FAV_CARDROOMS","Oblíbené pokerové herny");
define("_ADMIN_POKER_FAV_PLAYER","Oblíbený pokerový hráč");
define("_ADMIN_POKER_FAV_VARIANTS","Oblíbené varianty");
define("_ADMIN_POKER_FAV_VARIANTS_SELECT","Vyberte prosím vaší oblíbenou variantu pokeru");
define("_ADMIN_REGISTERED","Registrovaný uživatel");
define("_ADMIN_SHOW_ADMINS","Zobrazit administrátory");
define("_ADMIN_SHOW_USERS","Zobrazit uživatele");
define("_ADMIN_SIGNATURE","<strong>Podpis</strong><br>Maximálně 250 znaků");
define("_ADMIN_SKYPE","Skype");
define("_ADMIN_STATUS","Status");
define("_ADMIN_STATUS_ADMIN","Admin");
define("_ADMIN_STATUS_USER","Uživatel");
define("_ADMIN_STREET","Ulice");
define("_ADMIN_TELEFON","Telefon");
define("_ADMIN_TITLE","Titul");
define("_ADMIN_TITLE_SELECT","Prosím vyberte titul");
define("_ADMIN_USERINFO","Info");
define("_ADMIN_USERS","- Uživatelé");
define("_ADMIN_WEB","Oblíbený web");
define("_ADMIN_XFIRE","X-Fire");
/***************************************************************************************************************
*
*		ARTICLES
*
***************************************************************************************************************/
define("_ARTICLE","Článek");
define("_ARTICLES","Články");
define("_ARTICLES_VIEW_CHANNEL","Zobrazit kanál");
/***************************************************************************************************************
*
*		BUTTONS
*
***************************************************************************************************************/
define("_BUTTON_CANCEL","Storno");
define("_BUTTON_SEND","Odeslat");
//**************************************************************************************************************
//
//		modul_calendar.php
//
//**************************************************************************************************************
define("_CALENDAR","Kalendář");
$cal_lang['months']		= array("Leden", "Únor", "Březen", "Duben", "Květen", "Červen", "Červenec", "Srpen", "Září", "Říjen", "Listopad", "Prosinec");
$cal_lang['days'] 		= array("Pondělí", "Úterý", "Středa", "Čtvrtek", "Pátek", "Sobota","Neděle");
$cal_lang['abrvdays'] 	= array("Po", "Út", "St", "Čt", "Pá", "So", "Ne");
define("_CALOTHERITEMS","Další záznamy pro tento den.");
define("_CALCHECKDELETE","Opravdu chcete tuto položku odstranit?");
define("_CALPOSTEDBY","Zapsal");
define("_CALEDIT","Editovat");
define("_CALDEL","Odstranit");
define("_CALSEARCH","Vyhledat");
define("_CALADDMSG","Kalendář - přidávání zpráv");
define("_CALACCESSDENIED","Nedostatek oprávnění. Nejsete přihášení.");
define("_CALSTART","Začátek:");
define("_CALEND","Konec:");
define("_CALEDITTITLE","Editace události");
define("_CALEDITEV","Editovat událost");
define("_CALEDITBUT","Aktualizovat");
define("_CALADDNEWTITLE","Přidání události");
define("_CALADDNEWEV","Přidat novou událost");
define("_CALADD","Odeslat");
define("_CALDATE","Datum:");
define("_CALCAT","Kategorie:");
define("_CALTITLE","Nadpis:");
define("_CALTEXT","Text:");
define("_CALCANCEL","Storno");
define("_CALTITLEMISSING","Chybí napdpis");
define("_CALACCESSWARNING","K vykonání nemáte dostatečná oprávnění");
define("_CALDELETE","Odstranit událost");
/***************************************************************************************************************
*
*		CAPTCHA
*
***************************************************************************************************************/
define("_CAPTCHA_S3_APPLE","jablko");
define("_CAPTCHA_S3_AND","a");
define("_CAPTCHA_S3_CHERRY","třešně");
define("_CAPTCHA_S3_LEMON","citrón");
define("_CAPTCHA_S3_PEAR","hrušku");
define("_CAPTCHA_S3_STRAWBERRY","jahodu");
define("_CAPTCHA_S3_VERIFY","Potvrďtě, že jste člověk, vyberte prosím");

/***************************************************************************************************************
*
*		CLAN AWARDS
*
***************************************************************************************************************/
define("_CLAN_AWARDS","Ocenění");
define("_CLAN_AWARDS_BUTTON_SHOW","Zobrazit ocenění");
define("_CLAN_AWARDS_FILTER_CHOSE_GAME","Všechny hry");
define("_CLAN_AWARDS_FILTER_CHOSE_PLACE","Všechna umístění");
define("_CLAN_AWARDS_FILTER_CHOSE_YEAR","Všechny roky");
define("_CLAN_AWARDS_OTHER","Další");
define("_CLAN_AWARDS_PLACE","místo");
define("_CLAN_AWARDS_PLACE_EXT_1",".");
define("_CLAN_AWARDS_PLACE_EXT_2",".");
define("_CLAN_AWARDS_PLACE_EXT_3",".");
define("_CLAN_AWARDS_PLACE_EXT_4",".");
/***************************************************************************************************************
*																												
*		COMMENTS																								
*																												
***************************************************************************************************************/
define("_COMM_COMMENTS","Komentáře");
define("_COMM_THUMBS_MUST_LOGIN","Pro hodnocení komentářů musíte být přihlášeni.");
define("_COMM_THUMBS_RATED_BEST","Nejlépe hodnocený komentář");
define("_COMM_THUMBS_RATED_WORST","Nejhůře hodnocený komentář");
define("_COMM_THUMBS_THUMB","Ohodnoťit tento komentář.");
define("_COMM_THUMBS_THUMBED","Tento komentář již byl vámi hodnocen.");
/***************************************************************************************************************
*
*		DICTIONARY
*
***************************************************************************************************************/
define("_DICT_ADD","Přidat");
define("_DICT_ADD_REV","Přidat revizi");
define("_DICT_ADD_WORD","Přidat výraz");
define("_DICT_SHOW_WORD","Zobrazit");
define("_DICT_TITLE_WORD","Výraz");
define("_DICT_TITLE_AUTHOR","Autor");
define("_DICT_TITLE_DATE","Datum");
define("_DICT_WORD","Výraz");
define("_DICT_WORD_DESC","Definice výrazu");
//**************************************************************************************************************
//
//		ERRORR MESSAGES
//
//**************************************************************************************************************
define("_EDEN_DB_ERROR","Došlo k chybě při zpracovani dotazu z databáze.");
/***************************************************************************************************************
*
*		ERRORS
*
***************************************************************************************************************/
define("_ERR_ADD_LINK_OK","Odkaz byl úspěšně přidán.");
define("_ERR_ALLREADY_USED","Odkaz už byl použit, musíte požádat o nové zaslání odkazu.");
define("_ERR_BAD_CAPTCHA","Captcha byla zadána chybně. Zadejte ji prosím správně.");
define("_ERR_BANNED","Na tomto serveru vám byl udělen ban");
define("_ERR_CONTACT_BAD_EMAIL","Chyba: Vaše emailová adresa je neplatná! Zadejte ji, prosím, správně.");
define("_ERR_CONTACT_EMPTY_COMMENT","Chyba: Nebyl zadán komentář.");
define("_ERR_CONTACT_EMPTY_EMAIL","Chyba: Nebyl zadán email.");
define("_ERR_CONTACT_EMPTY_NAME","Chyba: Nebylo zadáno vaše jméno.");
define("_ERR_CONTACT_FORM_MAIL_ER","Chyba: Kontaktní formulář nemohl být odeslán.");
define("_ERR_CONTACT_FORM_MAIL_OK","Kontaktní formulář byl v pořádku odeslán.");
define("_ERR_CUPS_REG_ER_MAIL","Chyba: Vaše registrace nebyla odeslána. Prosím kontaktujte webmastera.");
define("_ERR_CUPS_REG_OK_MAIL","Vaše registrace byla odeslána.");
define("_ERR_DECKLIST_ADD_ER","Chyba: Při ukládní vašeho decklistu došlo k chybě.");
define("_ERR_DECKLIST_ADD_ER_NO_FORMAT","Chyba: Vyberte prosím formát decklistu.");
define("_ERR_DECKLIST_ADD_ER_NO_NAME","Chyba: Zadejte prosím název decklistu.");
define("_ERR_DECKLIST_ADD_OK","Váš decklist byl v pořádku uložen.");
define("_ERR_DICT_ADD_OK","Výraz byl úspěšně přidán a byl zařazen ke schválení administrátorem.");
define("_ERR_DICT_WORD_EXIST","Daný výraz již v databázi existuje");
define("_ERR_EDEN_MISSING_REQUEST_ID","Chyba: Chybí ID požadavku");
define("_ERR_EDEN_MISSING_SUBTEAM_ID","Chyba: Chybí ID subtýmu");
define("_ERR_EDEN_MISSING_VARIABLES","Chyba: Chybějí potřebné proměnné");
define("_ERR_EDIT_OK","Editované položky byly úspěšně změněny");
define("_ERR_EMAIL_OPT_OUT_ER","Nepodařilo se vás odhlásit z emailové kampaně. Prosím kontaktujte webmastera.");
define("_ERR_EMAIL_OPT_OUT_OK","Byli jste úspěšně odhlášeni z emailové kapmpaně.");
define("_ERR_FORGPASS_BADUSR_MAIL","Login nebo email je nesprávný. V databázi se nenachází uživatel s těmito údaji. Prosím zkuste to znovu.");
define("_ERR_FORGPASS_ER_MAIL","Chyba: email nemohl být odeslán.");
define("_ERR_FORGPASS_OK_MAIL","Na zadanou emailovou adresu bylo odeslána zpáva s odkazem pro nouzové přihlášení. Prosím zkontrolujte si svůj email, klikněte v něm na odkaz a neprodleně si změňte vaše heslo.");
define("_ERR_FORM_SENT_ER","Chyba: Formulář nemohl být kvůli chybě odeslán");
define("_ERR_FORM_SENT_OK","Formulář byl v pořádku odeslán");
define("_ERR_FORUM_EDIT_WITHOUT_REASON","Chyba: Editovaný příspěvek nemá zadán důvod editace");
define("_ERR_FORUM_NO_PM_POST","Chyba: V odesílané zprávě nebyl napsán žádný text.");
define("_ERR_FORUM_NO_PM_REC","Chyba: Nebyl vybrán příjemce.");
define("_ERR_FORUM_NO_TOPIC_NAME","Chyba: Nebyl zadán název tématu.");
define("_ERR_FORUM_REPORT_WITHOUT_REASON","Chyba: Nebyl zadán důvod oznámení");
define("_ERR_FTP_AV_IMG_BAD","Chyba: Soubor není obrázek");
define("_ERR_FTP_AV_FILESIZE_TOO_BIG;","Chyba: Velikost souboru je větší než je povoleno");
define("_ERR_FTP_AV_IMG_TOO_BIG","Chyba: Obrázek má větší rozměr než je povoleno");
define("_ERR_FTP_AV_IMG_TOO_SMALL","Chyba: Obrázek má menší rozměr než je povoleno");
define("_ERR_FTP_AV_IMG_WRONG_FILETYPE","Chyba: Soubor není obrázek povoleného typu");
define("_ERR_FTP_NO_CONNECTION","Chyba: Nepodařilo se připojit k FTP serveru");
define("_ERR_FTP_UPLOAD_ERROR","Chyba: Nepodařilo se nahrát soubor na server");
define("_ERR_HINTBOX_ERROR","Chyba: Stránka nevrátila validní hodnoty.<br>Kontaktujte prosím administrátora.");
define("_ERR_CHANGES_EMAIL_MAIL_ER","Na zadanou emailovou adresu se nepodařilo odeslat zprávu.");
define("_ERR_CHANGES_EMAIL_MAIL_OK","Na vámi zadanou novou emailovou adresu byl odeslán email s aktivačním kódem, po kliknutí na něj bude vaše nová emailová adresa aktivována.");
define("_ERR_CHANGES_EMAIL_OK","Vaše emailová adresa byla úspěšně změněna.");
define("_ERR_LEAGUE_DRAFT_DEL_ER","Chyba: Vybrané záznamy nebyly odstraněny z Draftu hráčů");
define("_ERR_LEAGUE_DRAFT_DEL_OK","Vybrané záznamy byly odstraněny z Draftu hráčů");
define("_ERR_LEAGUE_DRAFT_SEARCH_PLAYER_ERR","Chyba: Ukládání záznamu do Draftu hráčů selhalo.");
define("_ERR_LEAGUE_DRAFT_SEARCH_PLAYER_EXIST","Chyba: Pro tuto hru již záznam v Draftu hráčů máte.");
define("_ERR_LEAGUE_DRAFT_SEARCH_PLAYER_OK","Váš záznam do Draftu hráčů byl úspěšně uložen.");
define("_ERR_LEAGUE_DRAFT_SEARCH_TEAM_ERR","Chyba: Ukládání záznamu do Draftu hráčů selhalo.");
define("_ERR_LEAGUE_DRAFT_SEARCH_TEAM_EXIST","Chyba: Pro tento podtým již záznam v Draftu hráčů máte.");
define("_ERR_LEAGUE_DRAFT_SEARCH_TEAM_OK","Váš záznam v Draftu hráčů byl úspěšně uložen.");
define("_ERR_LEAGUE_GUID_ADD_OK","GUID byl úspěšně přidán.");
define("_ERR_LEAGUE_GUID_EDIT_OK","GUID byl úspěšně editován.");
define("_ERR_LEAGUE_GUID_EXIST","Pro tuto hru již máte GUID registrován.");
define("_ERR_LEAGUE_GUID_GUID_SHORT","Chyba: GUID je příliš krátký.");
define("_ERR_LEAGUE_GUID_NO_GUID","Chyba: Prosím zadejte GUID");
define("_ERR_LEAGUE_GUID_NO_REASON","Chyba: Prosím zadejte důvod ke změně GUIDu.");
define("_ERR_LEAGUE_GUID_REASON_SHORT","Chyba: Důvod pro změnu GUIDu je příliš krátký.");
define("_ERR_LEAGUE_HIBERNATE_ER","Chyba: Tým se nepodařilo hibernovat.");
define("_ERR_LEAGUE_HIBERNATE_OK","Tým byl úspěšně hibernován.");
define("_ERR_LEAGUE_HIBERNATE_PLAYERS_IN_TEAM","Chyba: V některém z podtýmů jsou pořád ještě hráči.");
define("_ERR_LEAGUE_IS_LOCKED","Litujeme, ale požadovaná akce momentálně nejde provést, z důvodu dočasného uzamčení ligy. Více prosím viz pravidla.");
define("_ERR_LEAGUE_NO_PRIVILEGE","Chyba: K této operaci nemáte dostatečná práva!");
define("_ERR_LEAGUE_PLAYER_ADD_ER_MAIL","Chyba: Nepodařilo se odeslat email s výzvou ke vstupu do týmu.");
define("_ERR_LEAGUE_PLAYER_ADD_OK_MAIL","Hráči byl úspěšně odeslán email s výzvou ke vstupu do týmu.");
define("_ERR_LEAGUE_PLAYER_INVITE_EXIST","Pozvánka pro tohoto hráče už byla odeslána a čeká se na odpověď");
define("_ERR_LEAGUE_PLAYER_KICKED","Hráč byl vyhozen z týmu.");
define("_ERR_LEAGUE_PLAYER_LEFT_LEAGUE","Úspěšně jste opustil/a ligu.");
define("_ERR_LEAGUE_PLAYER_LEFT_TEAM","Úspěšně jste opustil/a tým.");
define("_ERR_LEAGUE_PLAYER_MAKE_A","Byla udělena pozice asistenta");
define("_ERR_LEAGUE_PLAYER_MAKE_C","Byla předána pozice kapitána");
define("_ERR_LEAGUE_PLAYER_MAKE_O","Bylo předáno vlastnictví týmu");
define("_ERR_LEAGUE_PLAYER_MAKE_P","Byla udělena pozice hráče");
define("_ERR_LEAGUE_PLAYER_NON_EXIST","Hráč s tímto ID/emailem neexistue. Prosím zkuste ID nebo email zadat znovu.");
define("_ERR_LEAGUE_PLAYER_NOT_ENTERED","Nebyl zadáno hráčův ID nebo email. Prosím zkuste ID nebo email zadat znovu.");
define("_ERR_LEAGUE_PLAYER_REG_ALREADY","V teto lize již jste registrováni.");
define("_ERR_LEAGUE_PLAYER_REG_NO_AGREE","Nebyli jste registrováni do ligy, protože jste nesouhlasili s pravidly ligy.");
define("_ERR_LEAGUE_PLAYER_REG_TO_LEAGUE","Byli jste registrováni do ligy.");
define("_ERR_LEAGUE_TEAM_ADD_OK","Tým byl úspěšně přidán.");
define("_ERR_LEAGUE_TEAM_EDIT_OK","Tým byl úspěšně editován.");
define("_ERR_LEAGUE_TEAM_JOIN_REQUEST","Vaše přihláška do týmu byla v pořádku odeslána kapitánu týmu, který ji musí buďto potvrdit nebo zamítnout.");
define("_ERR_LEAGUE_TEAM_JOIN_REQUEST_EXIST","Chyba: Přihláška do tohoto týmu již byla odeslána.");
define("_ERR_LEAGUE_TEAM_JOIN_REQUEST_INTEAM","Chyba: V tomto týmu a dané hře jste již registrován/a");
define("_ERR_LEAGUE_TEAM_LEFT_PLAYERS_ALLOWED","Soupiska hráčů hrajících tuto ligu byla aktualizována");
define("_ERR_LEAGUE_TEAM_LEFT_LEAGUE","Váš tým úspěšně opustil ligu");
define("_ERR_LEAGUE_TEAM_NAME_EXIST","Chyba: Tým s tímto názvem již existuje.");
define("_ERR_LEAGUE_TEAM_NO_IMG","Chyba: Zadejte prosím obrázek týmu.");
define("_ERR_LEAGUE_TEAM_NO_NAME","Chyba: Zadejte prosím název týmu.");
define("_ERR_LEAGUE_TEAM_NO_PASS","Chyba: Zadejte prosím heslo pro přístup do týmu.");
define("_ERR_LEAGUE_TEAM_NO_PASS_SHORT","Chyba: Heslo je příliš krátké.");
define("_ERR_LEAGUE_TEAM_OWNER_HAVE_TEAM","Chyba: Již máte jeden tým registrován. Nemůžete být vlastník víc než jednoho týmu.");
define("_ERR_LEAGUE_TEAM_PLAYER_AGREED","Stal/a jste se členem nového týmu.");
define("_ERR_LEAGUE_TEAM_PLAYER_DISAGREED","Odmítl/a jste se stát členem nového týmu.");
define("_ERR_LEAGUE_TEAM_PLAYER_PLAY_SAME_GAME","Chyba: Již jste registrován(a) v jiném týmu hrající stejnou hru. Nemůžete být člen/členka víc než jednoho týmu v dané hře.");
define("_ERR_LEAGUE_TEAM_REACHED_MAX_PLAYERS","Chyba: Není možno vstoupit do tohoto podtýmu, protože již dosáhl maximální povolený počet hráčů. Prosím zkuste to později.");
define("_ERR_LEAGUE_TEAM_REG_ALREADY","Váš tým již je v teto lize registrován.");
define("_ERR_LEAGUE_TEAM_REG_NO_AGREE","Váš tým nebyl registrován do ligy, protože jste nesouhlasili s pravidly ligy.");
define("_ERR_LEAGUE_TEAM_REG_TO_LEAGUE","Váš tým byl úspěšně registrován do ligy");
define("_ERR_LEAGUE_TEAM_SUB_ADDED","Nový podtým byl úspěšně přidán.");
define("_ERR_LEAGUE_TEAM_TEAM_AGREED","Povolil jste vstup hráče do týmu.");
define("_ERR_LEAGUE_TEAM_TEAM_DISAGREED","Odmítl/a jste hráči vstup do týmu.");
define("_ERR_LINKS_NO_DESC","Chyba: Zadejte prosím popis odkazu.");
define("_ERR_LINKS_NO_IMG","Chyba: Zadejte prosím obrázek odkazu.");
define("_ERR_LINKS_NO_LINK","Chyba: Zadejte prosím odkaz.");
define("_ERR_LINKS_NO_NAME","Chyba: Zadejte prosím název odkazu.");
define("_ERR_POLL_EMPTY_OPTION","Prosím vyberte nějakou volbu!");
define("_ERR_POLL_OK","Hlasování proběhlo úspěšně");
define("_ERR_POLL_VOTED","Z vaší IP adresy již bylo hlasováno");
define("_ERR_RECOMMEND_EMPTY_NAME","Chyba: Nebylo zadáno vaše jméno.");
define("_ERR_RECOMMEND_FROM_BAD_EMAIL","Chyba: Vaše emailová adresa je neplatná! Zadejte ji, prosím, správně.");
define("_ERR_RECOMMEND_FROM_EMPTY_EMAIL","Chyba: Zadejte prosím váš email.");
define("_ERR_RECOMMEND_TO_ACT_BAD_EMAIL","Chyba: Emailová adresa osoby které chcete aktualitu doporučit je neplatná! Zadejte ji, prosím, správně.");
define("_ERR_RECOMMEND_TO_ACT_EMPTY_EMAIL","Chyba: Zadejte prosím email osoby které chcete aktualitu doporučit.");
define("_ERR_RECOMMEND_TO_ARTICLES_BAD_EMAIL","Chyba: Emailová adresa osoby které chcete článek doporučit je neplatná! Zadejte ji, prosím, správně.");
define("_ERR_RECOMMEND_TO_ARTICLES_EMPTY_EMAIL","Chyba: Zadejte prosím email osoby které chcete článek doporučit.");
define("_ERR_RECOMMEND_TO_SHOP_BAD_EMAIL","Chyba: Emailová adresa osoby které chcete produkt doporučit je neplatná! Zadejte ji, prosím, správně.");
define("_ERR_RECOMMEND_TO_SHOP_EMPTY_EMAIL","Chyba: Zadejte prosím email osoby které chcete produkt doporučit.");
define("_ERR_REG_ALLOW_NO","Chyba: Váš účet nebyl aktivován. Kontaktujte prosím administrátora.");
define("_ERR_REG_ALLOW_OK","Váš účet byl aktivován.");
define("_ERR_REG_ALLOW_OK_ADMIN","Byla úspešne odeslána žádost o ruční aktivaci účtu adminem. Poté co admin potvrdí aktivaci vašeho účtu vám bude odeslán potvrzující email. Tento proces může trvat i několik hodin, děkujeme za pochopení.");
define("_ERR_REG_BAD_EMAIL","Chyba: Vaše emailová adresa je neplatná! Zadejte ji, prosím, správně.");
define("_ERR_REG_BAD_EMAILS","Chyba: Emaily si neodpovídají, zdejte je prosím znovu.");
define("_ERR_REG_BAD_OLD_PASS","Chyba: Staré heslo nebylo zadáno správně, zdejte jej prosím znovu.");
define("_ERR_REG_BADLOGIN","Špatný login nebo heslo");
define("_ERR_REG_BADPASS","Chyba: Hesla si neodpovídají, zdejte je prosím znovu.");
define("_ERR_REG_EDIT_OK","Editace proběhla úspěšně.");
define("_ERR_REG_EMAIL_IS_NOT_VALID","Email není v platném formátu - zadejte ho prosím znovu");
define("_ERR_REG_EMPTY_EMAIL","Chyba: Nebyl zadán email.");
define("_ERR_REG_EMPTY_FIRSTNAME","Chyba: Nebylo zadáno vaše jméno.");
define("_ERR_REG_EMPTY_NAME","Chyba: Nebylo zadáno vaše příjmení.");
define("_ERR_REG_EMPTY_NICK","Chyba: Nebyl zadán váš nickname.");
define("_ERR_REG_EMPTY_PASS","Chyba: Nebylo zadáno vaše heslo.");
define("_ERR_REG_EMPTY_USERNAME","Chyba: Nebylo zadáno přihlašovací jméno.");
define("_ERR_REG_FILL_ALL_CELLS","Prosím vyplňte všechny kolonky níže.");
define("_ERR_REG_NOMATCH_EMAIL","Chyba: Zadané emailové adresy si neodpovídají.");
define("_ERR_REG_NONAME","Nebylo zadáno jméno.");
define("_ERR_REG_NOT_ALLOW","Účet nebyl dosud aktivován");
define("_ERR_REG_DISAGREE","Registrace nebyla dokončena jelikož nebyl potvrzen souhlas s pravidly.");
define("_ERR_REG_DISAGREE_JS","Pro úspěšnou registraci musíte souhlasit s pravidly.");
define("_ERR_REG_REG_ER","Registrace neproběhla úspěšně.");
define("_ERR_REG_REG_ER_MAIL","Chyba: Potvrzovací email nemohl být odeslán.");
define("_ERR_REG_REG_OK","Registrace proběhla úspěšně.");
define("_ERR_REG_REG_OK_MAIL","Registrace proběhla v pořádku. Na zadanou emailovou adresu by měl přijít odkaz, po kliknutí na něj bude účet aktivován");
define("_ERR_REG_REG_OK_MAIL_ADMIN","Registrace proběhla v pořádku. Na zadanou emailovou adresu by vám měl přijít odkaz. Tím, že na tento odkaz kliknete, se odešle žádost o ruční aktivaci účtu adminem. Poté co admin potvrdí aktivaci vašeho účtu vám bude odeslán potvrzující email. Tento proces může trvat i několik hodin, děkujeme za pochopení.");
define("_ERR_REG_REPLYEMAIL","Emailová adresa je již v systému registrována pro jiného uživatele.");
define("_ERR_REG_REPLYNAMES","Přihlašovací jméno je již v systému registrováno.");
define("_ERR_REG_REPLYNICK","Nick je již v systému registrován.");
define("_ERR_REG_REPLYSOMETHING","Při ukládání do databáze bylo zjištěno, že vámi zadané uživatelské jméno, Nick nebo email již v databázi existuje.");
define("_ERR_REG_SHORT_PASS","Chyba: Heslo je krátké. Prosím zadejte nejméně 4 znaky.");
define("_ERR_SELLER_ADD_ER","Chyba: Data nebyla uložena. Prosíme kontaktujte web administrátora.");
define("_ERR_SELLER_ADD_OK","Váš velkoobchodní účet byl úspěšně založen. Data které jste zadali budou prověřeny a váš účet aktivován. Ihned po aktivaci budete kontaktováni a pak můžete využít všechny výhody které velkoobchodní účet nabízí.");
define("_ERR_SELLER_BAD_EMAIL","Chyba: Vaše emailová adresa je neplatná! Zadejte ji, prosím, správně.");
define("_ERR_SELLER_EDIT_ER","Chyba: Změny nebyly uloženy. Prosíme kontaktujte web administrátora.");
define("_ERR_SELLER_EDIT_OK","Váš velkoobchodní účet byl úspěšně editován.");
define("_ERR_SELLER_EMPTY_NAME","Chyba: Nebylo zadáno jméno společnosti.");
define("_ERR_SELLER_EMPTY_POSITION","Chyba: Zadejte prosím vaší pozici ve společnosti.");
define("_ERR_SESSION_EXPIRED","Chyba: Vaše session vypršela. Prosím logněte se a zkuste akci znovu. Tomuto stavu předejdete zatrhnutím volby Zapamatovat uživatele ve vašem profilu");
define("_ERR_SHOP_ORDER_ER","Při odesílání došlo k chybě, prosím zkuste to znovu později, nebo kontaktujte webmastera.");
define("_ERR_SHOP_ORDER_OK","Vaše objednávka byla v pořádku odeslána.");
define("_ERR_TRY_AGAIN","Chyba: Prosím zkuste to znovu.");
define("_ERR_USERS_POLLS_24","Chyba: Lze přidat jen jednu anketu za 24 hodin");
define("_ERR_USERS_POLLS_DEL_OK","Anketa byla v pořádku odstranněna");
define("_ERR_USERS_POLLS_NOA","Chyba: Musíte zadat alespoň 2 odpovědi");
define("_ERR_USERS_POLLS_NOQ","Chyba: Musíte zadat otázku");
define("_ERR_USERS_POLLS_OK","Anketa byla v pořádku přidána");
define("_ERR_WEB_AGREEMENT_ER","Chyba: Při zápisu vašeho souhlasu s podmínkami a pravidly došlo k chybě.");
define("_ERR_WEB_AGREEMENT_OK","Váš souhlas s podmínkami a pravidly byl v pořádku zaznamenán.");
/***************************************************************************************************************
*
*		FORUM
*
***************************************************************************************************************/
define("_FORUM","Fórum");
define("_FORUM_ADD_COMM","Fórum - Přidání příspěvku");
define("_FORUM_ADD_HTOPIC","Přidání hlavní téma");
define("_FORUM_ADD_FORUM","Přidat fórum");
define("_FORUM_ADD_TOPIC","Přidat téma");
define("_FORUM_ADD_TO_FRIENDS","Přidat k přátelům");
define("_FORUM_ADMIN","Admin");
define("_FORUM_ADMIN_FOUND","Založen:");
define("_FORUM_ADMIN_POSTS","Příspěvků:");
define("_FORUM_ANONYMS","Anonymové");
define("_FORUM_AUD","Auditorií: ");
define("_FORUM_AUTHOR","Autor");
define("_FORUM_AUTOLOGIN","Autologin");
define("_FORUM_COMM","Komentář");
define("_FORUM_COMMENT","Komentář");
define("_FORUM_DATE","Datum");
define("_FORUM_DELETE","Mazat");
define("_FORUM_DEL_FORUM","Fórum - Odstranění fóra");
define("_FORUM_DELP","Odstranit označené");
define("_FORUM_DELPNUM","Odstranit od do");
define("_FORUM_DELPUSR","Odstranit vše od");
define("_FORUM_DEL_FROM_FRIENDS","Odebrat z přátel");
define("_FORUM_EDIT_FORUM","Editovat Fórum");
define("_FORUM_EDIT_TOPIC","Editovat téma");
define("_FORUM_EDIT_USER","Info");
define("_FORUM_FIRST_POST","První příspěvek");
define("_FORUM_FORUM_NAME","Název fóra");
define("_FORUM_FRIEND","Přítel");
define("_FORUM_FRIENDS","Přátelé");
define("_FORUM_GO_TO_PAGE","Jdi na stránku:");
define("_FORUM_HITS","Zobrazit příspěvků");
define("_FORUM_CHECKDELETE","Opravdu chcete tuto diskuzi odstranit?");
define("_FORUM_CHOSEIMAGE","Vyberte si obrázek");
define("_FORUM_CHOOSE_RECIPIENT","Vyberte příjemce");
define("_FORUM_IMG_HELP","Velikost obrázku: 50x40 bod?<br>Přípustné formáty: GIF, JPG, PNG");
define("_FORUM_LAST_POST","Poslední příspěvek");
define("_FORUM_LATEST_POST","Zobrazit poslední příspěvek");
define("_FORUM_MANAGE","Správa fór");
define("_FORUM_MCOMM","Komentář");
define("_FORUM_MODERATE","Moderuje: ");
define("_FORUM_MODERATE_P","Moderují: ");
define("_FORUM_NAME","Název fóra");
define("_FORUM_NEED_TO_LOGIN","Pro prohlížení fóra musíte být přilášeni.");
define("_FORUM_NEW_POSTS","Nových příspěvků");
define("_FORUM_NEW_TOPIC","Nové téma");
define("_FORUM_REPLY","Odpovědět");
define("_FORUM_OTHERUSERS","Ostatní");
define("_FORUM_PM","Soukromá Pošta");
define("_FORUM_POST","Příspěvek:");
define("_FORUM_POST_EDIT_REASON","Důvod editace:");
define("_FORUM_POST_EDIT_TITLE","Editovat tento příspěvek");
define("_FORUM_POST_EDITED_1","Naposledy upravil ");
define("_FORUM_POST_EDITED_2"," dne ");
define("_FORUM_POST_EDITED_3",", celkově upraveno ");
define("_FORUM_POST_EDITED_4"," krát");
define("_FORUM_POST_DEL_TITLE","Odstranit tento příspěvek");
define("_FORUM_POST_NEW","Nový příspěvek");
define("_FORUM_POST_OTHER_SETTINGS","Další nastavení:");
define("_FORUM_POST_OTHER_SETTINGS_ATTACH_SIG","Připojit podpis (podpis můžete změnit ve vašem profilu)");
define("_FORUM_POST_QUOTE_TITLE","Citovat tento příspěvek");
define("_FORUM_POST_QUOTE_WROTE"," napsal");
define("_FORUM_POST_REPORT_IT","Nahlásit");
define("_FORUM_POST_REPORT_IT_HELP","<strong>Důvod oznámení:</strong><br>Uveďte prosím stručně váš důvod, proč tento příspěvek oznamujete moderátorům (spam...)<br>\n<br>\nOdkaz, datum atd. bude doplněn automaticky");
define("_FORUM_POST_REPORT_IT_POST","<strong>Příspěvek k oznámaní:</strong>");
define("_FORUM_POST_REPORT_IT_TITLE","Oznámit tento příspěvek moderátorům");
define("_FORUM_POST_REPORTED","Příspěvek byl ohlášen");
define("_FORUM_POST_SUBJECT","Předmět:");
define("_FORUM_POSTED","Založeno");
define("_FORUM_POSTS","Příspěvků");
define("_FORUM_POSTS_ADD_DISALLOW","Přidávání příspěvků do tohoto tématu vám není povoleno");
define("_FORUM_POSTS_DEL","Odstranit");
define("_FORUM_POSTS_DEL_REASON","Důvod odstranění:");
define("_FORUM_POSTS_EDIT","Editovat");
define("_FORUM_POSTS_ORDER","<strong>Řazení příspěvků:</strong>");
define("_FORUM_POSTS_ORDER_ASC","Nejstarší nahoře");
define("_FORUM_POSTS_ORDER_DESC","Nejnovější nahoře");
define("_FORUM_POSTS_POSTED","Zasláno");
define("_FORUM_POSTS_QUOTE","Quote");
define("_FORUM_PREVOD","Převod práv tohoto tématu na jiného uživatele");
define("_FORUM_READ","Číst");
define("_FORUM_SEND","Odeslat");
define("_FORUM_SEND_PREVIEW","Zobrazit náhled");
define("_FORUM_SEND_SEND","Odeslat");
define("_FORUM_SETUP","Nastavení");
define("_FORUM_SHOW_NEWEST_POSTS","Zobrazit nejnovější příspěvky");
define("_FORUM_TOPICS","Témat");
define("_FORUM_TOPIC","Název tématu");
define("_FORUM_TOPIC_IMPORTANCE","Důležitost: ");
define("_FORUM_TOPIC_IMPORTANT","Důležité: ");
define("_FORUM_TOPIC_NAME","Název tématu");
define("_FORUM_HEAD_TOPICS","Hlavních Témat");
define("_FORUM_USEREDIT","Upravit detaily");
define("_FORUM_VIEWS","Zobrazní");
define("_FORUM_WRITE","Psát");
//**************************************************************************************************************
//
//		GAME SERVERS
//
//**************************************************************************************************************
define("_GAMESRV_COUNTRY","Země");
define("_GAMESRV_NAME","Název herního serveru");
define("_GAMESRV_IP","IP adresa");
define("_GAMESRV_MODE","Herní mód");
//**************************************************************************************************************
//
//		GUESTBOOK
//
//**************************************************************************************************************
define("_GUESTBOOK_FLAG_NO_SELECTED","Nebylo vybráno");
/***************************************************************************************************************
*																												
*		LEAGUE																									
*																												
***************************************************************************************************************/
define("_LEAGUE_AWARD_DATE","Datum");
define("_LEAGUE_AWARD_GAME","Hra");
define("_LEAGUE_AWARD_LEAGUE","Liga");
define("_LEAGUE_AWARD_PLACE","Umístění");
define("_LEAGUE_AWARD_SEASON","Sezóna");
define("_LEAGUE_BUTTON_UPDATE_TEAM","Aktualizovat tým");
define("_LEAGUE_DRAFT","Draft hráčů");
define("_LEAGUE_DRAFT_BUTTON_DEL","Odstranit vybrané příspěvky");
define("_LEAGUE_DRAFT_GAME","Hra");
define("_LEAGUE_DRAFT_CHOSE_GAME","Vyberte prosím hru, v které chcete hledat tým");
define("_LEAGUE_DRAFT_CHOSE_TEAM","Vyberte prosím podtým pro který chcete hledat hráče");
define("_LEAGUE_DRAFT_CHOSE_TEAM_PLAYERS","Kolik hráčů hledáte?");
define("_LEAGUE_DRAFT_MSG","Zpráva");
define("_LEAGUE_DRAFT_MSG_PLAYER","Hledám tým");
define("_LEAGUE_DRAFT_MSG_TEAM","Hledáme hráče");
define("_LEAGUE_DRAFT_NAME","Název/Nick");
define("_LEAGUE_DRAFT_PLAYER","Hráč");
define("_LEAGUE_DRAFT_PLAYER_LOOKING","Hráč hledá tým");
define("_LEAGUE_DRAFT_SEARCHING_TEAM","Hledám tým");
define("_LEAGUE_DRAFT_SEARCHING_PLAYERS","Hledáme hráče");
define("_LEAGUE_DRAFT_TEAM","Tým");
define("_LEAGUE_DRAFT_TEAM_LOOKING","Tým hledá hráče");
define("_LEAGUE_LEAGUE_LIST_GAME","Hra");
define("_LEAGUE_LEAGUE_LIST_ID","ID");
define("_LEAGUE_LEAGUE_LIST_MAX","Max. hráčů");
define("_LEAGUE_LEAGUE_LIST_MIN","Min. hráčů");
define("_LEAGUE_LEAGUE_LIST_MODE","Mód");
define("_LEAGUE_LEAGUE_LIST_MODE_PLAYER","Liga jednotlivců");
define("_LEAGUE_LEAGUE_LIST_MODE_TEAM","Týmová liga");
define("_LEAGUE_LEAGUE_LIST_NAME","Název ligy");
define("_LEAGUE_LEAGUE_LIST_NO_LIMIT","Bez omezení");
define("_LEAGUE_LEAGUE_LIST_RULES","Popis a pravidla ligy");
define("_LEAGUE_LOG_ACTION","Akce");
define("_LEAGUE_LOG_DATE","Datum");
define("_LEAGUE_LOG_NO_ACTION","Žádná akce");
define("_LEAGUE_LOG_NO_MODE","Nebyl vybrán správný mód funkce.");
define("_LEAGUE_LOG_NO_SUBJECT","Nebyl vybrán subjekt pro historii.");
define("_LEAGUE_LOG_PLAYER_ACC_BLOCKED","Účet zablokován");
define("_LEAGUE_LOG_PLAYER_ACC_CREATED","Založen účet ");
define("_LEAGUE_LOG_PLAYER_ADD_GUID","Přidán GUID - ");
define("_LEAGUE_LOG_PLAYER_ADD_PERSONALITY","Přidána personalita: ");
define("_LEAGUE_LOG_PLAYER_BANNED_FROM_LEAGUE","Hráč zabanobván v lize: ");
define("_LEAGUE_LOG_PLAYER_BECOME_ASSISTANT","Získána pozice asistenta v týmu: ");
define("_LEAGUE_LOG_PLAYER_BECOME_CAPTAIN","Získána pozice kapitána v týmu: ");
define("_LEAGUE_LOG_PLAYER_BECOME_OWNER","Získána pozice majitele týmu: ");
define("_LEAGUE_LOG_PLAYER_CHANGE_GUID","Změněn GUID z ");
define("_LEAGUE_LOG_PLAYER_CHANGE_GUID_2"," na ");
define("_LEAGUE_LOG_PLAYER_CHANGE_GUID_3","<br>Důvod: ");
define("_LEAGUE_LOG_PLAYER_CHANGE_NICK","Změněn nick z ");
define("_LEAGUE_LOG_PLAYER_CHANGE_NICK_2"," na ");
define("_LEAGUE_LOG_PLAYER_CHANGE_PERSONALITY","Změna personality z ");
define("_LEAGUE_LOG_PLAYER_CHANGE_PERSONALITY_2"," na ");
define("_LEAGUE_LOG_PLAYER_CHANGE_TEAM","Přestup z týmu ");
define("_LEAGUE_LOG_PLAYER_CHANGE_TEAM_2"," do ");
define("_LEAGUE_LOG_PLAYER_GAVE_POSITION_CAPTAIN_TO_1","Pozice kapitána týmu ");
define("_LEAGUE_LOG_PLAYER_GAVE_POSITION_CAPTAIN_TO_2"," předána hráči ");
define("_LEAGUE_LOG_PLAYER_JOIN_LEAGUE","Vstup do ligy: ");
define("_LEAGUE_LOG_PLAYER_JOIN_TEAM","Vstup do týmu: ");
define("_LEAGUE_LOG_PLAYER_KICKED_FROM_LEAGUE","Vyhozen z ligy: ");
define("_LEAGUE_LOG_PLAYER_KICKED_FROM_TEAM","Vyhozen z týmu: ");
define("_LEAGUE_LOG_PLAYER_LEFT_OWNERSHIP","Opuštění vlastnictví týmu: ");
define("_LEAGUE_LOG_PLAYER_LEFT_LEAGUE","Opuštění ligy: ");
define("_LEAGUE_LOG_PLAYER_LEFT_TEAM","Opuštění týmu: ");
define("_LEAGUE_LOG_PLAYER_REFUSE_JOIN_TEAM","Odmítnuta žádost o připojení k týmu: ");
define("_LEAGUE_LOG_PLAYER_TAKEN_POSITION_ASSISTANT","Odebrána pozice asistenta v týmu: ");
define("_LEAGUE_LOG_PLAYER_TAKEN_POSITION_CAPTAIN","Odebrána pozice kapitána v týmu: ");
define("_LEAGUE_LOG_PLAYER_UNBANNED_FROM_LEAGUE","Hráč byl odbanován v lize: ");
define("_LEAGUE_LOG_TEAM_ACCOUNT_BLOCKED","Týmový účet byl zablokován");
define("_LEAGUE_LOG_TEAM_ADD_GAME","Přidána hra: ");
define("_LEAGUE_LOG_TEAM_ASSISTANT_POSITION_WAS_TAKEN","Pozice asistenta byla odebrána hráči: ");
define("_LEAGUE_LOG_TEAM_CAPTAIN_POSITION_WAS_TAKEN","Pozice kapitána byla odebrána hráči: ");
define("_LEAGUE_LOG_TEAM_CHANGE_NAME","Tým ");
define("_LEAGUE_LOG_TEAM_CHANGE_NAME_2"," změnil jméno na ");
define("_LEAGUE_LOG_TEAM_CREATED","Založen tým ");
define("_LEAGUE_LOG_TEAM_HAS_BEEN_ACCEPTED_TO_LEAGUE","Týmu bylo uděleno povolení hrát v lize: ");
define("_LEAGUE_LOG_TEAM_HAS_BEEN_HIBERNATED","Tým byl hibernován");
define("_LEAGUE_LOG_TEAM_JOIN_LEAGUE","Vstup do ligy: ");
define("_LEAGUE_LOG_TEAM_KICKED_FROM_LEAGUE","Vyhození z ligy: ");
define("_LEAGUE_LOG_TEAM_KICKED_PLAYER","Vyhozen hráč: ");
define("_LEAGUE_LOG_TEAM_LEFT_LEAGUE","Odchod z ligy: ");
define("_LEAGUE_LOG_TEAM_NEW_ASSISTANT_BECOME","Novým asistentem v týmu se stal: ");
define("_LEAGUE_LOG_TEAM_NEW_CAPTAIN_BECOME","Novým kapitánem týmu se stal: ");
define("_LEAGUE_LOG_TEAM_NEW_OWNER_BECOME","Novým majitelem týmu se stal: ");
define("_LEAGUE_LOG_TEAM_OWNERSHIP_WAS_GIVEN_TO","Novým majitelem týmu se stal: ");
define("_LEAGUE_LOG_TEAM_PLAYER_CHANGED_NICK","Hráč ");
define("_LEAGUE_LOG_TEAM_PLAYER_CHANGED_NICK_2"," si změnil nick na ");
define("_LEAGUE_LOG_TEAM_REFUSED_ADD_PLAYER","Tým odmítnul přidat hráče: ");
define("_LEAGUE_LOG_TEAM_WAS_JOINED_BY_PLAYER","Do týmu vstoupil hráč: ");
define("_LEAGUE_LOG_TEAM_WAS_LEFT_BY_PLAYER","Z týmu vystoupil hráč: ");
define("_LEAGUE_PLAYER_ACC_PLAYER","Hráčský účet");
define("_LEAGUE_PLAYER_ACC_TEAMS","Týmové účty");
define("_LEAGUE_PLAYER_ADD_TEAM","Založit tým");
define("_LEAGUE_PLAYER_AWARDS","Získaná ocenění");
define("_LEAGUE_PLAYER_EDIT_TEAM","Editovat tým");
define("_LEAGUE_PLAYER_EMAIL","Email");
define("_LEAGUE_PLAYER_GAME","Hra");
define("_LEAGUE_PLAYER_GAMES","Hry");
if ($project == "PokerTeam"){
define("_LEAGUE_PLAYER_GUID","PokerStars ID");
define("_LEAGUE_PLAYER_GUID_CURRENT","Současný PokerStars ID");
define("_LEAGUE_PLAYER_GUID_CURRENT_EDIT","Váš současný PokerStars ID je: ");
define("_LEAGUE_PLAYER_GUID_CURRENT_TITLE","Současný PokerStars ID");
define("_LEAGUE_PLAYER_GUID_EDIT","Editovat PokerStars ID");
define("_LEAGUE_PLAYER_GUID_HELP","PokerStars ID je důležitý pro vaši identifikaci.");
define("_LEAGUE_PLAYER_GUID_NO","Hráč nemá registrován PokerStars ID");
define("_LEAGUE_PLAYER_GUID_NO_2","Není registrován PokerStars ID");
define("_LEAGUE_PLAYER_GUID_NO_GAME_TO_REG","Již máte registrován PokerStars ID.");
define("_LEAGUE_PLAYER_GUID_NOT_YET_1","Váš ");
define("_LEAGUE_PLAYER_GUID_NOT_YET_2"," není ještě registrován.");
define("_LEAGUE_PLAYER_GUID_REASON","Důvod pro změnu PokerStars ID");
define("_LEAGUE_PLAYER_GUID_REG","Registrovat");
define("_LEAGUE_PLAYER_GUID_REG_NEW","Registrovat nový PokerStars ID");
define("_LEAGUE_PLAYER_GUID_REG_SELECT","Vyberte typ PokerStars ID");
define("_LEAGUE_PLAYER_GUID_SAMPLE_1","Tady je ukázka jak by měl správný ");
define("_LEAGUE_PLAYER_GUID_SAMPLE_2"," vypadat:");
define("_LEAGUE_PLAYER_GUID_STATUS"," PokerStars ID status");
define("_LEAGUE_PLAYER_GUID_STATUS_YES"," PokerStars ID zadáno");
define("_LEAGUE_PLAYER_GUID_TYPE","Typ ID");
define("_LEAGUE_PLAYER_GUID_VALUE","Hodnota");
define("_LEAGUE_PLAYER_GUIDS","PokerStars ID");
define("_LEAGUE_TEAM_GUIDS","Týmové PokerStars ID");
define("_LEAGUE_TEAM_GUIDS_TEAM_WASNT_SELECTED","Nebyl vybrán tým.");
define("_LEAGUE_TEAM_GUIDS_PLAYERS_COUNTRY","Země");
define("_LEAGUE_TEAM_GUIDS_PLAYERS_GAME","Hra");
define("_LEAGUE_TEAM_GUIDS_PLAYERS_GUIDS","ID");
define("_LEAGUE_TEAM_GUIDS_PLAYERS_NICK","Nick");
} else {
define("_LEAGUE_PLAYER_GUID","Herní GUID/ID");
define("_LEAGUE_PLAYER_GUID_CURRENT","Současný GUID");
define("_LEAGUE_PLAYER_GUID_CURRENT_EDIT","Váš současný GUID je: ");
define("_LEAGUE_PLAYER_GUID_CURRENT_TITLE","Současné GUIDy");
define("_LEAGUE_PLAYER_GUID_EDIT","Editovat GUID");
define("_LEAGUE_PLAYER_GUID_HELP","Herní GUID/ID je důležitý pro vaši identifikaci.");
define("_LEAGUE_PLAYER_GUID_NO","Hráč nemá registrován GUID");
define("_LEAGUE_PLAYER_GUID_NO_2","Není registrován GUID");
define("_LEAGUE_PLAYER_GUID_NO_GAME_TO_REG","Již máte registrován GUID/ID pro všechny dostupné hry.");
define("_LEAGUE_PLAYER_GUID_NOT_YET_1","Váš ");
define("_LEAGUE_PLAYER_GUID_NOT_YET_2"," není ještě registrován.");
define("_LEAGUE_PLAYER_GUID_REASON","Důvod pro změnu GUIDu");
define("_LEAGUE_PLAYER_GUID_REG","Registrovat");
define("_LEAGUE_PLAYER_GUID_REG_NEW","Registrovat nový GUID");
define("_LEAGUE_PLAYER_GUID_REG_SELECT","Vyberte typ GUIDu");
define("_LEAGUE_PLAYER_GUID_SAMPLE_1","Tady je ukázka jak by měl správný ");
define("_LEAGUE_PLAYER_GUID_SAMPLE_2"," vypadat:");
define("_LEAGUE_PLAYER_GUID_STATUS"," GUID status");
define("_LEAGUE_PLAYER_GUID_STATUS_YES"," GUID zadán");
define("_LEAGUE_PLAYER_GUID_TYPE","Typ GUIDu");
define("_LEAGUE_PLAYER_GUID_VALUE","Hodnota");
define("_LEAGUE_PLAYER_GUIDS","Herní GUIDy/ID");
define("_LEAGUE_TEAM_GUIDS","Týmové GUIDy");
define("_LEAGUE_TEAM_GUIDS_TEAM_WASNT_SELECTED","Nebyl vybrán tým.");
define("_LEAGUE_TEAM_GUIDS_PLAYERS_COUNTRY","Země");
define("_LEAGUE_TEAM_GUIDS_PLAYERS_GAME","Hra");
define("_LEAGUE_TEAM_GUIDS_PLAYERS_GUIDS","GUIDy");
define("_LEAGUE_TEAM_GUIDS_PLAYERS_NICK","Nick");
}
define("_LEAGUE_PLAYER_HOME_PLAYER_LEAGUES_NAME","Název ligy");
define("_LEAGUE_PLAYER_HOME_PLAYER_LEAGUES_OPTIONS","Možnosti");
define("_LEAGUE_PLAYER_HOME_PLAYER_LEAGUES_STATUS","Status");
define("_LEAGUE_PLAYER_ID","ID Hráče");
define("_LEAGUE_PLAYER_JOIN_BUTTON_NO","NE - Nechci vstoupit do týmu ");
define("_LEAGUE_PLAYER_JOIN_BUTTON_YES","ANO - Chci vstoupit do týmu ");
define("_LEAGUE_PLAYER_JOIN_MEMBER_NO_TEAM","Nejste členem žádného týmu v této hře.");
define("_LEAGUE_PLAYER_JOIN_MEMBER_OF","V této hře již jste členem týmu");
define("_LEAGUE_PLAYER_JOIN_MEMBER_OF_HELP","Pokud budete souhlasit se vstupem do nového týmu, automaticky opustíte svůj současný tým. <br> POZOR! Momentem přestupu se začíná 24 hodinová ochranná lhůta. Podle pravidel a povahy jednotlivých lig se v této lhůtě buď nebudete moci zůčastnit žádné soutěže, nebo se vaše výsledky boudou započítávat týmu ze kterého jste přestoupili. Pro zamezení nadměrné fluktuace také není možno přestupovat či vystupovat z týmu.");
define("_LEAGUE_PLAYER_JOIN_NO_TEAM_MEMBER","Ještě nejste členem žádného týmu v této hře.");
define("_LEAGUE_PLAYER_JOIN_SAFE","Ještě stále se nacházíte v 24 hodinové ochranné lhůtě, ve které není možno přestoupit k jinému týmu.<br>Tato lhůta vyprší ");
define("_LEAGUE_PLAYER_JOIN_TEAM","Vstoupit do týmu");
define("_LEAGUE_PLAYER_JOIN_TEAM_CONFIRM","Chystáte se vstoupit do týmu: ");
define("_LEAGUE_PLAYER_JOIN_TEAM_CONTINUE","Pokračovat");
define("_LEAGUE_PLAYER_JOIN_TEAM_IN_GAME","Ve hře: ");
define("_LEAGUE_PLAYER_JOIN_TEAM_REQUEST","Zažádat o vstup do týmu");
define("_LEAGUE_PLAYER_JOIN_TEAM_SELECT","Napište název hledaného týmu");
define("_LEAGUE_PLAYER_JOIN_TEAM_SELECT_GAME","Vyberte hru");
define("_LEAGUE_PLAYER_KICK_BUTTON_NO","NE - Nevyhodit hráče");
define("_LEAGUE_PLAYER_KICK_BUTTON_YES","ANO - Vyhodit hráče");
define("_LEAGUE_PLAYER_KICK_NEW_CAPTAIN","Nový kapitán");
define("_LEAGUE_PLAYER_KICK_NO_ID","Nebylo zadáno ID hráče!");
define("_LEAGUE_PLAYER_KICK_NO_IS_OWNER","Nelze vyhodit majitele týmu!");
define("_LEAGUE_PLAYER_KICK_QUEST","Opravdu chcete vyhodit z týmu hráče: ");
define("_LEAGUE_PLAYER_KICK_QUEST_CAPTAIN"," je kapitánem týmu, pri jeho vyhození musíte vybrat kapitána týmu.");
define("_LEAGUE_PLAYER_LEAGUE_LEAVE_Q"," - Opravdu se chcete odhlásit z této ligy?");
define("_LEAGUE_PLAYER_LEAGUE_LEAVE_R_0","Jiné");
define("_LEAGUE_PLAYER_LEAGUE_LEAVE_R_1","Nedostatek kvalitních soupeřů");
define("_LEAGUE_PLAYER_LEAGUE_LEAVE_R_2","Nesouhlas s pravidly ligy");
define("_LEAGUE_PLAYER_LEAGUE_LEAVE_R_3","Nedostatek hráčů v lize");
define("_LEAGUE_PLAYER_LEAGUE_LEAVE_TITLE","Odhlášení z ligy");
define("_LEAGUE_PLAYER_LEAGUE_REG_ALREADY","V této lize jste již registrováni");
define("_LEAGUE_PLAYER_LEAGUE_REG_BANNED","V této lize máte udělen ban");
define("_LEAGUE_PLAYER_LEAGUE_REG_Q","Opravdu se chcete registrovat do této ligy?");
define("_LEAGUE_PLAYER_LEAGUE_REG_TO","Registrovat do ligy jednotlivců");
define("_LEAGUE_PLAYER_LEAVE_BUTTON_NO","NE - Nechci opustit tým");
define("_LEAGUE_PLAYER_LEAVE_BUTTON_YES","ANO - Chci opustit tým");
define("_LEAGUE_PLAYER_LEAVE_CAPTAIN","Jste kapitánem týmu, při opuštění týmu musíte vybrat svého nástupce na postu kapitána.");
define("_LEAGUE_PLAYER_LEAVE_NEW_CAPTAIN","Nový kapitán");
define("_LEAGUE_PLAYER_LEAVE_NEW_OWNER","Nový vlastník");
define("_LEAGUE_PLAYER_LEAVE_OWNER","Jste majitelem týmu, při opuštění týmu musíte vybrat svého nástupce na postu majitele.");
define("_LEAGUE_PLAYER_LEAVE_OWNER_ONLY","Jste majitel týmu a jeho jediný člen. Při opuštění týmu, tento přejde do trvalé hibernace. Týmu zůstanou všechny jeho výsledky a ocenění, ale již nikdy ho nebude možno aktivovat.<br><br>Opravdu si přejete tým opustit a hibernovat?");
define("_LEAGUE_PLAYER_LEAVE_QUEST","Opravdu chcete opustit tým");
define("_LEAGUE_PLAYER_LEAVE_TEAM","Opustit tým");
define("_LEAGUE_PLAYER_LOG","Historie hráče");
define("_LEAGUE_PLAYER_MAKE_NO_MODE","Nebyl vybrán správný mód funkce.");
define("_LEAGUE_PLAYER_MAKE_NO_PLAYER","Nebyl vybrán hráč.");
define("_LEAGUE_PLAYER_MAKE_Q_ASSISTANT_1","Opravdu chcete udělit hráči ");
define("_LEAGUE_PLAYER_MAKE_Q_ASSISTANT_2","  pozici asistenta týmu?");
define("_LEAGUE_PLAYER_MAKE_Q_ASSISTANT_3","Ano - Udělit pozici asistenta");
define("_LEAGUE_PLAYER_MAKE_Q_CAPTAIN_1","Opravdu chcete udělit hráči ");
define("_LEAGUE_PLAYER_MAKE_Q_CAPTAIN_2","  pozici kapitána týmu?");
define("_LEAGUE_PLAYER_MAKE_Q_CAPTAIN_3","Ano - Udělit pozici kapitána");
define("_LEAGUE_PLAYER_MAKE_Q_OWNER_1","Opravdu chcete předat hráči ");
define("_LEAGUE_PLAYER_MAKE_Q_OWNER_2","vlastnictví týmu?");
define("_LEAGUE_PLAYER_MAKE_Q_OWNER_3","ANO - Předat vlastnictví týmu");
define("_LEAGUE_PLAYER_MAKE_Q_PLAYER_1","Opravdu chcete udělit hráči ");
define("_LEAGUE_PLAYER_MAKE_Q_PLAYER_2","  pozici hráče?");
define("_LEAGUE_PLAYER_MAKE_Q_PLAYER_3","ANO - udělit pozici hráče");
define("_LEAGUE_PLAYER_NICK","Nick");
define("_LEAGUE_PLAYER_NO_GAME","Nebyla vybrána hra pro hráče! Kontaktujte prosím admina.");
define("_LEAGUE_PLAYER_NO_LEAGUE","Nebyla vybrána liga! Kontaktujte prosím admina.");
define("_LEAGUE_PLAYER_NO_PLAY","Hráč nebyl vybrán a nemůže se účastnit ligy");
define("_LEAGUE_PLAYER_PLAY","Hráč byl vybrán a může se účastnit ligy");
define("_LEAGUE_PLAYER_REG_SUBMIT","Registrovat");
define("_LEAGUE_PLAYER_SAFE_TIME","Nacházíte v 24 hodinové ochranné lhůtě, ve které není možno vystoupit z týmu.<br>Tato lhůta vyprší ");
define("_LEAGUE_PLAYER_STATUS_ASSISTANT","Asistent");
define("_LEAGUE_PLAYER_STATUS_BAN_YOU","V této lize máte ban");
define("_LEAGUE_PLAYER_STATUS_BAN_HIM","Hráč má v této lize ban");
define("_LEAGUE_PLAYER_STATUS_CAPTAIN","Kapitán");
define("_LEAGUE_PLAYER_STATUS_OWNER","Vlastník");
define("_LEAGUE_PLAYER_STATUS_PLAYER","Hráč");
define("_LEAGUE_RESULTS_COUNTRY","Země");
define("_LEAGUE_RESULTS_NICK","Nick");
define("_LEAGUE_RESULTS_PLACE","Umístění");
define("_LEAGUE_RESULTS_PLAYERS","Hráči");
define("_LEAGUE_RESULTS_POINTS","Body");
define("_LEAGUE_RESULTS_ROUND","Kolo");
define("_LEAGUE_RESULTS_SEASON","Sezóna");
define("_LEAGUE_RESULTS_TEAM","Tým");
define("_LEAGUE_RESULTS_TEAMS","Týmy");
define("_LEAGUE_TEAM","Tým");
define("_LEAGUE_TEAM_AWARDS","Získaná ocenění");
define("_LEAGUE_TEAM_COMMENT","Komentář");
define("_LEAGUE_TEAM_COUNTRY","Země");
define("_LEAGUE_TEAM_GAME","Hra");
define("_LEAGUE_TEAM_GAME_ADD","Přidat hru");
define("_LEAGUE_TEAM_GAME_REG_IN_ALL","Váš tým již má zaregistrovány všechny dostupné hry.");
define("_LEAGUE_TEAM_HIBERNATE","Hibernovat team");
define("_LEAGUE_TEAM_HIBERNATE_BACK_TO_TEAM","Zpátky na stránku týmu");
define("_LEAGUE_TEAM_HIBERNATE_CHECK","Opravdu chcete tento tým hibernovat? Po hibernaci již není možno tým znovu aktivovat!");
define("_LEAGUE_TEAM_HIBERNATE_PLAYERS_IN_SUB_TEAM","Tým není možno hibernovat dokud jsou v podtýmu/podtýmech hráči.");
define("_LEAGUE_TEAM_HIBERNATE_PROCEED_NO","Ne - nepřeji si tento tým hibernovat");
define("_LEAGUE_TEAM_HIBERNATE_PROCEED_YES","Ano - přeji si tento tým hibernovat");
define("_LEAGUE_TEAM_HIBERNATE_TEAM_WASNT_SELECTED","Nebyl vybrán tým.");
define("_LEAGUE_TEAM_HOME_COUNTRY","Země");
define("_LEAGUE_TEAM_HOME_GAME","Hra");
define("_LEAGUE_TEAM_HOME_GENERAL","Hlavní informace");
define("_LEAGUE_TEAM_HOME_LAST_CHANGES","Poslední změny");
define("_LEAGUE_TEAM_HOME_OWNER","Majitel");
define("_LEAGUE_TEAM_HOME_PLAYER_JOIN_ACCEPT","Přijmout / Odmítnout hráče");
define("_LEAGUE_TEAM_HOME_PLAYERS_OPTIONS","Možnosti");
define("_LEAGUE_TEAM_HOME_PLAYERS","Hráči");
define("_LEAGUE_TEAM_HOME_PLAYERS_COUNTRY","Země");
define("_LEAGUE_TEAM_HOME_PLAYERS_GAME","Hra");
define("_LEAGUE_TEAM_HOME_PLAYERS_NICK","Nick");
define("_LEAGUE_TEAM_HOME_PLAYERS_PENDING","Čekající hráči");
define("_LEAGUE_TEAM_HOME_PLAYERS_POSITION","Pozice");
define("_LEAGUE_TEAM_HOME_PLAYERS_POSITION_ASSISTANT","Asistent");
define("_LEAGUE_TEAM_HOME_PLAYERS_POSITION_CAPTAIN","Kapitán");
define("_LEAGUE_TEAM_HOME_PLAYERS_POSITION_OWNER","Majitel");
define("_LEAGUE_TEAM_HOME_PLAYERS_POSITION_PLAYER","Hráč");
define("_LEAGUE_TEAM_HOME_PLAYERS_POSITION_PENDING_NONE","Nic");
define("_LEAGUE_TEAM_HOME_PLAYERS_POSITION_PENDING_PLAYER","Čeká na povolení hráčem");
define("_LEAGUE_TEAM_HOME_PLAYERS_POSITION_PENDING_TEAM","Čeká na povolení týmem");
define("_LEAGUE_TEAM_HOME_SUB_TEAMS","Podtýmy");
define("_LEAGUE_TEAM_HOME_TEAM_NAME","Název týmu");
define("_LEAGUE_TEAM_HOME_TEAM_LEAGUES","Ligy");
define("_LEAGUE_TEAM_HOME_TEAM_LEAGUES_NAME","Název ligy");
define("_LEAGUE_TEAM_HOME_TEAM_LEAGUES_OPTIONS","Možnosti");
define("_LEAGUE_TEAM_HOME_TEAM_LEAGUES_STATUS","Status týmu");
define("_LEAGUE_TEAM_HOME_TEAM_LEAGUES_STATUS_LESS","Nesplňuje podmínky ligy: Tým má méně než povolený počet hráčů");
define("_LEAGUE_TEAM_HOME_TEAM_LEAGUES_STATUS_OK","Tým splňuje podmínky ligy");
define("_LEAGUE_TEAM_HOME_TEAM_LEAGUES_STATUS_OVER","Nesplňuje podmínky ligy: Tým má více než povolený počet hráčů");
define("_LEAGUE_TEAM_HOME_TEAM_LEAGUES_LEAVE","Odhlásit z ligy");
define("_LEAGUE_TEAM_HOME_WWW","Web");
define("_LEAGUE_TEAM_IRC","IRC");
define("_LEAGUE_TEAM_JOIN_BUTTON_NO","Ne - Odmítnout hráče ");
define("_LEAGUE_TEAM_JOIN_BUTTON_YES","Ano - Přijmout hráče ");
define("_LEAGUE_TEAM_LEAGUE_ALLOWED_PLAYERS","Povolení hráči:");
define("_LEAGUE_TEAM_LEAGUE_LEAVE_Q"," - Opravdu chcete váš tým odhlásit z této ligy?");
define("_LEAGUE_TEAM_LEAGUE_LEAVE_R_0","Jiné");
define("_LEAGUE_TEAM_LEAGUE_LEAVE_R_1","Nedostatek kvalitních soupeřů");
define("_LEAGUE_TEAM_LEAGUE_LEAVE_R_2","Nesouhlas s pravidly ligy");
define("_LEAGUE_TEAM_LEAGUE_LEAVE_R_3","Nedostatek hráčů v týmu");
define("_LEAGUE_TEAM_LEAGUE_LEAVE_TITLE","Odhlášení z ligy");
define("_LEAGUE_TEAM_LEAGUE_LOCKED","Liga je zamknuta");
define("_LEAGUE_TEAM_LEAGUE_REG","Registrace do ligy");
define("_LEAGUE_TEAM_LEAGUE_REG_ALREADY","V této lize už je váš tým registrován");
define("_LEAGUE_TEAM_LEAGUE_REG_IN_ALL","Nebyla nalezena žádná liga k registraci");
define("_LEAGUE_TEAM_LEAGUE_REG_NO_MODE","Nebyl vybrán správný mód funkce");
define("_LEAGUE_TEAM_LEAGUE_REG_Q"," - Opravdu chcete váš tým registrovat do této ligy?");
define("_LEAGUE_TEAM_LEAGUE_REG_TO","Registrovat do týmové ligy");
define("_LEAGUE_TEAM_LEAGUE_REGISTER","Registrovat");
define("_LEAGUE_TEAM_LIST_COUNTRY","Země");
define("_LEAGUE_TEAM_LIST_GAME","Hra");
define("_LEAGUE_TEAM_LIST_ID","ID");
define("_LEAGUE_TEAM_LIST_NAME","Název");
define("_LEAGUE_TEAM_LOG","Historie týmu");
define("_LEAGUE_TEAM_LOGO","Logo týmu");
define("_LEAGUE_TEAM_LOGO_HEIGHT","Výška - ");
define("_LEAGUE_TEAM_LOGO_SIZE","Velikost - ");
define("_LEAGUE_TEAM_LOGO_WIDTH","Šířka - ");
define("_LEAGUE_TEAM_MOTTO","Motto týmu");
define("_LEAGUE_TEAM_NAME","Název týmu");
define("_LEAGUE_TEAM_NO_GAME","Nebyla vybrána hra pro tým! Kontaktujte prosím admina.");
define("_LEAGUE_TEAM_PASS","Heslo ke vstupu do týmu");
define("_LEAGUE_TEAM_PASS_HELP","(min 4 - max 8 znaků)");
define("_LEAGUE_TEAM_PENDING","Čekající tým");
define("_LEAGUE_TEAM_PLAYER_CHECK_24","Tento hráč se nalézá ve 24 hodinové ochranné lhůtě, ve které se nebude moci připojit k vašemu týmu.<br>Tato lhůta vyprší ");
define("_LEAGUE_TEAM_PLAYER_ADD","Přidat hráče");
define("_LEAGUE_TEAM_PLAYER_ADD_HELP_1","Zadejte ID nebo email hráče, kterého chcete pozvat do ");
define("_LEAGUE_TEAM_PLAYER_ADD_HELP_2","Pokud daný hráč ještě není registrován musí se registrovat pomocí registračního formuláře na tomto webu.");
define("_LEAGUE_TEAM_PLAYER_ALREADY_IN","Tento hráč už je ve vašem týmu a není ho tedy možno přidat znovu.");
define("_LEAGUE_TEAM_PLAYER_ALREADY_REQUESTED","Tomuto hráči již byla pozvánka odeslána a není ho tedy možno požádat o vstup znovu dokud vaší pozvánku nepotvrdí nebo nezamítne.");
define("_LEAGUE_TEAM_PLAYER_EMAIL","Emailová adresa");
define("_LEAGUE_TEAM_PLAYER_CHANGE_OPTIONS_HELP","V současnosti jste již členem některého z týmu. Dle pravidel jeden hráč nemůže hrát ve dvou týmech hrající stejnou hru. Pokud založíte nový tým, automaticky přejdete z vašeho současného týmu do týmu nového.");
define("_LEAGUE_TEAM_PLAYER_CHECK_HELP_1","Opravdu chcete pozvat ");
define("_LEAGUE_TEAM_PLAYER_CHECK_HELP_2"," do vašeho týmu?");
define("_LEAGUE_TEAM_PLAYER_ID","Hráčovo ID");
define("_LEAGUE_TEAM_PLAYER_KICK","Vyhodit");
define("_LEAGUE_TEAM_PLAYER_MAKE_ASSISTANT","Udělat asistentem");
define("_LEAGUE_TEAM_PLAYER_MAKE_CAPTAIN","Udělat kapitánem");
define("_LEAGUE_TEAM_PLAYER_MAKE_OWNER","Předat tým");
define("_LEAGUE_TEAM_PLAYER_MAKE_PLAYER","Udělat hráčem");
define("_LEAGUE_TEAM_PLAYER_NICK","Nick");
define("_LEAGUE_TEAM_PLAYER_OR","nebo");
define("_LEAGUE_TEAM_PLAYER_OWN_TEAM","Již máte jeden tým registrován. Nemůžete být vlastník víc než jednoho týmu.");
define("_LEAGUE_TEAM_PLAYER_PLAY_SAME_GAME","Již jste registrován(a) v jiném týmu hrající stejnou hru. Nemůžete být člen/členka víc než jednoho týmu v dané hře.");
define("_LEAGUE_TEAM_PLAYER_SEARCH","Vyhledat hráče");
define("_LEAGUE_TEAM_PLAYER_SEARCH_AGAIN","Vyhledat hráče");
define("_LEAGUE_TEAM_PLAYER_TAKE_ASSISTANT","Odebrat asistentství");
define("_LEAGUE_TEAM_PLAYER_TAKE_CAPTAIN","Odebrat kapitánství");
define("_LEAGUE_TEAM_SUBMIT_EDIT","Editovat tým");
define("_LEAGUE_TEAM_SUBMIT_REG","Registrovat tým");
define("_LEAGUE_TEAM_SERVER_1","Server #1");
define("_LEAGUE_TEAM_SERVER_2","Server #2");
define("_LEAGUE_TEAM_SERVER_3","Server #3");
define("_LEAGUE_TEAM_SERVER_4","Server #4");
define("_LEAGUE_TEAM_TAG","Tag týmu");
define("_LEAGUE_TEAM_WEB","Web");
define("_LEAGUE_TEAMS","Týmy");
/***************************************************************************************************************
*
*		add_link.php
*
***************************************************************************************************************/
define("_LINK_ID","ID článku");
define("_LINK_INSERT","Vložit odkaz");
define("_LINK_TARGET","Cíl");
define("_LINK_ALT","Název odkazu");
define("_LINK_TITLE","Vložení odkazu na článek");
define("_LINK_TYPE","Typ");
define("_LINK_LINK","Odkaz");
/***************************************************************************************************************
*
*		LINKS
*
***************************************************************************************************************/
define("_LINKS","Odkazy");
define("_LINKS_ADD_LINK","Přidat odkaz");
define("_LINKS_ADD_TEAM","Přidat tým");
define("_LINKS_DESC","Popis");
define("_LINKS_IMAGE","Obrázek");
define("_LINKS_IMAGE_HEIGHT","Výška");
define("_LINKS_IMAGE_SIZE","Velikost souboru Max.");
define("_LINKS_IMAGE_WIDTH","Šířka");
define("_LINKS_LINK","Odkaz");
define("_LINKS_TITLE","Název");
//**************************************************************************************************************
//
//		class.mail.php
//
//**************************************************************************************************************
define("_MAIL_PROV_ADRESS","Musíte zadat alespoň jednu emailovou adresu příjemce.");
define("_MAIL_MAILER_NOT_SUPP"," mailový klient není podporován.");
define("_MAIL_EXECUTE","Nelze provést: ");
define("_MAIL_INSTATNTIATE","Nelze vytvořit instanci emailové funkce.");
define("_MAIL_AUTH","SMTP Error: Nemožnost autentifikace.");
define("_MAIL_FROM_FAILED","Následující adresa From je nesprávná: ");
define("_MAIL_REC_FAILED","SMTP Error: Adresy příjemců nejsou správné ");
define("_MAIL_DATA_NOT_ACCEPTED","SMTP Error: Data nebyla přijata");
define("_MAIL_CONNECT_HOST","SMTP Error: Nelze navázat spojení se SMTP serverem.");
define("_MAIL_FILE_ACCESS","Soubor nenalezen: ");
define("_MAIL_OPEN","File Error: Nelze otevřít soubor pro čtení: ");
define("_MAIL_ENCODING","Neznámé kódování: ");
/***************************************************************************************************************
*
*		SYSTEM MESSAGE
*
***************************************************************************************************************/
define("_MSG_FLASH_NO_FLASH","Pozor, máte vypnutý jazyk JavaScript nebo máte starou verzi přehrávače Adobe Flash Player. <a href=\"http://www.adobe.com/go/getflashplayer/\">Získejte nejnovější přehrávač Flash Player.</a>");
/***************************************************************************************************************
*																												
*		MTG																							
*																												
***************************************************************************************************************/
define("_MTG_CARD_MANA_COST","Mana cost");
define("_MTG_CARD_NAME","Název karty");
define("_MTG_CARD_SET","Expanze");
define("_MTG_CARD_TYPES","Typ");
define("_MTG_RARITY_C","Common");
define("_MTG_RARITY_M","Mythic Rare");
define("_MTG_RARITY_R","Rare");
define("_MTG_RARITY_T","Special");
define("_MTG_RARITY_U","Uncommon");
/***********************************************************************************************************
*
*		PODCASTS
*
***********************************************************************************************************/
define("_PODCASTS_ITEM_AUTHOR","Autor");
define("_PODCASTS_ITEM_DATE","Datum");
define("_PODCASTS_ITEM_DURATION","Délka");
define("_PODCASTS_ITEM_TITLE","Název");
define("_PODCASTS_ITEM_SHOW_ALL_CHANNELS","Všechny kanály");
define("_PODCASTS_ITEM_SHOW_ALL_ITEMS","Všechny podcasty kanálu");
/***************************************************************************************************************
*
*		POLL
*
***************************************************************************************************************/
define("_POLL","Anketa");
define("_POLL_24","Lze přidat jen jednu anketu za 24 hodin");
define("_POLL_ADD_POLL","Přidat anketu");
define("_POLL_ADD_POLL_AFTER_LOGIN","Přídávat ankety můžete až po přihlášení");
define("_POLL_ANSWERS","Odpovědi");
define("_POLL_ANSWERS_NUM","Počet odpovědí:");
define("_POLL_AUTHOR","Autor");
define("_POLL_COMMENTS","Kom.");
define("_POLL_DATE","Datum");
define("_POLL_CHECK_DEL","Opravdu chcete tuto anketu odstranit?");
define("_POLL_OLDER","Starší ankety");
define("_POLL_QUESTION","Otázka");
define("_POLL_QUESTIONS","Otázky");
define("_POLL_SEPARATE","V rámci zachování konzistence odpovědí nejde odpovědi editovat, překontrolujte si proto anketní otázky a odpovědi před tím, než dáte odeslat.<br><br>Lze přidat jen jednu anketu za 24 hodin");
define("_POLL_VOTE","Hlasovat");
/***************************************************************************************************************
*
*		POST EDITOR
*
***************************************************************************************************************/
define("_POST_EDITOR_CLOSE_TAGS","zavřít značky");
define("_POST_EDITOR_ERR_TYPE_POST","Musíte zadat text příspěvku");
define("_POST_EDITOR_FONT_COLOR","Barva písma:");
define("_POST_EDITOR_FONT_COLOR_BASIC","Výchozí");
define("_POST_EDITOR_FONT_COLOR_BLACK","Černá");
define("_POST_EDITOR_FONT_COLOR_BLUE","Modrá");
define("_POST_EDITOR_FONT_COLOR_BROWN","Hnědá");
define("_POST_EDITOR_FONT_COLOR_CYAN","Akvamarínová");
define("_POST_EDITOR_FONT_COLOR_DARKBLUE","Tmavě modrá");
define("_POST_EDITOR_FONT_COLOR_DARKRED","Kaštanová");
define("_POST_EDITOR_FONT_COLOR_GREEN","Zelená");
define("_POST_EDITOR_FONT_COLOR_INDIGO","Fialová");
define("_POST_EDITOR_FONT_COLOR_OLIVE","Olivová");
define("_POST_EDITOR_FONT_COLOR_ORANGE","Oranžová");
define("_POST_EDITOR_FONT_COLOR_RED","Červená");
define("_POST_EDITOR_FONT_COLOR_VIOLET","Fuchsiová");
define("_POST_EDITOR_FONT_COLOR_WHITE","Bílá");
define("_POST_EDITOR_FONT_COLOR_YELLOW","Žlutá");
define("_POST_EDITOR_FONT_SIZE","Velikost písma:");
define("_POST_EDITOR_FONT_SIZE_BASIC","Výchozí");
define("_POST_EDITOR_FONT_SIZE_BIG","Velké");
define("_POST_EDITOR_FONT_SIZE_BIGGEST","Obrovské");
define("_POST_EDITOR_FONT_SIZE_SMALL","Malé");
define("_POST_EDITOR_FONT_SIZE_SMALLEST","Drobné");
define("_POST_EDITOR_PREVIEW","Náhled:");
define("_POST_EDITOR_TAGS_HELP_BOLD","Tučné: [b]text[/b](alt+b)");
define("_POST_EDITOR_TAGS_HELP_ITALIC","Kurzíva: [i]text[/i](alt+i)");
define("_POST_EDITOR_TAGS_HELP_UNDERLINE","Podtržené: [u]text[/u](alt+u)");
define("_POST_EDITOR_TAGS_HELP_QUOTE","Citace: [quote]text[/quote](alt+q)");
define("_POST_EDITOR_TAGS_HELP_CODE","Zobrazení kódu: [code]code[/code](alt+c)");
define("_POST_EDITOR_TAGS_HELP_LIST","Seznam: [list]text[/list] (alt+l)");
define("_POST_EDITOR_TAGS_HELP_OLIST","Uspořádaný seznam: [list=]text[/list=](alt+o)");
define("_POST_EDITOR_TAGS_HELP_IMAGE","Vložit obrázek: [img]http://image_url[/img](alt+p)");
define("_POST_EDITOR_TAGS_HELP_URL","Vložit URL: [url]http://url[/url] or [url=http://url]URL text[/url](alt+w)");
define("_POST_EDITOR_TAGS_HELP_CLOSE_TAGS","Zavře všechny otevřené značky");
define("_POST_EDITOR_TAGS_HELP_FONT_COLOR","Barva písma: [color=red]text[/color]Tip: můžete použít také color=#FF0000");
define("_POST_EDITOR_TAGS_HELP_FONT_SIZE","Velikost písma: [size=x-small]malý text[/size]");
define("_POST_EDITOR_TAGS_HELP_HIDE","Skrýt zprávu: [hide]Text skryté zprávy[/hide] (alt+h)");
define("_POST_EDITOR_TAGS_HELP_TIP","Tip: Styl můžete aplikovat rychleji na označeném textu");
/***************************************************************************************************************
*
*		RECOMMEND TO FRIEND
*
***************************************************************************************************************/
define("_RECOMMEND","Doporučit");
define("_RECOMMEND_EMAIL_FROM_ACT","aktualitu");
define("_RECOMMEND_EMAIL_FROM_ACT_B","Aktualitu");
define("_RECOMMEND_EMAIL_FROM_ARTICLES","článek");
define("_RECOMMEND_EMAIL_FROM_ARTICLES_B","Článek");
define("_RECOMMEND_EMAIL_FROM_SHOP","produkt");
define("_RECOMMEND_EMAIL_FROM_SHOP_B","Produkt");
define("_RECOMMEND_EMAIL_SUBJECT"," doporučení od přítele");
define("_RECOMMEND_EMAIL_TEXT_1","Tento email vám byl zaslán, protože ");
define("_RECOMMEND_EMAIL_TEXT_2"," by chtěl/chtěla doporučit níže uvedený ");
define("_RECOMMEND_EMAIL_TEXT_3",".");
define("_RECOMMEND_FORM_FROM_EMAIL","Váš email");
define("_RECOMMEND_FORM_FROM_NAME","Váše jméno");
define("_RECOMMEND_FORM_CHECK_EMAIL1","Zadejte prosím validní emailovou adresu");
define("_RECOMMEND_FORM_CHECK_EMAIL2","Emailová adresa");
define("_RECOMMEND_FORM_CHECK_EMAIL3","je nesprávná");
define("_RECOMMEND_FORM_CHECK_EMAIL4","Prosím zadejte méně než 10 emailových adres.");
define("_RECOMMEND_FORM_MESSAGE","Poznámka (Nepovinné)");
define("_RECOMMEND_FORM_SUBJECT","Předmět (Nepovinné)");
define("_RECOMMEND_FORM_TO_EMAIL","Email přítele");
define("_RECOMMEND_INFO_1","Tímto formulářem odešlete níže umístěný odkaz vašemu příteli.");/* Pokud chcete odkaz odeslat více přátelům, oddělte jejich email adresy středníkem(;).*/
define("_RECOMMEND_INFO_2","Emailová adresy jsou použity výhradně k odeslání vašeho doporučení a nejsou nikde zaznamenány.");
define("_RECOMMEND_TO_EMAIL","Komu (email)");
define("_RECOMMEND_TO_FRIEND","Doporučit příteli");
define("_RECOMMEND_WHO","Vaše jméno");
/***************************************************************************************************************
*
*		eden_save.php
*
***************************************************************************************************************/
define("_SAVE_FORGPASS_ONCEUSE","Tento odkaz muze byt pouzit pouze jednou.");
define("_SAVE_NEW_REGISTRATION","Nová registrace");
//**************************************************************************************************************
//
//		EDEN Shop
//
//**************************************************************************************************************
define("_SHOP_01_CUSTOMER_LOGIN","Přihlášení zákazníka");
define("_SHOP_01_CUSTOMER_REG","Registrace zákazníka");
define("_SHOP_02_AGREE","Přečetl jsem a souhlasím se smluvními podmínkami.");
define("_SHOP_02_TERMS","Podmínky nákupu");
define("_SHOP_03_BASKET_CONTENTS","Obsah košíku");
define("_SHOP_03_CUSTOMER_ADDRESS","Adresa zákazníka");
define("_SHOP_03_CUSTOMER_AND_DELIVERY","Zákazník a dodací adresa");
define("_SHOP_03_DELIVERY_ADDRESS","Adresa dodání");
define("_SHOP_03_DELIVERY_OPTIONS","Přepravní služba");
define("_SHOP_03_PAYMENT_METHOD","Platební metody");
define("_SHOP_04_BASKET_CONTENTS","Obsah košíku");
define("_SHOP_04_CONFIRM_ORDER","Potvrdit objednávku");
define("_SHOP_04_CUSTOMER_ADDRESS","Adresa zákazníka");
define("_SHOP_04_DELIVERY_ADDRESS","Adresa dodání");
define("_SHOP_04_DETAILS","Detaily");
define("_SHOP_04_IMPORTANT_INFO","Důležité informace");
define("_SHOP_04_NOT_YET_CONFIRMED","Vaše objednávka ještě není potvrzena");
define("_SHOP_05_ADDITIONAL_INFO","Doplňující informace");
define("_SHOP_05_CUSTOMER_ADDRESS","Adresa zákazníka");
define("_SHOP_05_DELIVERY_ADDRESS","Adresa dodání");
define("_SHOP_05_DETAILS","Detaily");
define("_SHOP_05_ORDER","Vaše objednávka");
define("_SHOP_05_ORDER_CANCELED","Objednávka byla stornována");
define("_SHOP_05_ORDER_COMPLETE","Objednávka je kompletní");
define("_SHOP_ADD_TO_BASKET","Přidat do košíku");
define("_SHOP_BASKET","Košík");
define("_SHOP_BASKET_EMPTY","Ve vašem košíku není žádné zboží.");
define("_SHOP_BASKET_EMPTY_PLEASE","Prosím");
define("_SHOP_BUTTON_PROCEED","Provést >>");
define("_SHOP_BUTTON_RECALCULATE","Přepočítat");
define("_SHOP_CARRIAGE","Doprava");
define("_SHOP_CODE","Kód");
define("_SHOP_COMPANY_NAME","Název společnosti");
define("_SHOP_CONFIRM_INV_NUM","Číslo objednávky");
define("_SHOP_CONFIRM_ACC_NUM","Číslo uživatelského účtu");
define("_SHOP_CONFIRM_INV_DATE","Datum objednávky");
define("_SHOP_CONFIRM_EST_DEL_DATE","Předpokládaný datum dodávky");
define("_SHOP_CONFIRM_IP","IP Adresa");
define("_SHOP_CONFIRM_TO_BE","Bude potvrzeno");
define("_SHOP_CUSTOMER_ADDRESS","Adresa:");
define("_SHOP_CUSTOMER_CITY","Město:");
define("_SHOP_CUSTOMER_COUNTRY","Země:");
define("_SHOP_CUSTOMER_EMAIL","Email:");
define("_SHOP_CUSTOMER_FILL_FIELD","Prosím vyplňtě označená pole. Pak můžete pokračovat v objednávce.");
define("_SHOP_CUSTOMER_MOBILE","Mobil:");
define("_SHOP_CUSTOMER_NAME","Jméno:");
define("_SHOP_CUSTOMER_POSTCODE","PSČ:");
define("_SHOP_CUSTOMER_TELEPHONE","Telefon:");
define("_SHOP_DESIGN_NOT_AVAIL","Vámi vybraný produkt již není dále v naší nabídce");
define("_SHOP_HINT_QUANT_BOX1","U tohoto produktu není možno změnit množství");
define("_SHOP_LOGIN","Přihlášení");
define("_SHOP_LOGOUT","Odhlášení");
define("_SHOP_NEP","Produkt není na skladě. Pokud chcete pokračovat, prosím odeberte zvýrazněný produkt.");
define("_SHOP_NETT_TOTAL","Celkem bez DPH");
define("_SHOP_ORDER_STATUS","Stav objednávky: ");
define("_SHOP_ORDER_STATUS_1","Objednává se");
define("_SHOP_ORDER_STATUS_2","Odesláno k zaplacení / Čekání na potvrzení platby");
define("_SHOP_ORDER_STATUS_3","Platba potvrzena / Předáno k zabalení");
define("_SHOP_ORDER_STATUS_4","Objednávka zabalena / Čekání na odeslání");
define("_SHOP_ORDER_STATUS_5","Objednávka odeslána");
define("_SHOP_ORDER_STATUS_6","Stornováno před platbou");
define("_SHOP_ORDER_STATUS_7","Stornováno po platbě");
define("_SHOP_PREV_ORDER","Předchozí objednávky");
define("_SHOP_PREV_ORDER_DATE","Datum obj.");
define("_SHOP_PREV_ORDER_ID","Číslo obj.");
define("_SHOP_PREV_ORDER_PRICE","Cena obj.");
define("_SHOP_PREV_ORDER_STATUS","Stav objednávky");
define("_SHOP_PRICE_EX_VAT","Cena bez daně");
define("_SHOP_PRICE_EX_VAT_S","Bez DPH");
define("_SHOP_PRICE_INC_VAT","Cena s daní");
define("_SHOP_PRICE_INC_VAT_S","S DPH");
define("_SHOP_PROGRESS_ADD_DELIVERY","Přidat dodací adresu");
define("_SHOP_PROGRESS_AGREE_WAR","Pro další pokračování v objednávce požadujeme od všech zákazníků se souhlasem se zněním smluvních podmínek.");
define("_SHOP_PROGRESS_BACK","Zpátky");
define("_SHOP_PROGRESS_CHANGE","Změnit");
define("_SHOP_PROGRESS_TOTAL_PRICE","Koncová cena: ");
define("_SHOP_QTY","Kusů");
define("_SHOP_REG","Registrovat nového zákazníka");
define("_SHOP_REM_ITEM","Odstranit z košíku");
define("_SHOP_SELLER_ADITIONAL_INFO","Doplňující informace");
define("_SHOP_SELLER_COMPANY_INFO","Informace o společnosti");
define("_SHOP_SELLER_COMPANY_NAME","Jméno společnosti");
define("_SHOP_SELLER_CONTACT_DETAILS","Kontaktní informace");
define("_SHOP_SELLER_DELIVERY_ADDRESS_1","Dodací adresa");
define("_SHOP_SELLER_DELIVERY_ADDRESS_2","");
define("_SHOP_SELLER_DELIVERY_CITY","Město");
define("_SHOP_SELLER_DELIVERY_COUNTRY","Země");
define("_SHOP_SELLER_DELIVERY_POSTCODE","PSČ");
define("_SHOP_SELLER_EMAIL","Email");
define("_SHOP_SELLER_EMAIL_REPEAT","Opakujte Email");
define("_SHOP_SELLER_FAX","Fax");
define("_SHOP_SELLER_INVOICE_ADDRESS_1","Fakturační adresa");
define("_SHOP_SELLER_INVOICE_ADDRESS_2","");
define("_SHOP_SELLER_INVOICE_CITY","Město");
define("_SHOP_SELLER_INVOICE_COUNTRY","Země");
define("_SHOP_SELLER_INVOICE_POSTCODE","PSČ");
define("_SHOP_SELLER_MOBILE","Mobil");
define("_SHOP_SELLER_NAME","Jméno");
define("_SHOP_SELLER_NEW","Nový prodejce");
define("_SHOP_SELLER_NOTE","Poznámka");
define("_SHOP_SELLER_PHONE","Telefon");
define("_SHOP_SELLER_POSITION","Pozice");
define("_SHOP_SELLER_REG_TERMS","Naše velkoobchodní sekce je jen pro prodejce. Každá registrace prochází schvalovacím procesem.");
define("_SHOP_SELLER_VAT_NUMBER","IČO");
define("_SHOP_SELLER_WEB","Web");
define("_SHOP_SELLER_YOUR_NAME","Vaše jméno");
define("_SHOP_SUBTOTAL","Mezisoučet");
define("_SHOP_TITLE","Název");
define("_SHOP_TOTAL","CELKEM");
define("_SHOP_TOTAL_VAT","DPH");
//**************************************************************************************************************
//
//		eden_shop_save.php - je i v /lang/lang-cz.php
//
//**************************************************************************************************************
define("_SHOP_SAVE_CARRIAGE","Doprava&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
define("_SHOP_SAVE_PRICE","Cena");
define("_SHOP_SAVE_PRODUCT","Produkt&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
define("_SHOP_SAVE_PRODUCT_CODE","Kód produktu&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
define("_SHOP_SAVE_QUANTITY","Množství&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
define("_SHOP_SAVE_SUB_NETT_TOTAL","Mezisoučet bez DPH&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
define("_SHOP_SAVE_SUB_TOTAL","Mezisoučet&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
define("_SHOP_SAVE_TOTAL","CELKEM&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
define("_SHOP_SAVE_TOTAL_VAT","DPH&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
define("_SHOP_SAVE_EMAIL_NEW_ORDER_SUB","Nová objednávka ");
//**************************************************************************************************************
//
//		Nazvy vlajek
//
//**************************************************************************************************************
define("_ALPS","Alpské státy");
define("_ALPY","Alpské státy");
define("_BALTIC","Baltské státy");
define("_AMERICA","Amerika");
define("_AMERIKA","Amerika");
define("_BENELUX","Benelux");
define("_SKANDINAVIA","Skandinávie");
define("_SKANDINAVIE","Skandinávie");
define("_EAST","Východ");
define("_VYCHOD","Východ");
define("_TIBET","Tibet");
define("_EU","Evropská unie");
define("_SCOTLAND","Skotsko");
define("_ENGLAND","Anglie");
define("_WAKE_ISLAND","Ostrov Wake");
define("_WALES","Wales");
define("_NORTHERN_IRELAND","Severní Irsko");
define("_NORTHERN_CYPRUS","Severní Kypr");
define("_MIDWAY_ISLANDS","Midway");
define("_JERSEY","Jersey");
define("_ISLE_OF_MAN","Ostrov Man");
define("_AFGHANISTAN","Afgánistán");
define("_ALBANIA","Albánie");
define("_ALBANIE","Albánie");
define("_ALGERIA","Alžírsko");
define("_AMERICAN_SAMOA","Americká Samoa");
define("_ANDORRA","Andorra");
define("_ANGOLA","Angola");
define("_ANGUILLA","Anguilla");
define("_ANTARCTICA","Antarktida");
define("_ANTIGUA_AND_BARBUDA","Antigua a Barbuda");
define("_ARGENTINA","Argentina");
define("_ARMENIA","Armenie");
define("_ARUBA","Aruba");
define("_AUSTRALIA","Austrálie");
define("_AUSTRIA","Rakousko");
define("_AZERBAIJAN","Azarbajdžán");
define("_BAHAMAS","Bahamy");
define("_BAHRAIN","Bahrain");
define("_BANGLADESH","Bangladéš");
define("_BARBADOS","Barbados");
define("_BELARUS","Bělorusko");
define("_BELGIE","Belgie");
define("_BELIZE","Belize");
define("_BENIN","Benin");
define("_BERMUDA","Bermudy");
define("_BHUTAN","Bhútán");
define("_BOLIVIA","Bolívie");
define("_BOSNA","Bosna a Hercegovina");
define("_BOTSWANA","Botswana");
define("_BOUVET_ISLAND","Bouvetův ostrov");
define("_BRAZIL","Brazílie");
define("_BRITISH_INDIAN_TERR","Britské indickooceánské teritorium");
define("_BRUNEI","Brunei");
define("_BULGARIA","Bulharsko");
define("_BURKINA_FASO","Burkina Faso");
define("_BURUNDI","Burundi");
define("_CAMBODIA","Kambodža");
define("_CAMEROON","Kamerun");
define("_CANADA","Kanada");
define("_CAPE_VERDE","Kapverdy");
define("_CAYMAN_ISLANDS","Kajmanské ostrovy");
define("_CENTRAL_AFRICA_REP","Středoafrická republika");
define("_CHAD","Čad");
define("_CHILE","Chile");
define("_CHINA","Čína");
define("_CHRISTMAS_ISLAND","Vánoční ostrov");
define("_COCOS_ISLANDS","Kokosové ostrovy");
define("_COLUMBIA","Kolumbie");
define("_COMOROS","Komory");
define("_CONGO","Kongo");
define("_CONGO_DPR","Demokratické Kongo");
define("_COOK_ISLANDS","Cookovy ostrovy");
define("_COSTA_RICA","Kostarika");
define("_IVORY_COAST","Pobřeží slonoviny");
define("_CROATIA","Chorvatsko");
define("_CUBA","Kuba");
define("_CYPRUS","Kypr");
define("_CZECH_REPUBLIC","Česká republika");
define("_DENMARK","Dánsko");
define("_DJIBOUTI","Džibuti");
define("_DOMINICA","Dominika");
define("_DOMINICAN_REPUBLIC","Dominikánská republika");
define("_EAST_TIMOR","Východní Timor");
define("_ECUADOR","Ekvádor");
define("_EGYPT","Egypt");
define("_EL_SALVADOR","Salvador");
define("_EQUATORIA_GUINEA","Rovníková Guinea");
define("_ERITREA","Eritrea");
define("_ESTONIA","Estonsko");
define("_ETHIOPIA","Etiopie");
define("_FALKLAND_ISLANDS","Falklandy / Malvíny");
define("_FAROE_ISLANDS","Faerské ostrovy");
define("_FIJI","Fidži");
define("_FINLAND","Finsko");
define("_FRANCE","Francie");
define("_FRENCH_GUIANA","Francouzská Guaiana");
define("_FRENCH_POLUNESIA","Francouzská Polynesie");
define("_FRENCH_SOUTHERN_TERR","Francouzské jižní teritorium");
define("_GABON","Gabon");
define("_GAMBIA","Gambie");
define("_GEORGIA","Gruzie");
define("_GERMANY","Německo");
define("_GHANA","Ghana");
define("_GIBRALTAR","Gibraltar");
define("_GREECE","Řecko");
define("_GREENLAND","Grónsko");
define("_GRENADA","Grenada");
define("_GUADELOUPE","Guadalupe");
define("_GUAM","Guam");
define("_GUATEMALA","Guatemala");
define("_GUINEA","Guinea");
define("_GUINEA_BISSAU","Guinea Bissau");
define("_GUYANA","Guayana");
define("_HAITI","Haiti");
define("_HEARD_AND_MCDONALD","Heardovy a McDonnaldovy ostrovy");
define("_HONDURAS","Honduras");
define("_HONG_KONG","Hong Kong");
define("_HUNGARY","Maďarsko");
define("_ICELAND","Island");
define("_INDIA","Indie");
define("_INDONESIA","Indonesie");
define("_IRAN","Islámská republika Írán");
define("_IRAQ","Irák");
define("_IRELAND","Irsko");
define("_ITALY","Itálie");
define("_ISRAEL","Izrael");
define("_JAMAICA","Jamajka");
define("_JAPAN","Japonsko");
define("_JORDAN","Jordánsko");
define("_KAZAKSTAN","Kazachstán");
define("_KENYA","Keňa");
define("_KIRIBATI","Kiribati");
define("_KOREA_REPUBLIC","Jižní Korea");
define("_KOREA_DPR","Severní Korea");
define("_KOSOVO","Kosovo");
define("_KUWAIT","Kuvait");
define("_KYRGYZSTAN","Kyrgyzstán");
define("_LAO","Lao");
define("_LATVIA","Lotyšsko");
define("_LEBANON","Libanon");
define("_LESOTHO","Lesotho");
define("_LIBERIA","Libérie");
define("_LYBIA","Lybie");
define("_LICHTENSTEIN","Lichtenštejnsko");
define("_LITHUANIA","Litva");
define("_LUXEMBOURG","Lucenbursko");
define("_MACAU","Macau");
define("_MACEDONIA","Makedonie");
define("_MADAGASCAR","Madagaskar");
define("_MALAWI","Maliwi");
define("_MALAYSIA","Malaisie");
define("_MALDIVES","Maledivy");
define("_MALI","Mali");
define("_MALTA","Malta");
define("_MARSHALL_ISLANDS","Marshallovy ostrovy");
define("_MARTINIQUE","Martinik");
define("_MAURITANIA","Mauretánie");
define("_MAURITIUS","Mauricius");
define("_MAYOTTE","Mayotte");
define("_MEXICO","Mexiko");
define("_MICRONESIA","Federované státy Mikronésie");
define("_MOLDOVA_REP","Moldávie");
define("_MONACO","Monako");
define("_MONGOLIA","Mongolsko");
define("_MONTENEGRO","Černá hora");
define("_MONTSERRAT","Monserrat");
define("_MOROCCO","Maroko");
define("_MOZAMBIQUE","Mozambik");
define("_MYANMAR","Myamar");
define("_NAMIBIA","Namíbie");
define("_NAURU","Nauru");
define("_NEPAL","Nepál");
define("_NETHERLANDS","Holandsko");
define("_NETHERLANDS_ANTILLES","Holandské Antilly");
define("_NEW_CALEDONIA","Nová Kaledonie");
define("_NEW_ZEALAND","Nový Zéland");
define("_NICARAGUA","Nikaragua");
define("_NIGER","Niger");
define("_NIGERIA","Nigérie");
define("_NIUE","Niue");
define("_NORFOLK_ISLANDS","Norfolkské ostrovy");
define("_NORTHERN_MARIANA_ISLANDS","Ostrovy severní Mariany");
define("_NORWAY","Norsko");
define("_OMAN","Omán");
define("_PAKISTAN","Pakistán");
define("_PALAU","Palau");
define("_PALESTINE","Palestina");
define("_PANAMA","Panama");
define("_PAPUA_NEW_GUINEA","Papua nová Guinea");
define("_PARAGUAY","Paraguay");
define("_PERU","Peru");
define("_PHILIPINES","Filipíny");
define("_PITCAIRN","Pitcairn");
define("_POLAND","Polsko");
define("_PORTUGAL","Portugalsko");
define("_PUERTO_RICO","Portoriko");
define("_QUATAR","Katar");
define("_REUNION","Reunion");
define("_ROMANIA","Rumunsko");
define("_RUSSIAN_FEDERATION","Ruská federace");
define("_RWANDA","Rwanda");
define("_SAINT_HELENA","Svatá Helena");
define("_SAINT_KITTS_AND_NEVIS","Svatý Kryštof a Nevis");
define("_SAINT_LUCIA","Svatá Lucie");
define("_SAINT_PIERRE_AND_MIQUELON","Saint Pierre and Miquelon");
define("_SAMOA","Samoa");
define("_SAN_MARINO","San Marino");
define("_SAINT_TOME_AND_PRINCIPE","Svatý Tomáš a Princův ostrov");
define("_SAUDI_ARABIA","Saudská arábie");
define("_SENEGAL","Senegal");
define("_SEYCHELLES","Seychely");
define("_SIERRA_LEONE","Siera Leone");
define("_SINGAPORE","Singapur");
define("_SLOVAKIA","Slovensko");
define("_SLOVENIA","Slovinkso");
define("_SOLOMON_ISLANDS","Šalamounovy ostrovy");
define("_SOMALIA","Somálsko");
define("_SOUTH_AFRICA","Jihoafrická republika");
define("_SOUTH_GEORGIA_SANDWICH_IS","Jižní Georgie a Jižní Sandwichovy ostrovy");
define("_SPAIN","Španělsko");
define("_SRI_LANKA","Srí Lanka");
define("_ST_VINCENT","Svatý Vincent a Grenadiny");
define("_SUDAN","Sůdán");
define("_SURINAME","Surinam");
define("_SVALBARD_AND_JAN_MAYEN","Špicberky a Jan Mayen");
define("_SWAZILAND","Svahilsko");
define("_SWEDEN","Švédsko");
define("_SWITZERLAND","Švýcarsko");
define("_SYRIAN_REPUBLIC","Sýrie");
define("_TAIWAN","Thaiwan");
define("_TAJIKISTAN","Tádžikistán");
define("_TANZANIA","Tanzánie");
define("_THAILAND","Thaisko");
define("_TOGO","Togo");
define("_TOKELAU","Tokelau");
define("_TONGA","Tonga");
define("_TRINIDAD_AND_TOBAGO","Trinidad a Tobago");
define("_TUNISIA","Tunis");
define("_TURKEY","Turecko");
define("_TURKMENISTAN","Turkmenistan");
define("_TURKS_AND_CAICOS_ISLANDS","Turks a Caicos");
define("_TUVALU","Tuvalu");
define("_UGANDA","Uganda");
define("_UKRAINE","Ukrajina");
define("_UNITED_ARAB_EMIRATES","Spojené arabské emiráty");
define("_UNITED_KINGDOM","Velká Británie");
define("_UNITED_STATES","USA");
define("_URUGUAY","Uruguay");
define("_US_MINOR_OUTLYING_ISLANDS","Americké menší ostrovy");
define("_UZBEKISTAN","Uzbekistán");
define("_VANUATU","Vanuatu");
define("_VATICAN_CITY","Vatikán");
define("_VENEZUELA","Venezuela");
define("_VIETNAM","Vietnam");
define("_VIRGIN_ISLANDS_BRITISH","Britské Panenské ostrovy");
define("_VIRGIN_ISLANDS_US","Americké Panenské ostrovy");
define("_WALLIS_AND_FUTUNA","Walisovy ostrovy");
define("_WESTERN_SAHARA","Západní Sahara");
define("_FLAG_WORLD","World");
define("_YEMEN","Jemen");
define("_SERBIA","Srbsko");
define("_ZAMBIA","Zambie");
define("_ZIMBABWE","Zimbabwe");