<?php
/***********************************************************************************************************
*
*		NAZEV VLAJKY
*
***********************************************************************************************************/
function NazevVlajky($flag,$flag_lang){
	
	global $eden_cfg;
	
	include_once($eden_cfg['www_dir_cms']."eden_lang_".$flag_lang.".php");
	
	if ($flag == "BALTIC"){return _BALTIC;}
	if ($flag == "ALPY"){return _ALPS;}
	if ($flag == "AMERIKA"){return _AMERICA;}
	if ($flag == "BENELUX"){return _BENELUX;}
	if ($flag == "SKANDINAVIE"){return _SKANDINAVIA;}
	if ($flag == "VYCHOD"){return _EAST;}
	if ($flag == "TIBET"){return _TIBET;}
	
	if ($flag == "01"){return _ALPS;}
	if ($flag == "02"){return _BALTIC;}
	if ($flag == "03"){return _AMERICA;}
	if ($flag == "04"){return _BENELUX;}
	if ($flag == "05"){return _SKANDINAVIA;}
	if ($flag == "06"){return _EAST;}
	if ($flag == "07"){return _TIBET;}
	if ($flag == "08"){return _SCOTLAND;}
	if ($flag == "09"){return _ENGLAND;}
	if ($flag == "10"){return _WAKE_ISLAND;}
	if ($flag == "11"){return _WALES;}
	if ($flag == "12"){return _NORTHERN_IRELAND;}
	if ($flag == "13"){return _NORTHERN_CYPRUS;}
	if ($flag == "14"){return _MIDWAY_ISLANDS;}
	if ($flag == "15"){return _JERSEY;}
	if ($flag == "16"){return _ISLE_OF_MAN;}
	if ($flag == "17"){return _FLAG_WORLD;}
	if ($flag == "18"){return _KOSOVO;}
	
	if ($flag == "EU"){return _EU;}
	
	if ($flag == "AF"){return _AFGHANISTAN;}
	if ($flag == "AL"){return _ALBANIA;}
	if ($flag == "DZ"){return _ALGERIA;}
	if ($flag == "AS"){return _AMERICAN_SAMOA;}
	if ($flag == "AD"){return _ANDORRA;}
	if ($flag == "AO"){return _ANGOLA;}
	if ($flag == "AI"){return _ANGUILLA;}
	if ($flag == "AQ"){return _ANTARCTICA;}
	if ($flag == "AG"){return _ANTIGUA_AND_BARBUDA;}
	if ($flag == "AR"){return _ARGENTINA;}
	if ($flag == "AM"){return _ARMENIA;}
	if ($flag == "AW"){return _ARUBA;}
	if ($flag == "AU"){return _AUSTRALIA;}
	if ($flag == "AT"){return _AUSTRIA;}
	if ($flag == "AZ"){return _AZERBAIJAN;}
	if ($flag == "BS"){return _BAHAMAS;}
	if ($flag == "BH"){return _BAHRAIN;}
	if ($flag == "BD"){return _BANGLADESH;}
	if ($flag == "BB"){return _BARBADOS;}
	if ($flag == "BY"){return _BELARUS;}
	if ($flag == "BE"){return _BELGIE;}
	if ($flag == "BZ"){return _BELIZE;}
	if ($flag == "BJ"){return _BENIN;}
	if ($flag == "BM"){return _BERMUDA;}
	if ($flag == "BT"){return _BHUTAN;}
	if ($flag == "BO"){return _BOLIVIA;}
	if ($flag == "BA"){return _BOSNA;}
	if ($flag == "BW"){return _BOTSWANA;}
	if ($flag == "BV"){return _BOUVET_ISLAND;}
	if ($flag == "BR"){return _BRAZIL;}
	if ($flag == "IO"){return _BRITISH_INDIAN_TERR;}
	if ($flag == "BN"){return _BRUNEI;}
	if ($flag == "BG"){return _BULGARIA;}
	if ($flag == "BF"){return _BURKINA_FASO;}
	if ($flag == "BI"){return _BURUNDI;}
	if ($flag == "KH"){return _CAMBODIA;}
	if ($flag == "CM"){return _CAMEROON;}
	if ($flag == "CA"){return _CANADA;}
	if ($flag == "CV"){return _CAPE_VERDE;}
	if ($flag == "KY"){return _CAYMAN_ISLANDS;}
	if ($flag == "CF"){return _CENTRAL_AFRICA_REP;}
	if ($flag == "TD"){return _CHAD;}
	if ($flag == "CL"){return _CHILE;}
	if ($flag == "CN"){return _CHINA;}
	if ($flag == "CX"){return _CHRISTMAS_ISLAND;}
	if ($flag == "CC"){return _COCOS_ISLANDS;}
	if ($flag == "CO"){return _COLUMBIA;}
	if ($flag == "KM"){return _COMOROS;}
	if ($flag == "CG"){return _CONGO;}
	if ($flag == "CD"){return _CONGO_DPR;}
	if ($flag == "CK"){return _COOK_ISLANDS;}
	if ($flag == "CR"){return _COSTA_RICA;}
	if ($flag == "CI"){return _IVORY_COAST;}
	if ($flag == "HR"){return _CROATIA;}
	if ($flag == "CU"){return _CUBA;}
	if ($flag == "CY"){return _CYPRUS;}
	if ($flag == "CZ"){return _CZECH_REPUBLIC;}
	if ($flag == "DK"){return _DENMARK;}
	if ($flag == "DJ"){return _DJIBOUTI;}
	if ($flag == "DM"){return _DOMINICA;}
	if ($flag == "DO"){return _DOMINICAN_REPUBLIC;}
	if ($flag == "TP"){return _EAST_TIMOR;}
	if ($flag == "EC"){return _ECUADOR;}
	if ($flag == "EG"){return _EGYPT;}
	if ($flag == "SV"){return _EL_SALVADOR;}
	if ($flag == "GQ"){return _EQUATORIA_GUINEA;}
	if ($flag == "ER"){return _ERITREA;}
	if ($flag == "EE"){return _ESTONIA;}
	if ($flag == "ET"){return _ETHIOPIA;}
	if ($flag == "FK"){return _FALKLAND_ISLANDS;}
	if ($flag == "FO"){return _FAROE_ISLANDS;}
	if ($flag == "FJ"){return _FIJI;}
	if ($flag == "FI"){return _FINLAND;}
	if ($flag == "FR"){return _FRANCE;}
	if ($flag == "GF"){return _FRENCH_GUIANA;}
	if ($flag == "PF"){return _FRENCH_POLUNESIA;}
	if ($flag == "TF"){return _FRENCH_SOUTHERN_TERR;}
	if ($flag == "GA"){return _GABON;}
	if ($flag == "GM"){return _GAMBIA;}
	if ($flag == "GE"){return _GEORGIA;}
	if ($flag == "DE"){return _GERMANY;}
	if ($flag == "GH"){return _GHANA;}
	if ($flag == "GI"){return _GIBRALTAR;}
	if ($flag == "GR"){return _GREECE;}
	if ($flag == "GL"){return _GREENLAND;}
	if ($flag == "GD"){return _GRENADA;}
	if ($flag == "GP"){return _GUADELOUPE;}
	if ($flag == "GU"){return _GUAM;}
	if ($flag == "GT"){return _GUATEMALA;}
	if ($flag == "GN"){return _GUINEA;}
	if ($flag == "GW"){return _GUINEA_BISSAU;}
	if ($flag == "GY"){return _GUYANA;}
	if ($flag == "HT"){return _HAITI;}
	if ($flag == "HM"){return _HEARD_AND_MCDONALD;}
	if ($flag == "HN"){return _HONDURAS;}
	if ($flag == "HK"){return _HONG_KONG;}
	if ($flag == "HU"){return _HUNGARY;}
	if ($flag == "IS"){return _ICELAND;}
	if ($flag == "IN"){return _INDIA;}
	if ($flag == "ID"){return _INDONESIA;}
	if ($flag == "IR"){return _IRAN;}
	if ($flag == "IQ"){return _IRAQ;}
	if ($flag == "IE"){return _IRELAND;}
	if ($flag == "IT"){return _ITALY;}
	if ($flag == "IL"){return _ISRAEL;}
	if ($flag == "JM"){return _JAMAICA;}
	if ($flag == "JP"){return _JAPAN;}
	if ($flag == "JO"){return _JORDAN;}
	if ($flag == "KZ"){return _KAZAKSTAN;}
	if ($flag == "KE"){return _KENYA;}
	if ($flag == "KI"){return _KIRIBATI;}
	if ($flag == "KR"){return _KOREA_REPUBLIC;}
	if ($flag == "KP"){return _KOREA_DPR;}
	if ($flag == "KW"){return _KUWAIT;}
	if ($flag == "KG"){return _KYRGYZSTAN;}
	if ($flag == "LA"){return _LAO;}
	if ($flag == "LV"){return _LATVIA;}
	if ($flag == "LB"){return _LEBANON;}
	if ($flag == "LS"){return _LESOTHO;}
	if ($flag == "LR"){return _LIBERIA;}
	if ($flag == "LY"){return _LYBIA;}
	if ($flag == "LI"){return _LICHTENSTEIN;}
	if ($flag == "LT"){return _LITHUANIA;}
	if ($flag == "LU"){return _LUXEMBOURG;}
	if ($flag == "MO"){return _MACAU;}
	if ($flag == "MK"){return _MACEDONIA;}
	if ($flag == "MG"){return _MADAGASCAR;}
	if ($flag == "MW"){return _MALAWI;}
	if ($flag == "MY"){return _MALAYSIA;}
	if ($flag == "MV"){return _MALDIVES;}
	if ($flag == "ML"){return _MALI;}
	if ($flag == "MT"){return _MALTA;}
	if ($flag == "MH"){return _MARSHALL_ISLANDS;}
	if ($flag == "MQ"){return _MARTINIQUE;}
	if ($flag == "MR"){return _MAURITANIA;}
	if ($flag == "MU"){return _MAURITIUS;}
	if ($flag == "YT"){return _MAYOTTE;}
	if ($flag == "MX"){return _MEXICO;}
	if ($flag == "FM"){return _MICRONESIA;}
	if ($flag == "MD"){return _MOLDOVA_REP;}
	if ($flag == "MC"){return _MONACO;}
	if ($flag == "MN"){return _MONGOLIA;}
	if ($flag == "ME"){return _MONTENEGRO;}
	if ($flag == "MS"){return _MONTSERRAT;}
	if ($flag == "MA"){return _MOROCCO;}
	if ($flag == "MZ"){return _MOZAMBIQUE;}
	if ($flag == "MM"){return _MYANMAR;}
	if ($flag == "NA"){return _NAMIBIA;}
	if ($flag == "NR"){return _NAURU;}
	if ($flag == "NP"){return _NEPAL;}
	if ($flag == "NL"){return _NETHERLANDS;}
	if ($flag == "AN"){return _NETHERLANDS_ANTILLES;}
	if ($flag == "NC"){return _NEW_CALEDONIA;}
	if ($flag == "NZ"){return _NEW_ZEALAND;}
	if ($flag == "NI"){return _NICARAGUA;}
	if ($flag == "NE"){return _NIGER;}
	if ($flag == "NG"){return _NIGERIA;}
	if ($flag == "NU"){return _NIUE;}
	if ($flag == "NF"){return _NORFOLK_ISLANDS;}
	if ($flag == "MP"){return _NORTHERN_MARIANA_ISLANDS;}
	if ($flag == "NO"){return _NORWAY;}
	if ($flag == "OM"){return _OMAN;}
	if ($flag == "PK"){return _PAKISTAN;}
	if ($flag == "PW"){return _PALAU;}
	if ($flag == "PS"){return _PALESTINE;}
	if ($flag == "PA"){return _PANAMA;}
	if ($flag == "PG"){return _PAPUA_NEW_GUINEA;}
	if ($flag == "PY"){return _PARAGUAY;}
	if ($flag == "PE"){return _PERU;}
	if ($flag == "PH"){return _PHILIPINES;}
	if ($flag == "PN"){return _PITCAIRN;}
	if ($flag == "PL"){return _POLAND;}
	if ($flag == "PT"){return _PORTUGAL;}
	if ($flag == "PR"){return _PUERTO_RICO;}
	if ($flag == "QA"){return _QUATAR;}
	if ($flag == "RE"){return _REUNION;}
	if ($flag == "RO"){return _ROMANIA;}
	if ($flag == "RU"){return _RUSSIAN_FEDERATION;}
	if ($flag == "RW"){return _RWANDA;}
	if ($flag == "SH"){return _SAINT_HELENA;}
	if ($flag == "KN"){return _SAINT_KITTS_AND_NEVIS;}
	if ($flag == "LC"){return _SAINT_LUCIA;}
	if ($flag == "PM"){return _SAINT_PIERRE_AND_MIQUELON;}
	if ($flag == "WS"){return _SAMOA;}
	if ($flag == "SM"){return _SAN_MARINO;}
	if ($flag == "ST"){return _SAINT_TOME_AND_PRINCIPE;}
	if ($flag == "SA"){return _SAUDI_ARABIA;}
	if ($flag == "SN"){return _SENEGAL;}
	if ($flag == "RS"){return _SERBIA;}
	if ($flag == "SC"){return _SEYCHELLES;}
	if ($flag == "SL"){return _SIERRA_LEONE;}
	if ($flag == "SG"){return _SINGAPORE;}
	if ($flag == "SK"){return _SLOVAKIA;}
	if ($flag == "SI"){return _SLOVENIA;}
	if ($flag == "SB"){return _SOLOMON_ISLANDS;}
	if ($flag == "SO"){return _SOMALIA;}
	if ($flag == "ZA"){return _SOUTH_AFRICA;}
	if ($flag == "GS"){return _SOUTH_GEORGIA_SANDWICH_IS;}
	if ($flag == "ES"){return _SPAIN;}
	if ($flag == "LK"){return _SRI_LANKA;}
	if ($flag == "VC"){return _ST_VINCENT;}
	if ($flag == "SD"){return _SUDAN;}
	if ($flag == "SR"){return _SURINAME;}
	if ($flag == "SJ"){return _SVALBARD_AND_JAN_MAYEN;}
	if ($flag == "SZ"){return _SWAZILAND;}
	if ($flag == "SE"){return _SWEDEN;}
	if ($flag == "CH"){return _SWITZERLAND;}
	if ($flag == "SY"){return _SYRIAN_REPUBLIC;}
	if ($flag == "TW"){return _TAIWAN;}
	if ($flag == "TJ"){return _TAJIKISTAN;}
	if ($flag == "TZ"){return _TANZANIA;}
	if ($flag == "TH"){return _THAILAND;}
	if ($flag == "TG"){return _TOGO;}
	if ($flag == "TK"){return _TOKELAU;}
	if ($flag == "TO"){return _TONGA;}
	if ($flag == "TT"){return _TRINIDAD_AND_TOBAGO;}
	if ($flag == "TN"){return _TUNISIA;}
	if ($flag == "TR"){return _TURKEY;}
	if ($flag == "TM"){return _TURKMENISTAN;}
	if ($flag == "TC"){return _TURKS_AND_CAICOS_ISLANDS;}
	if ($flag == "TV"){return _TUVALU;}
	if ($flag == "UG"){return _UGANDA;}
	if ($flag == "UA"){return _UKRAINE;}
	if ($flag == "AE"){return _UNITED_ARAB_EMIRATES;}
	if ($flag == "GB"){return _UNITED_KINGDOM;}
	if ($flag == "US"){return _UNITED_STATES;}
	if ($flag == "UY"){return _URUGUAY;}
	if ($flag == "UM"){return _US_MINOR_OUTLYING_ISLANDS;}
	if ($flag == "UZ"){return _UZBEKISTAN;}
	if ($flag == "VU"){return _VANUATU;}
	if ($flag == "VA"){return _VATICAN_CITY;}
	if ($flag == "VE"){return _VENEZUELA;}
	if ($flag == "VN"){return _VIETNAM;}
	if ($flag == "VG"){return _VIRGIN_ISLANDS_BRITISH;}
	if ($flag == "VI"){return _VIRGIN_ISLANDS_US;}
	if ($flag == "WF"){return _WALLIS_AND_FUTUNA;}
	if ($flag == "EH"){return _WESTERN_SAHARA;}
	if ($flag == "YE"){return _YEMEN;}
	if ($flag == "YU"){return _SERBIA;}
	if ($flag == "ZM"){return _ZAMBIA;}
	if ($flag == "ZW"){return _ZIMBABWE;}
	// Stare rozvrzeni
	if ($flag == "ALBANIE"){return _ALBANIA;}
	if ($flag == "ARGENTINA"){return _ARGENTINA;}
	if ($flag == "BOSNA"){return _BOSNA;}
	if ($flag == "BELGIE"){return _BELGIE;}
	if ($flag == "BELORUSKO"){return _BELARUS;}
	if ($flag == "BRAZILIE"){return _BRAZIL;}
	if ($flag == "BULHARSKO"){return _BULGARIA;}
	if ($flag == "CESKO"){return _CZECH_REPUBLIC;}
	if ($flag == "CINA"){return _CHINA;}
	if ($flag == "COLUMBIE"){return _COLOMBIA;}
	if ($flag == "DANSKO"){return _DENMARK;}
	if ($flag == "ENGLAND"){return _UNITED_KINGDOM;}
	if ($flag == "ESTONSKO"){return _ESTONIA;}
	if ($flag == "FILIPINY"){return _PHILIPINES;}
	if ($flag == "FINSKO"){return _FINLAND;}
	if ($flag == "FRANCIE"){return _FRANCE;}
	if ($flag == "HOLANDSKO"){return _NETHERLAND;}
	if ($flag == "CHILE"){return _CHILE;}
	if ($flag == "CHORVATSKO"){return _CROATIA;}
	if ($flag == "INDIE"){return _INDIA;}
	if ($flag == "INDONESIE"){return _INDONESIA;}
	if ($flag == "IRAK"){return _IRAQ;}
	if ($flag == "IRAN"){return _IRAN;}
	if ($flag == "IRSKO"){return _IRELAND;}
	if ($flag == "ISLAND"){return _ICELAND;}
	if ($flag == "ITALIE"){return _ITALY;}
	if ($flag == "IZRAEL"){return _ISRAEL;}
	if ($flag == "JAPONSKO"){return _JAPAN;}
	if ($flag == "KANADA"){return _CKANADA;}
	if ($flag == "KOREA"){return _KOREA_REPUBLIC;}
	if ($flag == "KYPR"){return _CYPRUS;}
	if ($flag == "LITVA"){return _LITHUANIA;}
	if ($flag == "MADARSKO"){return _HUNGARY;}
	if ($flag == "MALAISIE"){return _MALAISIA;}
	if ($flag == "MALTA"){return _MALTA;}
	if ($flag == "MAROKO"){return _MOROCCO;}
	if ($flag == "MEXIKO"){return _MEXICO;}
	if ($flag == "MOLDAVSKO"){return _MOLDAVIA;}
	if ($flag == "MONGOLSKO"){return _MONGOLIA;}
	if ($flag == "NEMECKO"){return _GERMANY;}
	if ($flag == "NORSKO"){return _NORWAY;}
	if ($flag == "NOVYZELAND"){return _NEW_ZEALAND;}
	if ($flag == "PERU"){return _PERU;}
	if ($flag == "POLSKO"){return _POLAND;}
	if ($flag == "PORTUGALSKO"){return _PORTUGAL;}
	if ($flag == "RAKOUSKO"){return _AUSTRIA;}
	if ($flag == "RECKO"){return _GREECE;}
	if ($flag == "RUMUNSKO"){return _ROMANIA;}
	if ($flag == "RUSKO"){return _RUSSIAN_FEDERATION;}
	if ($flag == "SEICHILY"){return _SEYCHELLES;}
	if ($flag == "SINGAPUR"){return _SINGAPORE;}
	if ($flag == "SLOVENSKO"){return _SLOVAKIA;}
	if ($flag == "SLOVINSKO"){return _SLOVENIA;}
	if ($flag == "SPANELSKO"){return _SPAIN;}
	if ($flag == "SRBSKO"){return _SERBIA;}
	if ($flag == "STREDOAFRICKA"){return _CENTRAL_AFRICA_REP;}
	if ($flag == "SVEDSKO"){return _SWEDEN;}
	if ($flag == "SVYCARSKO"){return SWITZERLAND;}
	if ($flag == "SYRIE"){return _SYRIA;}
	if ($flag == "TAIWAN"){return _TAIWAN;}
	if ($flag == "TIBET"){return _TIBET;}
	if ($flag == "TUNIS"){return _TUNISIA;}
	if ($flag == "TURECKO"){return _TURKEY;}
	if ($flag == "UKRAINA"){return _UKRAINE;}
	if ($flag == "URUGUAY"){return _URUGUAY;}
	if ($flag == "USA"){return _UNITED_STATES;}
	if ($flag == "VENEZUELA"){return _VENEZUELA;}
}