<?php
/***********************************************************************************************************
*																											
*			SETUP																							
*																											
***********************************************************************************************************/
function Setup(){
	
	global $db_setup,$db_setup_lang,$db_setup_images,$db_language,$db_country;
	global $eden_cfg;
	global $url_project_images;
	global $ftp_path_project_images;
	
	// Zabezpeceni, ze kdyz nekdo opusti novinky bez ulozeni, tak se odstrani jeho jmeno z kolonky uzivatele, ktery ma zaznam otevren
	KillUse($_SESSION['loginid']);
	
	if (CheckPriv("groups_setup_edit") <> 1) { echo _NOTENOUGHPRIV;exit;}
	
	$res = mysql_query("SELECT s.*, sl.* FROM $db_setup AS s, $db_setup_lang AS sl WHERE sl.setup_lang='".mysql_real_escape_string($_SESSION['web_lang'])."'") or die ("<strong>File:</strong> ".__FILE__."<br /><strong>Line:</strong>".__LINE__."<br />".mysql_error());
	$ar = mysql_fetch_array($res);
	$res_img = mysql_query("SELECT * FROM $db_setup_images") or die ("<strong>File:</strong> ".__FILE__."<br /><strong>Line:</strong>".__LINE__."<br />".mysql_error());
	$i=0;
	// Nastavime promenne do pole
	while ($ar_img = mysql_fetch_array($res_img)){
		$setup_images[$ar_img[1]] = $ar_img;
		$i++;
	}
	
	echo "<script src=\"./js/tab-contentdivider.js\" type=\"text/javascript\"></script>\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr>\n";
	echo "		<td align=\"left\" class=\"nadpis\">"._SETUP."<br><br></td>\n";
	echo "	</tr>\n";
	// Zobrazeni chyb a hlasek systemu
	if ($_GET['msg']){
		echo "<tr><td style=\"color:#ff0000;padding:10px 0px 10px 10px;font-weight:bold;\">".SysMsg($_GET['msg'])."</td></tr>\n";
	}
	echo "</table>\n";
	echo "<form action=\"sys_save.php?action=sys_setup\" method=\"post\" name=\"form1\" enctype=\"multipart/form-data\">";
	echo "<div id=\"cyclelinks\"></div>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_1\" class=\"nadpis_sekce\">"._SETUP_BASIC."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_BASIC_DOCTYPE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><select  name=\"setup_basic_doctype\" class=\"input\">\n";
	echo "			<option value=\"1\" "; if ($ar['setup_basic_doctype'] == 1){echo "selected=\"selected\"";} echo ">HTML 4.01 Transitional (default)</option>\n";
	echo "			<option value=\"2\" "; if ($ar['setup_basic_doctype'] == 2){echo "selected=\"selected\"";} echo ">HTML 4.01 Strict</option>\n";
	echo "			<option value=\"3\" "; if ($ar['setup_basic_doctype'] == 3){echo "selected=\"selected\"";} echo ">XHTML 1.0 Transitional</option>\n";
	echo "			<option value=\"4\" "; if ($ar['setup_basic_doctype'] == 4){echo "selected=\"selected\"";} echo ">XHTML 1.0 Strict</option>";
	echo "			<option value=\"5\" "; if ($ar['setup_basic_doctype'] == 5){echo "selected=\"selected\"";} echo ">XHTML 1.1</option>";
	echo "		</select></td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\">\n";
	echo "	<td width=\"250\" align=\"right\"><br><strong>"._SETUP_BASIC_MAILER."</strong></td>\n";
	echo "	<td width=\"500\" align=\"left\"><br><select name=\"setup_reg_mailer\" class=\"input\">\n";
	echo "		<option value=\"mail\" "; if ($ar['setup_reg_mailer'] == "mail"){echo "selected=\"selected\"";} echo ">Mail</option>\n";
	echo "		<option value=\"sendmail\" "; if ($ar['setup_reg_mailer'] == "sendmail"){echo "selected=\"selected\"";} echo ">SendMail</option>\n";
	echo "		<option value=\"smtp\" "; if ($ar['setup_reg_mailer'] == "smtp"){echo "selected=\"selected\"";} echo ">SMTP</option>\n";
	echo "		</select></td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\">\n";
	echo "	<td width=\"250\" align=\"right\"><br><strong>"._SETUP_BASIC_CONTACT_FORM_EMAIL."</strong></td>\n";
	echo "	<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_contact_form_from']."\" name=\"setup_contact_form_from\" size=\"30\" maxlength=\"50\"></td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\">\n";
	echo "	<td width=\"250\" align=\"right\"><br><strong>"._SETUP_BASIC_CONTACT_FORM_SUBJECT."</strong></td>\n";
	echo "	<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_lang_contact_form_subject']."\" name=\"setup_lang_contact_form_subject\" size=\"80\" maxlength=\"100\"></td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\">\n";
	echo "	<td width=\"250\" align=\"right\"><br><strong>"._SETUP_EDEN_DOBA."</strong></td>\n";
	echo "	<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_eden_joining_time']."\" name=\"setup_eden_joining_time\" size=\"4\" maxlength=\"5\"></td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "	<td width=\"850\" colspan=\"2\"><span class=\"nadpis_sekce\">"._SETUP_LANGUAGES."</span><br></td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\">\n";
	echo "	<td width=\"250\" align=\"right\"><strong>"._SETUP_BASIC_COUNTRY."</strong><br></td>\n";
	echo "	<td width=\"500\" align=\"left\">\n";
				$res_country = mysql_query("SELECT country_shortname, country_name FROM $db_country") or die ("<strong>File:</strong> ".__FILE__."<br /><strong>Line:</strong>".__LINE__."<br />".mysql_error());
				$num_country = mysql_num_rows($res_country);
				if($num_country > 1){
					echo "<select name=\"setup_basic_country\" class=\"input\">\n";
					while ($ar_country = mysql_fetch_array($res_country)){
						echo "<option value=\"".$ar_country['country_shortname']."\"";
						if ($ar_country['country_shortname'] == $ar['setup_basic_country']){echo "selected=\"selected\"";}
						echo ">".$ar_country['country_name']."</option>\n";
					}
					echo "</select>\n";
				} else {
					$ar_country = mysql_fetch_array($res_country);
					echo $ar_country['country_name'];
					echo "<input type=\"hidden\" name=\"setup_basic_country\"  value=\"".$ar_country['country_shortname']."\">\n";
				}
	echo "	</td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\">\n";
	echo "	<td width=\"250\" align=\"right\"><strong>"._SETUP_BASIC_LANGUAGE."</strong><br></td>\n";
	echo "	<td width=\"500\" align=\"left\">";
		$res_lng = mysql_query("SELECT language_code, language_name FROM $db_language") or die ("<strong>File:</strong> ".__FILE__."<br /><strong>Line:</strong>".__LINE__."<br />".mysql_error());
		$num_lng = mysql_num_rows($res_lng);
		if($num_lng > 1){
			echo "<select name=\"setup_basic_lang\" class=\"input\">";
			while ($ar_lng = mysql_fetch_array($res_lng)){
				echo "<option value=\"".$ar_lng['language_code']."\""; 
				if ($ar_lng['language_code'] == $ar['setup_basic_lang']){echo "selected=\"selected\"";}
				echo ">".$ar_lng['language_name']."</option>";
			}
			echo "</select>";
		} else {
			$ar_lng = mysql_fetch_array($res_lng);
			echo $ar_lng['language_name'];
			echo "<input type=\"hidden\" name=\"setup_basic_lang\" value=\"".$ar_lng['language_code']."\">";
		}
	echo "	</td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "	<td width=\"850\" colspan=\"2\"><span class=\"nadpis_sekce\">"._SETUP_WEB."</span><br></td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\">\n";
	echo "	<td width=\"250\" align=\"right\"><br><strong>"._SETUP_BASIC_DATE."</strong></td>\n";
	echo "	<td width=\"500\" align=\"left\"><br>";
		if ($ar['setup_basic_date'] == "1990-01-01 00:00:00"){
			$dateon = formatTimeS(time());
			$setup_basic_date = $dateon[1].".".$dateon[2].".".$dateon[3];
		} else {
			$setup_basic_date = FormatDatetime($ar['setup_basic_date'],"d.m.Y H:i:s");
		}
	echo "		<script language=\"javascript\">\n";
	echo "		var StartDate = new ctlSpiffyCalendarBox(\"StartDate\", \"form1\", \"setup_basic_date\", \"btnDate1\",\"".$setup_basic_date."\",scBTNMODE_CUSTOMBLUE);\n";
	echo "		</script>\n";
	echo "		<script language=\"javascript\">StartDate.writeControl(); StartDate.dateFormat=\"dd.MM.yyyy\";</script>\n";
	echo "	</td>\n";
	echo "</tr>\n";
	echo "<tr align=\"left\" valign=\"top\">\n";
	echo "	<td width=\"250\" align=\"right\"><strong>"._SETUP_TIMEZONE."</strong></td>\n";
	echo "	<td width=\"500\" align=\"left\"><select name=\"setup_basic_timezone\" class=\"input\">";
	echo "		<option value=\"-1200\" "; if ($ar['setup_basic_timezone'] == "-1200"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M1200."</option>\n";
	echo "		<option value=\"-1100\" "; if ($ar['setup_basic_timezone'] == "-1100"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M1100."</option>\n";
	echo "		<option value=\"-1000\" "; if ($ar['setup_basic_timezone'] == "-1000"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M1000."</option>\n";
	echo "		<option value=\"-0900\" "; if ($ar['setup_basic_timezone'] == "-0900"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0900."</option>\n";
	echo "		<option value=\"-0800\" "; if ($ar['setup_basic_timezone'] == "-0800"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0800."</option>\n";
	echo "		<option value=\"-0700\" "; if ($ar['setup_basic_timezone'] == "-0700"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0700."</option>\n";
	echo "	   	<option value=\"-0600\" "; if ($ar['setup_basic_timezone'] == "-0600"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0600."</option>\n";
	echo "		<option value=\"-0500\" "; if ($ar['setup_basic_timezone'] == "-0500"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0500."</option>\n";
	echo "		<option value=\"-0430\" "; if ($ar['setup_basic_timezone'] == "-0430"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0430."</option>\n";
	echo "		<option value=\"-0400\" "; if ($ar['setup_basic_timezone'] == "-0400"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0400."</option>\n";
	echo "		<option value=\"-0330\" "; if ($ar['setup_basic_timezone'] == "-0330"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0330."</option>\n";
	echo "		<option value=\"-0300\" "; if ($ar['setup_basic_timezone'] == "-0300"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0300."</option>\n";
	echo "		<option value=\"-0200\" "; if ($ar['setup_basic_timezone'] == "-0200"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0200."</option>\n";
	echo "		<option value=\"-0100\" "; if ($ar['setup_basic_timezone'] == "-0100"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_M0100."</option>\n";
	echo "	   	<option value=\"GMT\" "; if ($ar['setup_basic_timezone'] == "GMT"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_GMT."</option>\n";
	echo "		<option value=\"+0100\" "; if ($ar['setup_basic_timezone'] == "+0100" || $ar['setup_basic_timezone'] == ""){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0100."</option>\n";
	echo "		<option value=\"+0200\" "; if ($ar['setup_basic_timezone'] == "+0200"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0200."</option>\n";
	echo "		<option value=\"+0300\" "; if ($ar['setup_basic_timezone'] == "+0300"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0300."</option>\n";
	echo "		<option value=\"+0330\" "; if ($ar['setup_basic_timezone'] == "+0330"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0330."</option>\n";
	echo "		<option value=\"+0400\" "; if ($ar['setup_basic_timezone'] == "+0400"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0400."</option>\n";
	echo "		<option value=\"+0430\" "; if ($ar['setup_basic_timezone'] == "+0430"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0430."</option>\n";
	echo "		<option value=\"+0500\" "; if ($ar['setup_basic_timezone'] == "+0500"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0500."</option>\n";
	echo "		<option value=\"+0530\" "; if ($ar['setup_basic_timezone'] == "+0530"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0530."</option>\n";
	echo "		<option value=\"+0545\" "; if ($ar['setup_basic_timezone'] == "+0545"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0545."</option>\n";
	echo "		<option value=\"+0600\" "; if ($ar['setup_basic_timezone'] == "+0600"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0600."</option>\n";
	echo "		<option value=\"+0630\" "; if ($ar['setup_basic_timezone'] == "+0630"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0630."</option>\n";
	echo "		<option value=\"+0700\" "; if ($ar['setup_basic_timezone'] == "+0700"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0700."</option>\n";
	echo "		<option value=\"+0800\" "; if ($ar['setup_basic_timezone'] == "+0800"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0800."</option>\n";
	echo "		<option value=\"+0900\" "; if ($ar['setup_basic_timezone'] == "+0900"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0900."</option>\n";
	echo "		<option value=\"+0930\" "; if ($ar['setup_basic_timezone'] == "+0930"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P0930."</option>\n";
	echo "		<option value=\"+1000\" "; if ($ar['setup_basic_timezone'] == "+1000"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P1000."</option>\n";
	echo "		<option value=\"+1100\" "; if ($ar['setup_basic_timezone'] == "+1100"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P1100."</option>\n";
	echo "		<option value=\"+1200\" "; if ($ar['setup_basic_timezone'] == "+1200"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P1200."</option>\n";
	echo "		<option value=\"+1300\" "; if ($ar['setup_basic_timezone'] == "+1300"){echo "selected=\"selected\"";} echo ">"._SETUP_TIMEZONE_P1300."</option>\n";
	echo "		</select></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_BAN_TEXT."</strong><br><input name=\"setup_lang_ban_text_checkbox\" type=\"checkbox\" value=\"1\"></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><textarea cols=\"70\" rows=\"15\" name=\"setup_lang_ban_text\">".$ar['setup_lang_ban_text']."</textarea></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_BAN_COLOR."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\" bgcolor=\"".$ar['setup_ban_color']."\"><br><input type=\"text\" value=\"".$ar['setup_ban_color']."\" name=\"setup_ban_color\" size=\"5\" maxlength=\"6\"></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_2\" class=\"nadpis_sekce\">"._SETUP_ARTICLES."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ARTICLES_IMG_1_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['article_1'][2]."\" name=\"setup_article_img_1_width\" size=\"3\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ARTICLES_IMG_1_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['article_1'][3]."\" name=\"setup_article_img_1_height\" size=\"3\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ARTICLES_IMG_2_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['article_2'][2]."\" name=\"setup_article_img_2_width\" size=\"3\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ARTICLES_IMG_2_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['article_2'][3]."\" name=\"setup_article_img_2_height\" size=\"3\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ARTICLES_COUNT." 1:</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_article_number']."\" name=\"setup_article_number\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ARTICLES_COUNT." 2:</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_article_number_2']."\" name=\"setup_article_number_2\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ARTICLES_ARCHIV."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_article_archive']."\" name=\"setup_article_archive\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ARTICLES_TOPN_ARCHIV."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_top_article_archive']."\" name=\"setup_top_article_archive\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ACT_COUNT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_news_number']."\" name=\"setup_news_number\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ACT_ARCHIV."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_news_archive']."\" name=\"setup_news_archive\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_ACT_ARCHIV_START."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_news_archivation_start']."\" name=\"setup_news_archivation_start\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TOP_ARTICLE_MOD."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_top_article_mod'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_top_article_mod\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ARTICLES_SHOW_BEST."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_article_show_best_article'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_article_show_best_article\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\">"._SETUP_SHOW_AUTHOR_NICKNAME."</td>\n";
	echo "		<td width=\"500\" align=\"left\"><select name=\"setup_show_author_nick\" class=\"input\">\n";
	echo "		<option value=\"1\" "; if ($ar['setup_show_author_nick'] == "1"){echo "selected=\"selected\"";} echo " >"._SETUP_SHOW_AUTHOR_NICK."</option>\n";
	echo "		<option value=\"2\" "; if ($ar['setup_show_author_nick'] == "2"){echo "selected=\"selected\"";} echo " >"._SETUP_SHOW_AUTHOR_NAME."</option>\n";
	echo "		</select></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ARTICLES_START_ARCHIV."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$ar['setup_article_archivation_start']."\" name=\"setup_article_archivation_start\" size=\"7\" maxlength=\"6\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span class=\"nadpis_sekce\">"._SETUP_EDITOR."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_EDITOR_CLEANER."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_eden_editor_cleaner'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_eden_editor_cleaner\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_EDITOR_PURIFICATOR."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_eden_editor_purificator'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_eden_editor_purificator\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_3\" class=\"nadpis_sekce\">"._SETUP_ADDS."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ADDS_IN_COMM."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$ar['setup_adds_in_com']."\" size=\"2\" maxlength=\"2\" name=\"setup_adds_in_com\">"._SETUP_ADDS_IN_COMM2."</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ADDS_IN_COMM_ID."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$ar['setup_adds_in_com_id']."\" size=\"2\" maxlength=\"2\" name=\"setup_adds_in_com_id\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_4\" class=\"nadpis_sekce\">"._SETUP_ADMIN."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ADMIN_SHOW_CONTACT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_admin_show_contact'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_admin_show_contact\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ADMIN_SHOW_CONTACT_SHOP."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_admin_show_contact_shop'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_admin_show_contact_shop\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ADMIN_SHOW_CLAN."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_admin_show_clan'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_admin_show_clan\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ADMIN_SHOW_GAME."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_admin_show_game'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_admin_show_game\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ADMIN_SHOW_HW."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_admin_show_hw'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_admin_show_hw\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ADMIN_SHOW_INFO."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_admin_show_info'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_admin_show_info\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ADMIN_SHOW_POKER."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_admin_show_poker'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_admin_show_poker\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span class=\"nadpis_sekce\">"._SETUP_REG."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br>"._SETUP_REG_ADMIN_NICK."<br><br></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input name=\"setup_reg_admin_nick\" type=\"checkbox\" value=\"1\" "; if ($ar['setup_reg_admin_nick'] == 1){echo "checked";} echo "></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_REG_EMAIL."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><select name=\"setup_reg_over_email\" class=\"input\">\n";
	echo "		<option value=\"0\" "; if ($ar['setup_reg_over_email'] == "0"){echo "selected=\"selected\"";} echo " >"._SETUP_REG_EMAIL_NO."</option>\n";
	echo "		<option value=\"1\" "; if ($ar['setup_reg_over_email'] == "1"){echo "selected=\"selected\"";} echo " >"._SETUP_REG_EMAIL_YES."</option>\n";
	echo "		<option value=\"2\" "; if ($ar['setup_reg_over_email'] == "2"){echo "selected=\"selected\"";} echo " >"._SETUP_REG_EMAIL_ADMIN."</option>\n";
	echo "		</select>\n";
	echo "		<!-- <input type=\"checkbox\" "; if ($ar['setup_reg_over_email'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_reg_over_email\"> --></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_REG_AGREEMENT."</strong><br></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input name=\"setup_reg_agreement\" type=\"checkbox\" value=\"1\" "; if ($ar['setup_reg_agreement'] == 1){echo "checked";} echo "></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_REG_HELP."</strong><br><input name=\"setup_lang_reg_help_checkbox\" type=\"checkbox\" value=\"1\"></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><textarea cols=\"70\" rows=\"15\" name=\"setup_lang_reg_help\">".$ar['setup_lang_reg_help']."</textarea></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_REG_TERMS."</strong><br><input name=\"setup_lang_reg_terms_checkbox\" type=\"checkbox\" value=\"1\"></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><textarea cols=\"70\" rows=\"15\" name=\"setup_lang_reg_terms\">".$ar['setup_lang_reg_terms']."</textarea></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_REG_SUBJ."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_lang_reg_subject']."\" size=\"80\" maxlength=\"100\" name=\"setup_lang_reg_subject\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br>"._SETUP_REG_TEXT."<br><input name=\"setup_lang_reg_text_checkbox\" type=\"checkbox\" value=\"1\"></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><textarea cols=\"70\" rows=\"15\" name=\"setup_lang_reg_text\">".$ar['setup_lang_reg_text']."</textarea></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_REG_FROM."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_reg_from']."\" name=\"setup_reg_from\" size=\"30\" maxlength=\"50\"> "._SETUP_REG_FROM_ADMIN."</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_REG_FROM_NAME."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_reg_from_name']."\" name=\"setup_reg_from_name\" size=\"30\" maxlength=\"50\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_FORGPASS_SUBJ."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_lang_forgpass_subject']."\" size=\"80\" maxlength=\"100\" name=\"setup_lang_forgpass_subject\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_FORGPASS_TEXT."</strong><br><input name=\"setup_lang_forgpass_text_checkbox\" type=\"checkbox\" value=\"1\"></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><textarea cols=\"70\" rows=\"15\" name=\"setup_lang_forgpass_text\">".$ar['setup_lang_forgpass_text']."</textarea></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span class=\"nadpis_sekce\">"._SETUP_CHANGES."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_CHANGES_CHANGE_EMAIL_SUBJ."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_lang_change_subject']."\" size=\"80\" maxlength=\"100\" name=\"setup_lang_change_subject\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_CHANGES_CHANGE_EMAIL."</strong><br><input name=\"setup_lang_change_email_checkbox\" type=\"checkbox\" value=\"1\"><br><br>\n";
	echo "		[{admin_uname}]<br>\n";
	echo "		[{setup_changes_old_email}]<br>\n";
	echo "		[{setup_changes_new_email}]<br>\n";
	echo "		</td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><textarea cols=\"70\" rows=\"15\" name=\"setup_lang_change_email\">".$ar['setup_lang_change_email']."</textarea></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_CHANGES_CHANGED_EMAIL_SUBJ."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_lang_changed_subject']."\" size=\"80\" maxlength=\"100\" name=\"setup_lang_changed_subject\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_CHANGES_CHANGED_EMAIL."</strong><br><input name=\"setup_lang_changed_email_checkbox\" type=\"checkbox\" value=\"1\"><br><br>\n";
	echo "		[{admin_uname}]<br>\n";
	echo "		[{admin_new_email}]<br>\n";
	echo "		[{admin_old_email}]<br>\n";
	echo "		</td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><textarea cols=\"70\" rows=\"15\" name=\"setup_lang_changed_email\">".$ar['setup_lang_changed_email']."</textarea></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span  id=\"tab_5\" class=\"nadpis_sekce\">"._SETUP_COMMENTS."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_COMMENTS_ANONYM."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_comm_anonym'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_comm_anonym\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_COMMENTS_AUTOFILL."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_comm_autofill'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_comm_autofill\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ARTICLES_COMM."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$ar['setup_article_comments']."\" name=\"setup_article_comments\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ARTICLES_COMM_FLAG."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_comm_flag'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_comm_flag\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ARTICLES_COMM_ADM_IMG."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_comm_adm_img'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_comm_adm_img\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ARTICLES_COMM_LINK."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_comm_link'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_comm_link\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ARTICLES_COMM_THUMBS."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_comm_thumbs'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_comm_thumbs\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ARTICLES_COMM_THUMBS_STEPS."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><span style=\"font-weight:bold;\">-</span>";
	echo"		<input type=\"text\" value=\"".$ar['setup_comm_thumbs_minus_4']."\" name=\"setup_comm_thumbs_minus_4\" size=\"3\" maxlength=\"4\" style=\"background-color:#ff0000;\">";
	echo"		<input type=\"text\" value=\"".$ar['setup_comm_thumbs_minus_3']."\" name=\"setup_comm_thumbs_minus_3\" size=\"3\" maxlength=\"4\" style=\"background-color:#a36109;\">";
	echo"		<input type=\"text\" value=\"".$ar['setup_comm_thumbs_minus_2']."\" name=\"setup_comm_thumbs_minus_2\" size=\"3\" maxlength=\"4\" style=\"background-color:#f68e56;\">";
	echo"		<input type=\"text\" value=\"".$ar['setup_comm_thumbs_minus_1']."\" name=\"setup_comm_thumbs_minus_1\" size=\"3\" maxlength=\"4\" style=\"background-color:#fdc689;\">";
	echo"		 0 ";
	echo"		<input type=\"text\" value=\"".$ar['setup_comm_thumbs_plus_1']."\" name=\"setup_comm_thumbs_plus_1\" size=\"3\" maxlength=\"4\" style=\"background-color:#c4df9b;\">";
	echo"		<input type=\"text\" value=\"".$ar['setup_comm_thumbs_plus_2']."\" name=\"setup_comm_thumbs_plus_2\" size=\"3\" maxlength=\"4\" style=\"background-color:#39b44a;\">";
	echo"		<input type=\"text\" value=\"".$ar['setup_comm_thumbs_plus_3']."\" name=\"setup_comm_thumbs_plus_3\" size=\"3\" maxlength=\"4\" style=\"background-color:#598527;\">";
	echo"		<input type=\"text\" value=\"".$ar['setup_comm_thumbs_plus_4']."\" name=\"setup_comm_thumbs_plus_4\" size=\"3\" maxlength=\"4\" style=\"background-color:#005825;\"><span style=\"font-weight:bold;\">+</span>";
	echo "		</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_COMMENTS_RULES."</strong><br><input name=\"setup_lang_comments_rules_checkbox\" type=\"checkbox\" value=\"1\"></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><textarea cols=\"70\" rows=\"15\" name=\"setup_lang_comments_rules\">".$ar['setup_lang_comments_rules']."</textarea></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span  id=\"tab_6\" class=\"nadpis_sekce\">"._SETUP_GUEST."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_GUEST_COMMENTS."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_guestbook_comments']."\" name=\"setup_guestbook_comments\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span  id=\"tab_7\" class=\"nadpis_sekce\">"._SETUP_FORUM."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_TITLE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$ar['setup_lang_forum_title']."\" name=\"setup_lang_forum_title\" size=\"60\" maxlength=\"100\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_TOPICS_HITS."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$ar['setup_forum_topics_on_page']."\" name=\"setup_forum_topics_on_page\" size=\"2\" maxlength=\"2\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_POSTS_HITS."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$ar['setup_forum_posts_on_page']."\" name=\"setup_forum_posts_on_page\" size=\"2\" maxlength=\"2\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_TIME."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$ar['setup_forum_joining_time']."\" name=\"setup_forum_joining_time\" size=\"3\" maxlength=\"4\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_ANONYM."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"radio\" value=\"1\" name=\"setup_forum_anonym\" "; if ($ar['setup_forum_anonym'] == 1){echo "checked";} echo ">"._CMN_YES."&nbsp;&nbsp;&nbsp;<input type=\"radio\" value=\"0\" name=\"setup_forum_anonym\" "; if ($ar['setup_forum_anonym'] == 0){echo "checked";} echo ">"._CMN_NO."</td>\n";
	echo "	</tr>\n";
	echo "	<tr class=\"forum-text-popisu\" align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_OPEN."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"radio\" value=\"1\" name=\"setup_forum_open\" "; if ($ar['setup_forum_open'] == 1){echo "checked";} echo ">"._CMN_YES."&nbsp;&nbsp;&nbsp;<input type=\"radio\" value=\"0\" name=\"setup_forum_open\" "; if ($ar['setup_forum_open'] == 0){echo "checked";} echo ">"._CMN_NO."</td>\n";
	echo "	</tr>\n";
	echo "	<tr class=\"forum-text-popisu\" align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_ALLOW_QUOTE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"radio\" value=\"1\" name=\"setup_forum_allow_quote\" "; if ($ar['setup_forum_allow_quote'] == 1){echo "checked";} echo ">"._CMN_YES."&nbsp;&nbsp;&nbsp;<input type=\"radio\" value=\"0\" name=\"setup_forum_allow_quote\" "; if ($ar['setup_forum_allow_quote'] == 0){echo "checked";} echo ">"._CMN_NO."</td>\n";
	echo "	</tr>\n";
	echo "	<tr class=\"forum-text-popisu\" align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_ALLOW_EDIT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"radio\" value=\"1\" name=\"setup_forum_allow_edit\" "; if ($ar['setup_forum_allow_edit'] == 1){echo "checked";} echo ">"._CMN_YES."&nbsp;&nbsp;&nbsp;<input type=\"radio\" value=\"0\" name=\"setup_forum_allow_edit\" "; if ($ar['setup_forum_allow_edit'] == 0){echo "checked";} echo ">"._CMN_NO."</td>\n";
	echo "	</tr>\n";
	echo "	<tr class=\"forum-text-popisu\" align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_ALLOW_DEL."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"radio\" value=\"1\" name=\"setup_forum_allow_del\" "; if ($ar['setup_forum_allow_del'] == 1){echo "checked";} echo ">"._CMN_YES."&nbsp;&nbsp;&nbsp;<input type=\"radio\" value=\"0\" name=\"setup_forum_allow_del\" "; if ($ar['setup_forum_allow_del'] == 0){echo "checked";} echo ">"._CMN_NO."</td>\n";
	echo "	</tr>\n";
	echo "	<tr class=\"forum-text-popisu\" align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_ALLOW_SIG."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"radio\" value=\"1\" name=\"setup_forum_allow_sig\" "; if ($ar['setup_forum_allow_sig'] == 1){echo "checked";} echo ">"._CMN_YES."&nbsp;&nbsp;&nbsp;<input type=\"radio\" value=\"0\" name=\"setup_forum_allow_sig\" "; if ($ar['setup_forum_allow_sig'] == 0){echo "checked";} echo ">"._CMN_NO."</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_FORUM_AVATAR_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['avatar'][2]."\" name=\"setup_forum_avatar_max_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_AVATAR_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['avatar'][3]."\" name=\"setup_forum_avatar_max_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_FORUM_AVATAR_FILESIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['avatar'][4]."\" name=\"setup_forum_avatar_max_filesize\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_8\" class=\"nadpis_sekce\">"._SETUP_POLL."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_POLL_TIME_IP."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_poll_iptime']."\" name=\"setup_poll_iptime\" size=\"4\" maxlength=\"5\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_POLL_SHOW_RESULTS."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_poll_show_results'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_poll_show_results\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_POLL_RESULTS_AS_NUMBER."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"radio\" "; if ($ar['setup_poll_results_as_number'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_poll_results_as_number\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_POLL_RESULTS_AS_PERCENTAGE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"radio\" "; if ($ar['setup_poll_results_as_number'] == 0){echo "checked";} echo " value=\"0\" name=\"setup_poll_results_as_number\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_9\" class=\"nadpis_sekce\">"._SETUP_LINKS."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_LINKS_IMG1_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['link_1'][2]."\" name=\"setup_links_img1_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_LINKS_IMG1_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['link_1'][3]."\" name=\"setup_links_img1_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_LINKS_IMG1_SIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['link_1'][4]."\" name=\"setup_links_img1_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_LINKS_IMG2_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['link_2'][2]."\" name=\"setup_links_img2_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_LINKS_IMG2_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['link_2'][3]."\" name=\"setup_links_img2_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_LINKS_IMG2_SIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['link_2'][4]."\" name=\"setup_links_img2_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><br></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<p class=\"dropcontent\">\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_10\" class=\"nadpis_sekce\">"._SETUP_ACCESORIES."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_ACCESORIES_POPUP_LOGO."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"file\" name=\"setup_accessories_popup_logo\" size=\"30\"> 440x90px (.gif, .jpg, .png)<br>\n";
					if ($ar['setup_accessories_popup_logo'] != ""){ echo "<img src=\"".$url_project_images.$ar['setup_accessories_popup_logo']."\">";}
	echo "		</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_9\" class=\"nadpis_sekce\">"._SETUP_CATEGORY."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_TODO_IMG_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['category'][2]."\" name=\"setup_cat_img_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['category'][3]."\" name=\"setup_cat_img_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_SIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['category'][4]."\" name=\"setup_cat_img_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_9\" class=\"nadpis_sekce\">"._SETUP_RSS."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_TODO_IMG_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['rss'][2]."\" name=\"setup_rss_img_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['rss'][3]."\" name=\"setup_rss_img_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_SIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['rss'][4]."\" name=\"setup_rss_img_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_9\" class=\"nadpis_sekce\">"._SETUP_GAMES."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_TODO_IMG_WIDTH." 1</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['games_1'][2]."\" name=\"setup_games_img_1_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_HEIGHT." 1</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['games_1'][3]."\" name=\"setup_games_img_1_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_SIZE." 1</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['games_1'][4]."\" name=\"setup_games_img_1_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_TODO_IMG_WIDTH." 2</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['games_2'][2]."\" name=\"setup_games_img_2_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_HEIGHT." 2</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['games_2'][3]."\" name=\"setup_games_img_2_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_SIZE." 2</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['games_2'][4]."\" name=\"setup_games_img_2_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_9\" class=\"nadpis_sekce\">"._SETUP_PROFILE."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_PROFILE_IMG_1_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['profile_1'][2]."\" name=\"setup_profile_img_1_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_PROFILE_IMG_1_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['profile_1'][3]."\" name=\"setup_profile_img_1_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_PROFILE_IMG_1_SIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['profile_1'][4]."\" name=\"setup_profile_img_1_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_9\" class=\"nadpis_sekce\">"._SETUP_SMILES."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_TODO_IMG_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['smiles'][2]."\" name=\"setup_smiles_img_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['smiles'][3]."\" name=\"setup_smiles_img_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_SIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['smiles'][4]."\" name=\"setup_smiles_img_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_9\" class=\"nadpis_sekce\">"._SETUP_TODO."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_TODO_IMG_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['todo'][2]."\" name=\"setup_todo_img_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['todo'][3]."\" name=\"setup_todo_img_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_TODO_IMG_SIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['todo'][4]."\" name=\"setup_todo_img_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\" style=\"background-color:FFDEDF\">\n";
	echo "		<td width=\"850\" colspan=\"2\"><span id=\"tab_9\" class=\"nadpis_sekce\">"._SETUP_LEAGUE."</span><br></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_LEAGUE_EMAIL_FROM_NAME."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_league_email_from_name']."\" name=\"setup_league_email_from_name\" size=\"40\" maxlength=\"50\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_LEAGUE_EMAIL."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_league_email']."\" name=\"setup_league_email\" size=\"40\" maxlength=\"80\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_LEAGUE_EMAIL_SUBJECT_ADD_PLAYER."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$ar['setup_lang_league_email_subject_add_player']."\" name=\"setup_lang_league_email_subject_add_player\" size=\"40\" maxlength=\"80\"></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_LEAGUE_EMAIL_BODY_ADD_PLAYER."</strong><br><input name=\"setup_lang_league_email_body_add_player_checkbox\" type=\"checkbox\" value=\"1\"><br><br>\n";
	echo "		[{team_captain}]<br>\n";
	echo "		[{team_name}]<br>\n";
	echo "		[{team_request_link}]<br>\n";
	echo "		</td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><textarea cols=\"70\" rows=\"15\" name=\"setup_lang_league_email_body_add_player\">".$ar['setup_lang_league_email_body_add_player']."</textarea></td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_LEAGUE_TEAM_LOGO_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['league_team_logo'][2]."\" name=\"setup_league_team_logo_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_LEAGUE_TEAM_LOGO_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['league_team_logo'][3]."\" name=\"setup_league_team_logo_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_LEAGUE_TEAM_LOGO_SIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['league_team_logo'][4]."\" name=\"setup_league_team_logo_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><br><strong>"._SETUP_LEAGUE_AWARD_WIDTH."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><br><input type=\"text\" value=\"".$setup_images['league_award'][2]."\" name=\"setup_league_award_width\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_LEAGUE_AWARD_HEIGHT."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['league_award'][3]."\" name=\"setup_league_award_height\" size=\"4\" maxlength=\"4\">px</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_LEAGUE_AWARD_SIZE."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"text\" value=\"".$setup_images['league_award'][4]."\" name=\"setup_league_award_size\" size=\"6\" maxlength=\"6\">Bytes</td>\n";
	echo "	</tr>\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"250\" align=\"right\"><strong>"._SETUP_LEAGUE_CHECK_24."</strong></td>\n";
	echo "		<td width=\"500\" align=\"left\"><input type=\"checkbox\" "; if ($ar['setup_league_check_24'] == 1){echo "checked";} echo " value=\"1\" name=\"setup_league_check_24\"></td>\n";
	echo "	</tr>\n";
	echo "</table>\n";
	echo "</p>\n";
	echo "<table width=\"857\" cellspacing=\"2\" cellpadding=\"1\" class=\"eden_main_table\">\n";
	echo "	<tr align=\"left\" valign=\"top\">\n";
	echo "		<td width=\"750\" colspan=\"2\"><br><br>\n";
	echo "			<input type=\"hidden\" name=\"confirm\" value=\"true\">\n";
	echo "			<input type=\"hidden\" name=\"project\" value=\"".$_SESSION['project']."\">\n";
	echo "			<input type=\"submit\" Value=\""._SETUP_SET."\" class=\"eden_button\">\n";
	echo "		</td>\n";
	echo "	</tr>\n";
	echo "</table>";
	echo "</form>\n";
}
include ("inc.header.php");
	if ($_GET['action'] == "") { Setup();}
include ("inc.footer.php");