<?php
if ($_GET['lang'] != ""){$lang = $_GET['lang'];} elseif ($_POST['lang'] != ""){$lang = $_POST['lang'];} else {$lang = "cz";}
//Nastaveni nenacitani spatneho jazyka z functions.phps
$eden_editor_add_include_lang = true;
$eden_editor_tinymce_plugin_path = "../../../..";
require_once ($eden_editor_tinymce_plugin_path."/lang/lang-".$lang.".php");
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n";
echo "<head>\n";
echo "<title>"._EDITOR_CARDS_ADD."</title>\n";
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n";
echo "<style type=\"text/css\">\n";
echo ".eden_redcardsuit, .eden_blackcardsuit {border-bottom: #888 1px solid; border-left: #888 1px solid; padding-bottom: 0px; background-color: #ffc; margin: 0px 1px; padding-left: 1px; padding-right: 1px; font: 15px/150% courier; border-top: #888 1px solid; border-right: #888 1px solid; padding-top: 0px;cursor: pointer;}\n";
echo ".eden_redcardsuit {color: red}\n";
echo ".eden_blackcardsuit {color: black}\n";
echo "</style>\n";
echo "<script type=\"text/javascript\" src=\"../../tiny_mce_popup.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"js/cards.js\"></script>\n";
echo "<script type=\"text/javascript\">\n";
echo "<!--\n";
echo "	function insert_card (card){\n";
echo "		if (card == \"Aclubs\"){real_card = '<span class=\"eden_blackcardsuit\">A&clubs;</span> ';}\n";
echo "		if (card == \"Kclubs\"){real_card = '<span class=\"eden_blackcardsuit\">K&clubs;</span> ';}\n";
echo "		if (card == \"Qclubs\"){real_card = '<span class=\"eden_blackcardsuit\">Q&clubs;</span> ';}\n";
echo "		if (card == \"Jclubs\"){real_card = '<span class=\"eden_blackcardsuit\">J&clubs;</span> ';}\n";
echo "		if (card == \"10clubs\"){real_card = '<span class=\"eden_blackcardsuit\">10&clubs;</span> ';}\n";
echo "		if (card == \"9clubs\"){real_card = '<span class=\"eden_blackcardsuit\">9&clubs;</span> ';}\n";
echo "		if (card == \"8clubs\"){real_card = '<span class=\"eden_blackcardsuit\">8&clubs;</span> ';}\n";
echo "		if (card == \"7clubs\"){real_card = '<span class=\"eden_blackcardsuit\">7&clubs;</span> ';}\n";
echo "		if (card == \"6clubs\"){real_card = '<span class=\"eden_blackcardsuit\">6&clubs;</span> ';}\n";
echo "		if (card == \"5clubs\"){real_card = '<span class=\"eden_blackcardsuit\">5&clubs;</span> ';}\n";
echo "		if (card == \"4clubs\"){real_card = '<span class=\"eden_blackcardsuit\">4&clubs;</span> ';}\n";
echo "		if (card == \"3clubs\"){real_card = '<span class=\"eden_blackcardsuit\">3&clubs;</span> ';}\n";
echo "		if (card == \"2clubs\"){real_card = '<span class=\"eden_blackcardsuit\">2&clubs;</span> ';}\n";
echo "      if (card == \"Aspades\"){real_card = '<span class=\"eden_blackcardsuit\">A&spades;</span> ';}\n";
echo "		if (card == \"Kspades\"){real_card = '<span class=\"eden_blackcardsuit\">K&spades;</span> ';}\n";
echo "		if (card == \"Qspades\"){real_card = '<span class=\"eden_blackcardsuit\">Q&spades;</span> ';}\n";
echo "		if (card == \"Jspades\"){real_card = '<span class=\"eden_blackcardsuit\">J&spades;</span> ';}\n";
echo "		if (card == \"10spades\"){real_card = '<span class=\"eden_blackcardsuit\">10&spades;</span> ';}\n";
echo "		if (card == \"9spades\"){real_card = '<span class=\"eden_blackcardsuit\">9&spades;</span> ';}\n";
echo "		if (card == \"8spades\"){real_card = '<span class=\"eden_blackcardsuit\">8&spades;</span> ';}\n";
echo "		if (card == \"7spades\"){real_card = '<span class=\"eden_blackcardsuit\">7&spades;</span> ';}\n";
echo "		if (card == \"6spades\"){real_card = '<span class=\"eden_blackcardsuit\">6&spades;</span> ';}\n";
echo "		if (card == \"5spades\"){real_card = '<span class=\"eden_blackcardsuit\">5&spades;</span> ';}\n";
echo "		if (card == \"4spades\"){real_card = '<span class=\"eden_blackcardsuit\">4&spades;</span> ';}\n";
echo "		if (card == \"3spades\"){real_card = '<span class=\"eden_blackcardsuit\">3&spades;</span> ';}\n";
echo "		if (card == \"2spades\"){real_card = '<span class=\"eden_blackcardsuit\">2&spades;</span> ';}\n";
echo "      if (card == \"Ahearts\"){real_card = '<span class=\"eden_redcardsuit\">A&hearts;</span> ';}\n";
echo "		if (card == \"Khearts\"){real_card = '<span class=\"eden_redcardsuit\">K&hearts;</span> ';}\n";
echo "		if (card == \"Qhearts\"){real_card = '<span class=\"eden_redcardsuit\">Q&hearts;</span> ';}\n";
echo "		if (card == \"Jhearts\"){real_card = '<span class=\"eden_redcardsuit\">J&hearts;</span> ';}\n";
echo "		if (card == \"10hearts\"){real_card = '<span class=\"eden_redcardsuit\">10&hearts;</span> ';}\n";
echo "		if (card == \"9hearts\"){real_card = '<span class=\"eden_redcardsuit\">9&hearts;</span> ';}\n";
echo "		if (card == \"8hearts\"){real_card = '<span class=\"eden_redcardsuit\">8&hearts;</span> ';}\n";
echo "		if (card == \"7hearts\"){real_card = '<span class=\"eden_redcardsuit\">7&hearts;</span> ';}\n";
echo "		if (card == \"6hearts\"){real_card = '<span class=\"eden_redcardsuit\">6&hearts;</span> ';}\n";
echo "		if (card == \"5hearts\"){real_card = '<span class=\"eden_redcardsuit\">5&hearts;</span> ';}\n";
echo "		if (card == \"4hearts\"){real_card = '<span class=\"eden_redcardsuit\">4&hearts;</span> ';}\n";
echo "		if (card == \"3hearts\"){real_card = '<span class=\"eden_redcardsuit\">3&hearts;</span> ';}\n";
echo "		if (card == \"2hearts\"){real_card = '<span class=\"eden_redcardsuit\">2&hearts;</span> ';}\n";
echo "      if (card == \"Adiams\"){real_card = '<span class=\"eden_redcardsuit\">A&diams;</span> ';}\n";
echo "		if (card == \"Kdiams\"){real_card = '<span class=\"eden_redcardsuit\">K&diams;</span> ';}\n";
echo "		if (card == \"Qdiams\"){real_card = '<span class=\"eden_redcardsuit\">Q&diams;</span> ';}\n";
echo "		if (card == \"Jdiams\"){real_card = '<span class=\"eden_redcardsuit\">J&diams;</span> ';}\n";
echo "		if (card == \"10diams\"){real_card = '<span class=\"eden_redcardsuit\">10&diams;</span> ';}\n";
echo "		if (card == \"9diams\"){real_card = '<span class=\"eden_redcardsuit\">9&diams;</span> ';}\n";
echo "		if (card == \"8diams\"){real_card = '<span class=\"eden_redcardsuit\">8&diams;</span> ';}\n";
echo "		if (card == \"7diams\"){real_card = '<span class=\"eden_redcardsuit\">7&diams;</span> ';}\n";
echo "		if (card == \"6diams\"){real_card = '<span class=\"eden_redcardsuit\">6&diams;</span> ';}\n";
echo "		if (card == \"5diams\"){real_card = '<span class=\"eden_redcardsuit\">5&diams;</span> ';}\n";
echo "		if (card == \"4diams\"){real_card = '<span class=\"eden_redcardsuit\">4&diams;</span> ';}\n";
echo "		if (card == \"3diams\"){real_card = '<span class=\"eden_redcardsuit\">3&diams;</span> ';}\n";
echo "		if (card == \"2diams\"){real_card = '<span class=\"eden_redcardsuit\">2&diams;</span> ';}\n";
echo "
	var ed = tinyMCEPopup.editor, dom = ed.dom;\n
	tinyMCEPopup.execCommand('mceInsertContent', false, real_card);\n
	tinyMCEPopup.close();\n
";
echo "	}\n";
echo "-->\n";
echo "</script>\n";
echo "</head>\n";
echo "<body>\n";
	echo "	 <table cellpadding=\"0\" cellspacing=\"1\">\n";
	echo "	 	<tr>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('Aclubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">A&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('Kclubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">K&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('Qclubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">Q&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('Jclubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">J&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('10clubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">10&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('9clubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">9&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('8clubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">8&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('7clubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">7&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('6clubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">6&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('5clubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">5&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('4clubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">4&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('3clubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">3&clubs;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('2clubs');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">2&clubs;</span></td>\n";
	echo "	 	</tr>\n";
	echo "	 	<tr>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('Aspades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">A&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('Kspades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">K&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('Qspades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">Q&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('Jspades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">J&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('10spades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">10&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('9spades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">9&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('8spades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">8&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('7spades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">7&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('6spades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">6&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('5spades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">5&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('4spades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">4&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('3spades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">3&spades;</span></td>\n";
	echo "	 		<td><span class=\"eden_blackcardsuit\" onclick=\"insert_card('2spades');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">2&spades;</span></td>\n";
	echo "	 	</tr>\n";
	echo "	 	<tr>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('Ahearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">A&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('Khearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">K&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('Qhearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">Q&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('Jhearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">J&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('10hearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">10&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('9hearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">9&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('8hearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">8&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('7hearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">7&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('6hearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">6&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('5hearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">5&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('4hearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">4&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('3hearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">3&hearts;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('2hearts');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">2&hearts;</span></td>\n";
	echo "	 	</tr>\n";
	echo "	 	<tr>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('Adiams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">A&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('Kdiams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">K&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('Qdiams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">Q&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('Jdiams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">J&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('10diams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">10&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('9diams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">9&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('8diams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">8&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('7diams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">7&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('6diams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">6&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('5diams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">5&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('4diams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">4&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('3diams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">3&diams;</span></td>\n";
	echo "	 		<td><span class=\"eden_redcardsuit\" onclick=\"insert_card('2diams');\" onmouseover=\"this.style.border='1px solid #000000'\" onmouseout=\"this.style.border='1px solid #888888'\">2&diams;</span></td>\n";
	echo "	 	</tr>\n";
	echo "	 </table>\n";
echo "</body>\n";
echo "</html>";