tinyMCE.addI18n('en.advimage_dlg',{
align:"Alignment",
align_baseline:"Baseline",
align_bottom:"Bottom",
align_left:"Left",
align_middle:"Middle",
align_right:"Right",
align_textbottom:"Text bottom",
align_texttop:"Text top",
align_top:"Top",
alt:"Image description",
alt_image:"Alternative image",
border:"Border",
classes:"Classes",
constrain_proportions:"Constrain proportions",
dialog_title:"Insert/edit image",
dimensions:"Dimensions",
example_img:"Appearance preview image",
general:"General",
help:"Help",
help_text:"Here will be simple help for images",
hspace:"Horizontal space",
id:"Id",
image_list:"Image list",
langcode:"Language code",
langdir:"Language direction",
link:"Link",
link_img:"Image Link",
link_to:"Link to",
link_to_img:"Image",
link_to_none:"None",
link_to_url:"URL",
link_url:"URL Link",
list:"Image list",
long_desc:"Long description link",
ltr:"Left to right",
map:"Image map",
misc:"Miscellaneous",
missing_alt:"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
mouseout:"for mouse out",
mouseout2:"for mouse out",
mouseover:"for mouse over",
mouseover2:"for mouse over",
preview:"Preview",
rtl:"Right to left",
src_from:"Image from",
src_from_dsk:"Disk",
src_from_lib:"Library",
src0:"Image from library",
src1:"Image from disk",
src2:"Image from library",
src3:"Image from disk",
style:"Style",
swap_image:"Swap image",
tab_advanced:"Advanced",
tab_appearance:"Appearance",
tab_general:"General",
tab_help:"Help",
target:"Target",
title:"Title",
vspace:"Vertical space"
});